### ISSUE TITLE
How to Get ID & Check Updates by Setup

### ISSUE THREAD

**Issue by ghost** [MachineGunnur/GOG-Games#101]
To get a game title from most GOG installers:
`7z l setup_airships_conquer_the_skies_1.0.13.4_\(33715\).exe | grep -m 1 "ProductName: " | sed -e 's/[[:space:]]*$//; s/^ProductName: //'`

Example Output:
> Airships - Conquer the Skies

To get the version/build for a new installer:
`7z l setup_airships_conquer_the_skies_1.0.13.4_\(33715\).exe | grep "ProductVersion: " | grep -v "ProductVersion: 0.0.0.0" | grep -m 1 . | sed -e 's/[[:space:]]*$//; s/^ProductVersion: //'`

Example Output:
> 1.0.13.4.[52780525203594009]

To get the verision only, new installers:
`7z l setup_airships_conquer_the_skies_1.0.13.4_\(33715\).exe | grep "ProductVersion: " | grep -v "ProductVersion: 0.0.0.0" | grep -m 1 . | sed -n -e 's/[[:space:]]*$//; s/^ProductVersion: //; s/^\(.*\)\.\[[0-9].*[0-9]\]$/\1/p'`

Example Output:
> 1.0.13.4

To get the build only, new installers:
`7z l setup_airships_conquer_the_skies_1.0.13.4_\(33715\).exe | grep "ProductVersion: " | grep -v "ProductVersion: 0.0.0.0" | grep -m 1 . | sed -n -e 's/[[:space:]]*$//; s/^ProductVersion: //; s/^.*\.\[\([0-9].*[0-9]\)\]$/\1/p'`

Example Output:
> 52780525203594009

For old only a version is availible:
`7z l setup_fallout_2.1.0.18.exe | grep "ProductVersion: " | grep -v "ProductVersion: 0.0.0.0" | grep -m 1 . | sed -e 's/[[:space:]]*$//; s/^ProductVersion: //'`

Example Output:
> 2.1.0.18

Get the setup slug, new installers:
`name="setup_airships_conquer_the_skies_1.0.13.4_(33715).exe"
echo "${name}" | sed -n -e "s/setup_//; s/patch_//; s/^\(.*\)_$( 7z l "${name}" | grep "ProductVersion: " | grep -v "ProductVersion: 0.0.0.0" | grep -m 1 . | sed -n -e 's/[[:space:]]*$//; s/^ProductVersion: //; s/^\(.*\)\.\[[0-9].*[0-9]\]$/\1/p' )_(.*)\.exe/\1/p"`

Example Output:
> airships_conquer_the_skies

Get the setup slug, old installers:
`name="setup_fallout_2.1.0.18.exe"
echo "${name}" | sed -n -e "s/setup_//; s/patch_//; s/^\(.*\)_$( 7z l "${name}" | grep "ProductVersion: " | grep -v "ProductVersion: 0.0.0.0" | grep -m 1 . | sed -e 's/[[:space:]]*$//; s/^ProductVersion: //' )\.exe/\1/p"`

Example Output:
> fallout

Query a site to get an installer ID:
`name="setup_airships_conquer_the_skies_1.0.13.4_(33715).exe"`
`title="$( 7z l "${name}" | grep -m 1 "ProductName: " | sed -e 's/[[:space:]]*$//; s/^ProductName: //; s/\(.*\)/\L\1/' | sed 's/[^a-z0-9 \-\|]//g' )"`
`lctitle="$( echo "${title}" | sed 's/\(.*\)/\L\1/; s/[^a-z0-9]//g' )"`
`query="$( python -c $'try: import urllib.request as urllib\nexcept: import urllib\nimport sys\nsys.stdout.write(urllib.quote(input()))' <<< "$( echo ${title} | sed -e 's/[[:space:]]*$//' )" )"`
`wget -q -O - "https://www.gogdb.org/products?search=${query}" | grep -B 10 "<td class=\"col-type\">Game</td>" | grep -A 1 "<a href=\"/product/.*\" class=\"hoveronly\">" | sed "s/&amp;/\&/g; s/&#39;/'/g; s/.*\/product\///g; s/\" class=.*//g; s/\(.*\)/\L\1/; s/[^a-z0-9\;]//g" | grep -B 1 -m 1 "^${lctitle}$" | grep -v "^${lctitle}$"`
GOG instead of GOGdb can be used, too:
`wget -q -O - "https://embed.gog.com/games/ajax/filtered?availibility=new&mediaType=game&page=1&sort=date&search=${query}" | sed 's/{"customAttributes":/\n/g' | sed -n -e 's/.*,"isInDevelopment":.*,"id":\(.*\),"releaseDate":.*,"fromObject":{"date":"\([0-9][0-9][0-9][0-9]-.*[0-9]-.*[0-9]\) [0-9].*","timezone_type":.*,"toObject":{"date":.*,"title":"\(.*\)","image":".*"isGame":.*,"slug":"\(.*\)","isWishlistable":.*/\3 ;;;; \1/p' | sed "s/\\\u0026/\&/g; s/\\\u0027/'/g; s/\\\u003E/>/g; s/\\\u00a0/ /g; s/\\\u00ae/®/g; s/\\\u00b7/·/g; s/\\\u00db/Û/g; s/\\\u00f6/ö/g; s/\\\u00fc/ü/g; s/\\\u2013/–/g; s/\\\u2014/—/g; s/\\\u2018/‘/g; s/\\\u2019/’/g; s/\\\u2122/™/g; s/\\\ufeff/﻿/g; s/\(.*\)/\L\1/" | sed 's/[^a-z0-9\;]//g' | grep "^${lctitle};;;;" | sed 's/.*;;;;//g'`

Example Output:
> 1232664301

Compare Version/Build against GOG by ID:
`gog_id=1440148836`
`name="setup_fallout_2.1.0.18.exe"`
`my_t="$( 7z l "${name}" | grep -m 1 "ProductName: " | sed -e 's/[[:space:]]*$//; s/^ProductName: //' )"`
`my_b="$( 7z l "${name}" | grep "ProductVersion: " | grep -v "ProductVersion: 0.0.0.0" | grep -m 1 . | sed -n -e 's/[[:space:]]*$//; s/^ProductVersion: //; s/^.*\.\[\([0-9].*[0-9]\)\]$/\1/p' )"`
`my_v="$(7z l "${name}" | grep "ProductVersion: " | grep -v "ProductVersion: 0.0.0.0" | grep -m 1 . | sed -n -e 's/[[:space:]]*$//; s/^ProductVersion: //; s/^\(.*\)\.\[[0-9].*[0-9]\]$/\1/p' | sed 's/\(.*\)/\L\1/; s/[^a-z0-9\.]//g')"`
`gog_v_raw="$( wget -q -O - "https://api.gog.com/products/${gog_id}?expand=downloads" | sed 's/"version":/\n"version":/g' | grep -m 1 "\"version\"" | sed 's/"version"://; s/"total_size":.*//g; s/,$//g; s/"//g' )"`
`gog_v="$( echo "${gog_v_raw}" | sed 's/\(.*\)/\L\1/; s/[^a-z0-9\.]//g' )"`
`gog_b="$( wget -q -O - "https://content-system.gog.com/products/${gog_id}/os/windows/builds?generation=2" | grep -B 4 "\"version_name\": \"${gog_v_raw}\"," | grep -m 1 -E "\"build_id\":" | sed 's/.*"build_id": //g; s/,$//g; s/"//g' )"`
`if [[ -z "${my_t}" ]]; then`
`	my_t="${name}"`
`fi`
`if [[ -z "${my_v}" ]]; then`
`	echo "ERROR: Can't read Setup" 2>&1`
`elif [[ -z "${gog_v}" ]]; then`
`	echo "ERROR: Unknown GOG Version" 2>&1`
`elif [[ "${gog_v}" = null ]]; then`
`	echo "SUCCESS: \"${my_t}\" IS OK (Legacy)"`
`elif [[ -z "${gog_b}" ]]; then`
`	echo "ERROR: Unknown GOG Build" 2>&1`
`elif [[ "${gog_v}" = "${my_v}" ]]; then`
`	if [[ "${gog_b}" = "${my_b}" ]]; then`
`		echo "SUCCESS: \"${my_t}\" IS OK"`
`	else`
`		echo "UPDATE: \"${my_t}\" TO NEW BUILD" 2>&1`
`	fi`
`elif [[ "${gog_v}" != "${my_v}" ]]; then`
`	echo "UPDATE: \"${my_t}\" TO \"${gog_v_raw}\"" 2>&1`
`fi`

Example Output:
> UPDATE "Fallout" TO "1.2"

BONUS CODE
Show recent GOG releases by ID/Slug in Terminal:
`wget -q -O - "https://embed.gog.com/games/ajax/filtered?availibility=new&mediaType=game&page=1&sort=date" | sed 's/{"customAttributes":/\n/g' | grep -Ev "\"isComingSoon\":true,"\|_demo | sed -n -e 's/.*,"isInDevelopment":.*,"id":\(.*\),"releaseDate":.*,"fromObject":{"date":"\([0-9][0-9][0-9][0-9]-.*[0-9]-.*[0-9]\) [0-9].*","timezone_type":.*,"toObject":{"date":.*,"title":"\(.*\)","image":".*"isGame":.*,"slug":"\(.*\)","isWishlistable":.*/\2 | \1 | \4/p' | grep -E "$(date +%F)"\|"$(date --date="$(date) -1 day" +%F)"\|"$(date --date="$(date) -2 days" +%F)"\|"$(date --date="$(date) -3 days" +%F)"\|"$(date --date="$(date) -4 days" +%F)"\|"$(date --date="$(date) -5 days" +%F)"\|"$(date --date="$(date) -6 days" +%F)"\|"1991-12-25" | sed "s/^1991-12-25 /           /g; s/\\\u0026/\&/g; s/\\\u0027/'/g; s/\\\u003E/>/g; s/\\\u00a0/ /g; s/\\\u00ae/®/g; s/\\\u00b7/·/g; s/\\\u00db/Û/g; s/\\\u00f6/ö/g; s/\\\u00fc/ü/g; s/\\\u2013/–/g; s/\\\u2014/—/g; s/\\\u2018/‘/g; s/\\\u2019/’/g; s/\\\u2122/™/g; s/\\\ufeff/﻿/g" | sed 's/^....-..-.. . //g'`

THE LICENSE
> This is free and unencumbered software released into the public domain.
> 
> Anyone is free to copy, modify, publish, use, compile, sell, or
> distribute this software, either in source code form or as a compiled
> binary, for any purpose, commercial or non-commercial, and by any
> means.
> 
> In jurisdictions that recognize copyright laws, the author or authors
> of this software dedicate any and all copyright interest in the
> software to the public domain. We make this dedication for the benefit
> of the public at large and to the detriment of our heirs and
> successors. We intend this dedication to be an overt act of
> relinquishment in perpetuity of all present and future rights to this
> software under copyright law.
> 
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
> EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
> MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
> IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
> OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
> ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
> OTHER DEALINGS IN THE SOFTWARE.
> 
> For more information, please refer to <https://unlicense.org>

**Comment by MachineGunnur** [comment]
i have no use for this. archiving. I appreciate your work of course!

**Comment by tomgatos** [comment]
CBA :)))
