### ISSUE TITLE
Clicking the Cart icon

### ISSUE THREAD

**Issue by dhaos21** [MachineGunnur/GOG-Games#104]
Clicking on the cart icon (go to gog store) gives a 404 error (as it adds https://goggamespc7v6z5e.onion.ws/ infront of the valid gog URL)

**Comment by MachineGunnur** [comment]
you are using other way to get to site via proxy :

> Alternative:

    Go to: https://goggamespc7v6z5e.onion.ws/


this way has bugs (like theone you encountered above). can't fix. use Tor browser for complete site functionality!
