### ISSUE TITLE
Starpoint Gemini Warlords is Removed

### ISSUE THREAD

**Issue by ghost** [MachineGunnur/GOG-Games#106]
Used to recheck my collection but now the game is removed. Why so?

My collection is very small, just 4 TB and 1,282 games. Once in a while a script checks files to autoupdate from Zippyshare. May I ask were any more games removed and why? I remember an issue on Surviving Mars BIN but to have an entire game disappear is something new. According to the Wayback Machine, the game was there on 2019-09-05.

**Comment by KottaGotta** [comment]
Thanks for solving! Please can offer an explanation to the mystery? Will be great to know.
