### ISSUE TITLE
GOG Games Interface Improvements

### ISSUE THREAD

**Issue by ghost** [MachineGunnur/GOG-Games#107]
Is it possible to: Display File Size in Bytes within the HTML game page; Demonstrate a Full last Update Date with Time (GMT+0) on "Browse All Games"; within HTML separately show Exact Latest Game version and Build for each game? For example, Terraria. For a wierd reason GOG remade an installer with exactly the same name, thus after it disappeared from RSS, no one can tell if a game was updated, even worse, the page itself and All don't have any clue, even though an update was performed: Before the checksum didn't match Connie's DAT, now it does.

Strangely "New Releases" sometimes includes "Updates" when a "new" clearly not a new release: Why? Anyway, since you're already timestamping everything, just can use the latest Date from "gog-times.sh -m [file] --" for example (of course don't forget to convert to GMT+0 like GOG Builds does, don't use own timezone), same to the size, "ls" provides that easily. As was already shown, most games are openable by 7z and to get a version or a Build shouldn't be difficult, a "latest update" date who shows a date of the last setup on HTML is helpful.

As well known, GOG Games still has no official client. Therefore, as a user, to update a big collection requieres either a incredible level of Insanity, doing so by hand, losing a lot of time, or being able to script something and make use of the fact that Zippyshare has a 5 KB unnoficial Bash [downloader](https://github.com/JuniYadi/zippyshare). RSS is too small, no help if doing rarely, so in order to update I am using IDs as you have in RSS as my folders, grabbing a list of files and compare. Does GG have any good way to tell if an update when having only a filelist, you know???

**Comment by tomgatos** [comment]
Showing Filesize in bytes (as in SQL) by default should solve the above without any additional fields: GOG installers aren't the same size even when same names... ;)

**Comment by coreyemtp** [comment]
I've noticed that your "new releases" item is caused by additional DLC added to the game. I'm okay with having it show in that section, as it's an indicator of new content. Just my opinion.
