### ISSUE TITLE
Missing Deluxe on Age of Wonders: Planetfall & BATTLETECH

### ISSUE THREAD

**Issue by KottaGotta** [MachineGunnur/GOG-Games#109]
Hi,

Availible on Torrminatorr:
`SHA1 (setup_age_of_wonders_planetfall_-_deluxe_edition_content_pack_1.1.0.3_(64bit)_(34231).exe) = 6d48f02b7fdad1666a897f698fc4f6c071a7c18a`
`SHA1 (setup_digital_deluxe_content_1.8.0-629r_(64bit)_(34198).exe) = a16916d7670a7ebd36163e5f890c05789770df82`
`BLAKE2b (setup_age_of_wonders_planetfall_-_deluxe_edition_content_pack_1.1.0.3_(64bit)_(34231).exe) = f4aa55c96ad13354e4745c6502471ce1d1b4ae47077af33063ff1f5cfc00fc87662c8a2d5fd28b828e154ae27c6ba369bbd875931fe19c52483008e979607ab9`
`BLAKE2b (setup_digital_deluxe_content_1.8.0-629r_(64bit)_(34198).exe) = dd915835a8884c5d366fca8d44ffbddab8be25c83faf9fa914b6094bc9d0a4b9295446b0561ecb19af3f469a78d7985eb0cdef197f506ca2d69b34240e7215c1`
`SHA512 (setup_age_of_wonders_planetfall_-_deluxe_edition_content_pack_1.1.0.3_(64bit)_(34231).exe) = b04b3a8404fd0d9f7c48bd959b530c0667107fb7be897f0b96038b4d4f87663879f73d276279b164171c0deb1d39cfef81fb5b47133573a9efff8610c9d0fe60`
`SHA512 (setup_digital_deluxe_content_1.8.0-629r_(64bit)_(34198).exe) = 3c0d8b32c2ac2a74fddd4beed2a3efb2898297dfe57ad661caec0e22561ea60232f9b0bed80fb8dd0263fe629f11a67a1a46e524b8b2e672cecb551cd1d444bf`
`SHA3-512 (setup_age_of_wonders_planetfall_-_deluxe_edition_content_pack_1.1.0.3_(64bit)_(34231).exe) = 07aa4effab7cea226ba1fc395c35342af41983bb4b2c9d54a95633108eac56cc244f07a39357783293b8862aea9974fe3d2a2fc9aee798556fe0bf7c4fce4dd5`
`SHA3-512 (setup_digital_deluxe_content_1.8.0-629r_(64bit)_(34198).exe) = 2ad844ef7ff1f7825fe6f308dd2e465735c813bf05259a6a2d7ef4e8b3120025dfa56a1cba269292acede37eb9620f4173b78b783799ca4a199a528031115eb8`

**Comment by MachineGunnur** [comment]
Age of Wonders: Planetfall - installer is just an entry. goodies are on site

BATTLETECH - same goodies on site. installer is large. removed. redundant. grab goodies if want "deluxe goods"

**Comment by KottaGotta** [comment]
Sorry then!

Interesting. So the Plantefall's installer has nothing useful and BattleTech's, as understand, installing Goodies (WTF?!), well, yeah, the size is almost equal to ZIP archives, kinda odd, and the Planetfall installer is strangely tiny. OK, no problems. For me they are just files, I am "blind" here, didn't play yet nor install, just keep both, never install everything of no interest if matches the 3rd party checksums. Space is not much of an issue to me. Previous had, literally its previous GG update, that's why I was surprised, the update before Previous had none though.

Also, if the case, why not delete MacOS/Linux files if so much need for space? Should free at least 8 GB or more. Using a Moderm FS with Build In deduplication might help as well, some FS even support compression.

**Comment by MachineGunnur** [comment]
yea, very strange from GOG. why they do this? no idea.

few games have linux/mac goodies, just cba to go through.

**Comment by tomgatos** [comment]
No CBA, one command and done, very easy:
`find -L -type f -regextype posix-egrep -iregex '.*\.(dmg|pkg|sh)$' -execdir rm -f -- '{}' \;`

**Comment by iFreester** [comment]
`find -L /media/$USER/disk/folder -type f -regextype posix-egrep -iregex '.*\.(dmg|pkg|sh|tar\.gz|tgz)$' -execdir rm -f -- '{}' \;`
`

**Comment by iFreester** [comment]
`find -L /media/disk/folder -type f -regextype posix-egrep -iregex '.*\.(dmg|pkg|sh|tar\.gz|tgz)$' -execdir rm -f -- '{}' \;`
