### ISSUE TITLE
Links don't get updated regardless of what the changelog says.

### ISSUE THREAD

**Issue by dreamco3d** [MachineGunnur/GOG-Games#11]
As of now, zippy links don't get updated regardless of whats stated by the changelog. I noticed that in Grim Dawn game. A delay on their end(GOG) or is it a bug?

**Comment by MachineGunnur** [comment]
the CHanglog comes directly from gog api. it will always be update even if game isn't (game files are manually updated if can get/have)

**Comment by dreamco3d** [comment]
So the links uploading is not an automated process? I thought it was...

**Comment by MachineGunnur** [comment]
the UPLOADING is. if game gets UPDATED ON GOG we have to manually GET the new files.
