### ISSUE TITLE
Kingdom Come: Deliverance 1.9.4.404-502 Corruption

### ISSUE THREAD

**Issue by KottaGotta** [MachineGunnur/GOG-Games#110]
Unfortinately some files are corrupt, CRC32 mismatches Connie's and installing fails on check itself (of course): Tested in VirtualBox on Windows 7, the host is CentOS on ZFS, S.M.A.R.T. is OK. Downloaded 2 times, all the time CRC32 of GOG Games RAR is OK actually but the files aren't. Guys on RIN Forum have the same issue with, they said BIN #12 was bad in particular. (BTW, if from P2P, did you check afterwards?). Anyway, Connie has a lot of SHA-1 and always updates each week, usually Sunday, try out, would help... Myself is loading from Torrminatorr now, Mail.ru sucks but no choice.

**Comment by MachineGunnur** [comment]
update pushed for BIN only
