### ISSUE TITLE
add a small .txt or .nfo file with your .onion address to your game archives

### ISSUE THREAD

**Issue by MGFan0815** [MachineGunnur/GOG-Games#113]
Please add a small .txt or .nfo file with your .onion address to your game archives to avoid that the idiots at torrminatorr steal your links. Those fuckers should upload their own stuff!

**Comment by MachineGunnur** [comment]
link to github site maybe? benefits all evern people who have no clue about onions

**Comment by MachineGunnur** [comment]
donee
