### ISSUE TITLE
Replace gogdb.org (abandoned) for gog-db.info (active and updated)

### ISSUE THREAD

**Issue by ownchoice** [MachineGunnur/GOG-Games#116]
**gog-db.info** ([Github repo](https://github.com/tiehichi/gogdb)) is a fork of **gogdb.org** ([Github repo](https://github.com/Yepoleb/gogdb)) that is currently working and it's just a continuation of the latter that hasn't been touched in 8 months and doesn't update the data anymore.

**Comment by DueDuo** [comment]
Rocking the boat? 1) Recent Github updates are not important, a GOGdb is a DB and not a development toy, the Site first IMHO, i.e. INFO didn't update the DB in 2020 (2019-12-24) but ORG does (2020-01-03): As a tool INFO is kinda Slowpoke; 2) For whatever reason INFO lost API and some other links but most strangely a Media page has no YouTube, no Media, worse then ORG; 3) INFO was made recently, ORG is tested by time, thus ORG is far more reliable, for God's sake let's not break what work: No good building can stand on an unstable foundation, GOGdb is a part of GG, shall be stable.

To be honest, the new INFO's interface isn't too bad, Currencies, etc, that's nice, on the other hand who cares how great it looks if not much to look at? I think no reason to change, ORG has more data, faster and stable, maybe when INFO will be more mature, who knows... not for today IMHO. Having a DB lag behind is unacceptable, not to mention ORG is perfectly fine and all on updates in recent months, one can only wonder why recommend a project who can't even do what Original does. What for?

An important thing to remember is that both run by a single person or so, like many lonely projects are. As mentioned, INFO is a fork of ORG, not the other way around. Unfortunately working on something like that isn't that easy as it looks like. I can only hope maybe one day INFO not only will be able to sufficiently handle what ORG has but even outperform. I am not for or against each as per name, judging solo by functionality. Seem to me, adding currencies made overall parsing slower, or some parts were done by hand, in any case no idea why INFO has Zero updates for 2020 when ORG has.

**Comment by ownchoice** [comment]
> Having a DB lag behind is unacceptable, not to mention ORG is perfectly fine and all on updates in recent months, one can only wonder why recommend a project who can't even do what Original does. What for?

I made the suggestion because I have had many cases of gogdb.org being outdated, likes this one:

- The Red Strings Club
- https://www.gogdb.org/product/1209307763 (last updated oct 7, 2018)
- https://www.gog-db.info/product/1209307763/ (last updated today)

**Comment by DueDuo** [comment]
Speaking of, I forgot to mention a critical part for folks who are watching updates: Where on Earth are Builds, Downloads, a game Changelog?! Can't even recognize of it was updated, can't say if the post is right, objectively looks like not, really sorry for being so direct. GOG API for the Red Springs Club does not show updates, no new builds (I repeat, API itself, not a 3rd party DB), even the last build is from 2018. If the source has no updates, my mind is out, too, totally. Will see what @MachineGunnur will say on the subject, I hope, maybe it's me who don't see updates, likely something very unnoticeable.

Let me guess, do you mean prices? I tried dead hard, even read INFO's changelog, however, the main INFO Changelog page, clearly, has no updates for 2020 whatsoever, any product, none today as well, the changelog is useless, even if an item was really updated. The original GOGdb has none (except broken prices) for the mentioned either, as well as GOG. What the update do you mean and why so needed to have it for, at all? Later today or this week I would compare my API backup with the "updated" page by `diff` of the content, if I'm wrong, will say later about.

I appreciate your efforts in Heart, just struggle to see any great improvement over ORG but tonnes of missing functionality. First, as a reason to switch, Github was mentioned, even though GOGdb isn't a Lib, therefore updates of code are no matter, a DB does. Second, the mentioned "update" doesn't show itself on both of them, nor I see a new GOG Build. Third, as an owner of 2,000 games, around 50% of GG, don't give a damn on prices, if anything, always can make an API request or MaGOG but to have a general Changelog up to date and correct is paramount: INFO even doesn't log itself right, sad.
