### ISSUE TITLE
Remove TXT, use RAR Comment or File Title

### ISSUE THREAD

**Issue by ghost** [MachineGunnur/GOG-Games#117]
For the purpose of Credits, RAR offers the comment box: Simple, nicer, doesn't pollute with unnecessary new junk files who could be annoying to delete afterwards and still makes noticeable who's archive is. On the other hand a less intrusive and the Most Visible Solution is to make the GG address be part of the name if wish so. TXT can be skipped, a comment not read, skip a name on the other hand is unreal... What do you think, a deal?

**Comment by AntiKoshchey** [comment]
Not solved!
