### ISSUE TITLE
New Uploads Corrupted

### ISSUE THREAD

**Issue by coreyemtp** [MachineGunnur/GOG-Games#118]
I'm going to keep a running list of all uploads I find that are corrupt. These have been downloaded numerous times with Jdownloader 2, both from multiple sources and from Zippy alone.  Most are not even showing the correct contents or mixed new/old contents.  It seems to have been a new development starting from the day Trine 4 was last updated. Please fix and look at the current uploading process. Someone please independently verify this problem and comment below.

I've added a section of those that are fine since the Trine 4 corruption. Note that I don't download every new release, so if anyone can add to this in the comments below I'll update the list until the problem is officially fixed.

Trine  4
Fictorum
Warhammer 40k Gladius: Relics of War
Tales of Maj'Eyal
Pyre
Tooth & Tail - Not corrupted, but still the old version (1.5.1.0)
Sins of a Solar Empire - Rebellion Ultimate Edition

OK;

Project Hospital
Late Shift

**Comment by your-awesome-ghost** [comment]
May I know without wasting traffic: Game data or an archive? I have some solutions to the problem in mind, one of which will be made as an Issue. Tested it on Ubuntu 18.04 LTS.

**Comment by coreyemtp** [comment]
Archives are corrupt

**Comment by TheNoisyGhost** [comment]
Oh... Understand, Thanks!

**Comment by coreyemtp** [comment]
Add Tales of Maj'Eyal to that list.  I'm using a multi-hoster downloading from different sites through Jdownloader 2, and have tried multiple times with each.  Perhaps you are not uploading the correct files to all hosters?  I did try to download Warhammer 40k from only zippy, and it still was corrupt.

**Comment by TheGhostlyAwesome** [comment]
I ain't afraid of no ghosts, I am a ghost: You asked to independently verify, done.

Autotested 56 latest except greedfall, starpoint_gemini_3, the_surge_2 who are too big to unpack on my UNIX-like 16 GB ECC RAM 100 Mbps PC. Compared every file against Zippy HTML Lists, no mismatches, tested every bit of RAR, no mix/errors for 51 of them! Only bad was deus_ex (Dead Links), others are OK, no expect the 3 be bad, as well.

To the person above, I'm wondering: Have you updated your Browser, JDownloader (beware: Bundleware) or Windows, recently? Is it Windows 10??? Buggy like Hell! You feel yourself, right? I remind reading about the same issue, probably has something to do with your browser cache. You know, one can use no browser and no Bundleware to download.

I suggest to close the issue, it can't be helped. The issue has no do with me, MG or GG whatsoever. I am very sorry for being that direct to the issuer but if you switch your PC, your ISP and your OS, I guarantee, you won't have any problems. Honestly speaking you may try to use Virtualbox or VMware, may help, I don't know why the bug happens.

In the future, take care everyone, & never stick to a single machine before report.
