### ISSUE TITLE
Re-upload button leads to a RAR file with curl debugging info instead of game file

### ISSUE THREAD

**Issue by gogd-helper** [MachineGunnur/GOG-Games#12]
**Describe the bug**
Re-upload button leads to a RAR file with curl debugging info instead of game file

**How to reproduce**
Click on re-upload button on any game older than 30 days

**Expected behavior**
Game file should be re-uploaded, instead a RAR with curl debugging information is uploaded

**Additional information**
Problems have affected the games Close Combat 1-5

**Comment by MachineGunnur** [comment]
think i fixed this .. found myself :)
thank you
