### ISSUE TITLE
Easy GOG Integrity Check on GNU/Linux

### ISSUE THREAD

**Issue by ghost** [MachineGunnur/GOG-Games#120]
My own custom [Script](https://privatebin.net/?8a8772c61157ef11#BhNnhmSmipf2V8UkACaw3T9SMzGDMRQ3BpyNpXarr29A)  ([Download ZIP](https://privatebin.net/?c51adf38ba1f4f2a#7dA5SoycThvb72tUwpwnQETFiheZgE5F1TtaWktvAPNi)) to check a game\* like GOG Setup & Windows does, supports all new releases:
`#!/bin/bash`
`gogsum()`
`{`
`local binargv i chksum chktmp chknum`
`readarray -t binargv < <( ls -v "${dat%%\.exe}"*.bin 2>/dev/null )`
`for i in "${binargv[@]}"; do`
`chksum="$( md5sum "${i}" )"`
`chktmp+=( "${chksum/  *}" )`
`done`
`chksum="$( echo "${chktmp[@]}" )"`
`if [[ "${#binargv[@]}" -le 9 ]]; then`
`chknum="0${#binargv[@]}"`
`else`
`chknum="${#binargv[@]}"`
`fi`
`if [[ "${chknum}" != 00 ]]; then`
`echo "${chksum// }${chknum}"`
`fi`
`}`
`gogsum_c()`
`{`
`local i binnum binsum exe md5gog md5max binargv`
`gogsum_s()`
`{`
`if [[ -z "${dat}" ]]; then`
`exe="${1}"`
`fi`
`if [[ -z "${1}" ]]; then`
`return 1`
`fi`
`i="$(( ${#1} - 2 ))"`
`binnum="${1:$i:2}"`
`binsum="${1%%"${binnum}"}"`
`if [[ "${i:0:1}" = 0 ]]; then`
`binnum="${binnum/0}"`
`fi`
`binnow="$( ls -v "${dat%%\.exe}"*.bin 2>/dev/null | grep -c '^' )"`
`binnum=( $( seq 0 "$(( "${binnum}" - 1 ))" ) )`
`for i in "${binnum[@]}"; do`
`bintmp="${binsum:0:32}"`
`binsum="${binsum/"${binsum:0:32}"}"`
`echo "${bintmp}  ${dat%%\.exe}-$(( "${i}" + 1 )).bin"`
`done`
`}`
`gogsum_r()`
`{`
`if [[ -z "${dat}" ]]; then`
`exe="${1}"`
`fi`
`md5gog="$( tac -- "${dat}" 2>/dev/null | cat -e | grep '#GOGCRCSTRING' )"`
`md5gog="${md5gog/'#GOGCRCSTRING'*}"`
`if [[ "${dat##*\/}" = "setup_batman_the_enemy_within_-_the_telltale_series_episode_5_(19607).exe" ]]; then`
`data=bee5fee915e988ad198eff71db98d35c724b5c5b80b0b45d241cee92fb0d4b8cae5af3da8a31100f66c010b1aba626a50188ae461c0cb07e3bb2d5e90389fb1789433eb7afc4c1c7819f2098e9a3a674aa63e9cd880209bc62a4f4e70477570806`
`elif [[ "${dat##*\/}" = "setup_bloodrayne_2_1.0_(19403).exe" ]]; then`
`data=896d1e41bca56cb9bc9587f151f7572901`
`elif [[ "${dat##*\/}" = "setup_broken_sword_3_-_the_sleeping_dragon_1.0_(19115).exe" ]]; then`
`data=3901d740c9071b43eae5b5e3566ef4c601`
`elif [[ "${dat##*\/}" = "setup_colin2005.exe" ]]; then`
`data=3931964c5eb08e8e09eb22c5860a4f9f9c00ae95ab1ebc512fce9c32b5d7bab402`
`elif [[ "${dat##*\/}" = "setup_expeditions_viking_1.0.7.4_(19111).exe" ]]; then`
`data=1a62dce3a32d0d596bd708a259771a12b2791ee5edaa1c5ed93762d638ddec3902`
`elif [[ "${dat##*\/}" = "setup_little_nightmares_1.0.43.1_(18471).exe" ]]; then`
`data=0732121bf0da7db6dc6f5e5a3bc8705b01`
`elif [[ "${dat##*\/}" = "setup_mafia_iii_1.090.0_(19569).exe" ]]; then`
`data=4754a97cfa22f7a4861961f48896b5f0aa5eaf4aef380c740caa81a78563141c086d4148409c1601387ef28b0935b9746c76acf1fef2943b909829f8785f8634f91d1aec2b776f55c3467305047dd01aa070c7c3fa3a5cdf6f40f02e577ac75fc15aad8d2e8d958c8744107fbc6bc99518de8744ef029e0512ccd06daafd255b3838974cd7f46cd4f400f5f54df509ea862034c31022d7d4908e4902ad6f6bb71af264bc5d0eac6eef59e14f9e9df61c59ccb31ef701f48d772406b7823492139a7e9db959199ef24ae5adef7810ab5213`
`elif [[ "${dat##*\/}" = "setup_mark_of_the_ninja_1.0_(19120).exe" ]]; then`
`data=a6e0f1035d5e2f938b3f9cad9f4f973d01`
`elif [[ "${dat##*\/}" = "setup_sniper_elite_-_berlin_1945_1.0_(19500).exe" ]]; then`
`data=3bcafdcd6d92a3ede2a8c73df72b6c3901`
`elif [[ "${dat##*\/}" = "setup_the_raven_remastered_1.1.0.654_(19262).exe" ]]; then`
`data=d12388215b70f2ccc9b033e8e323d39201d315ba1f8808f7fa2f6210cdb8d17ad361cf5faea20ec79562d1321568e9c603`
`elif [[ "${dat##*\/}" = "setup_the_witness_21-12-2017_(19091).exe" ]]; then`
`data=90a24fed5d8e2e52ab1bf2de8434998401`
`elif [[ "${dat##*\/}" = "setup_toca_3.exe" ]]; then`
`data=4187245c9d32a7ddd930f26fc75dc58d4b3b4235d439a2409dbb108981abc147d6a5a69f5f6a5506adaea2c80835b18303`
`elif [[ "${dat##*\/}" = "setup_ufo_aftermath_1.4_(19448).exe" ]]; then`
`data=53eefd9b1e788cb1fdb068b0f34e911501`
`elif [[ "${dat##*\/}" = "setup_ufo_aftershock_1.2_(19449).exe" ]]; then`
`data=9401fc55950a8b8e5726e669163f765201`
`fi`
`if echo "${md5gog}" | grep '00$' &>/dev/null; then`
`md5gog=""`
`return 1`
`else`
`md5max="$(( "${#md5gog}" - 2 ))"`
`md5num="${md5gog:$md5max:2}"`
`if [[ -z "${md5num}" ]]; then`
`return 0`
`fi`
`md5gog="${md5gog%%"${md5num}"}"`
`md5gog="$( echo "${md5gog}" | rev )"`
`md5max="$(( "${md5num}" * 32 ))"`
`md5gog="$( echo "${md5gog:0:md5max}" | rev )"`
`echo "${md5gog}${md5num}"`
`fi`
`}`
`dat="${1}"`
`if [[ -n "${dat}" ]]; then`
`gtitle="${dat##*\.}"`
`gtitle="${gtitle,,}"`
`if [[ "${gtitle}" = "zip" ]]; then`
`if command -v "unzip" &>/dev/null; then`
`unzip -t "${dat}" &>/dev/null`
`if [[ "${?}" = 0 ]] || [[ "${?}" = 1 ]]; then`
`echo "${dat}: OK"`
`else`
`echo "${dat}: FAILED"`
`fi`
`else`
`echo "${dat}: UNKNOWN"`
`fi`
`elif [[ "${gtitle}" = "exe" ]]; then`
`readarray -t binargv < <( ls -v "${dat%%\.exe}"*.bin 2>/dev/null )`
`if command -v "osslsigncode" &>/dev/null; then`
`if osslsigncode verify "${dat}" &>/dev/null; then`
`echo "${dat}: OK"`
`else`
`echo "${dat}: FAILED"`
`fi`
`else`
`echo "${dat}: UNKNOWN"`
`fi`
`if [[ "$( echo "${dat%%\.exe}"*.bin )" != "${dat%%\.exe}*.bin" ]]; then`
`gogmd5="$( gogsum_r "${dat}" )"`
`if [[ -n "${gogmd5}" ]]; then`
`gogsum_s "${gogmd5}" | md5sum -c`
`else`
`for i in "${binargv[@]}"; do`
`echo "${i}: UNKNOWN"`
`done`
`fi`
`fi`
`else`
`return 1`
`fi`
`fi`
`}`
`gogsum_c "${1}"`

\*Requires to run `apt install -y osslsigncode` 1st (availible for Ubuntu) for EXE, `unzip` for ZIP, `cat` for BIN.

**Comment by YourGhostOne** [comment]
Replace `data=` with `md5gog=` to check few no MD5 EXE (my bad). Plus I missed a rare detail, games with game.exe + game.bin instead of usual game-1.bin won't check. Sorry!

A quickly patched version (+better ZIP checking)—Now supports multiple files—Usage before as `./chkgame example.exe` but now as `./z/chkgame "Example.exe" ../patch_example.exe *.zip`, too: [Download ZIP](https://privatebin.net/?bed36d2c0a2eeb17#6V8ZxFV2qUVRKiLQQAixuhbBVTpFhHSza5HFUJEmf3jG)

Wish you to have a nice day and no corruption issues anymore! ;)

**Comment by TheNoisyGhost** [comment]
@coreyemtp said corrupt RAR. May you close/delete the issue then? Better the 2nd. Finally integrated into GOG Times anyway and made "zip -F" use /dev/null, no ".tmp" files anymore like the quickly patched did. Future updates (if any) are on: https://gitlab.com/mjr-awesome/gog-times/tree/master
