### ISSUE TITLE
link jumbled (in game card pop-up)

### ISSUE THREAD

**Issue by LEADERS22** [MachineGunnur/GOG-Games#13]
Rather than going to the gog store link it comes up as 
http://goggamespc7v6z5e.onion.ws/https://www.gog.com/game/cultist_simulator

![404](https://user-images.githubusercontent.com/51100531/58442696-2b165880-80ed-11e9-8430-1d1f7eb96e18.PNG)

**Comment by LEADERS22** [comment]
refreshed the page after a while and it came back to normal

**Comment by MachineGunnur** [comment]
http://onion.ws/ is a tor proxy and issue can happen on site. best if you use preferred method to get to site in README.md  =) 

i check and everything working on direct tor site.

**Comment by MachineGunnur** [comment]
cant fix, just how tor proxy site works . closing
