### ISSUE TITLE
Some multiup links are missing

### ISSUE THREAD

**Issue by reyqn** [MachineGunnur/GOG-Games#130]
For example, part 27 of dishonored definitive edition.

I don't really know if this is the place to report this type of issue, but I thought it was strange that the multiup link for part 27 didn't even exist.

**Comment by Pladdium** [comment]
samething on dishonored 2. Some items missing and download speed too low :/

**Comment by MachineGunnur** [comment]
are ZS links there for missing parts? use proxy to grab them if so.

**Comment by reyqn** [comment]
ZS links are mostly dead though. I thought multiup was there in case ZS links are flagged, but if they are missing too, the games can't be downloaded. Wouldn't it be useful to diagnose why the multiup links don't exist at all?
