### ISSUE TITLE
Game Kerbal Space Program - Expansion not possible to install

### ISSUE THREAD

**Issue by cendarlerouge** [MachineGunnur/GOG-Games#133]
Hi!

First I want to thank you for all the work you put in your website.

I have a problem with the last Kerbal update.
The game is in version 1.9.0.02781f2_(64bit)_(36208)
The expansion Breaking Ground is version 1.9.0.02781_(64bit)_(36046)

And the installer tell me that I can't install Breaking Ground because it is not the same version as the game installed.

I don't know if you can do something about it, but I wanted to point it out. If you can update the Breaking Ground install to match the game version, it would be awesome.

Thanks again!

Cendar

![2020-02-28 16_52_26-Window](https://user-images.githubusercontent.com/16260463/75563519-c5277a80-5a4a-11ea-807e-e958b9263ba6.png)

**Comment by MachineGunnur** [comment]
yea, dlc outdated. new one is queued. check in ~hour.
