### ISSUE TITLE
Alternate way to donate?

### ISSUE THREAD

**Issue by specterlich** [MachineGunnur/GOG-Games#135]
I don't have bitcoin or a btc wallet but i considered buying some to donate to you. I tried signing up at Coinbase, but it was asking for my ID card/driver's license and a photo of myself among other things. I realize that there is no other way to get a wallet, but this is just way too invasive for me. Buying bitcoin from other people seems super sketchy as well.

Any chance for an alternate way of donating, like paypal? Please?

**Comment by MachineGunnur** [comment]
paypal is not anonymous. only take bitcoin currently, sorry!!! :(
