### ISSUE TITLE
Disco Elysium is still using previous update files, not new update.

### ISSUE THREAD

**Issue by blackroseMD1** [MachineGunnur/GOG-Games#136]
I noticed after downloading that the files for Disco Elysium are still from the January update (5bad0c96) despite the changelog showing the February update (579003ab) and the game showing as having been updated 22 hours ago (as of the time of this post).

I just wanted to point this out so that others may not waste bandwidth downloading files that they already have. Thanks!

**Comment by MachineGunnur** [comment]
added goodies why updated. not game
