### ISSUE TITLE
Missing DLC / Extras

### ISSUE THREAD

**Issue by coreyemtp** [MachineGunnur/GOG-Games#137]
It seems lately that updated games are missing DLCs or other add-ons. Examples are Earthlock (Comic Book), Warhammer 40k: Gladius - Relics of War (All DLC except Tyranids), Warhammer 40k: Mechanicus (Heretek, Heretek+, Arc Scourge Weapon), etc.

Also, can I suggest adding a forum or some means other than GitHub to leave feedback?

**Comment by MachineGunnur** [comment]
dont have dlc
