### ISSUE TITLE
UploadHaven Feedback

### ISSUE THREAD

**Issue by MachineGunnur** [MachineGunnur/GOG-Games#139]

**Comment by coreyemtp** [comment]
Unfortunately, Alldebrid doesn't support UploadHaven, unlike MultiUp.  So, for us Alldebrid users it's vastly inferior.

**Comment by MachineGunnur** [comment]
this is no premium host. use jdownloader 2 and enjoy ^_^

**Comment by chrisryan63** [comment]
Unfortunately it's very slow compared to Multiup. Multiup maxes out my connection with Jdownloader and hosters like Uploaded, 1fichier etc. Not getting anthing near with Uploadhaven

**Comment by bokugaoyori** [comment]
I support Uploadhaven, it is much easier to automate than Multiup, through custom scripting. Multipup pretty much requires a paid debrid account and zippyshare's abhorrent 30 days policy often leaves many dead links. +1 for Uploadhaven from me. It is superb!

On a side note, MachineGunner, can you check and see if it is possible to add a vote for re-upload buttons on all the existing games, I have often came across several titles with dead links but no vote for re-upload.

**Comment by chrisryan63** [comment]
That's fine if it works for you and you don't like to pay, a lot of us have paid debrid accounts. I don't care how easy it is to automate, I'd rather have faster download speeds any day of the week. Uploadhaven is a big thumbs down as it's way to slow, it took over 3 hours to download a 26gig file and I have a 500meg connection. Compare that to Multiup which takes around 30 minutes for the same size file.

I'm sorry but free is not always the best way to go, sometimes you have to pay if you want the best way of downloading things.

**Comment by bokugaoyori** [comment]
Maybe if possible, MachineGunner could keep 3 separate links? Zippy, Uploadhaven and Multi. I have a 1 Gbps uncapped internet and Uploadhaven is working like a charm and thanks to the easy automation possibilities, I can easily start multiple parts simultaneously like in zippy. 

@chrisryan63 you might wanna ask your debrid provider to add support for Uploadhaven. They basically just have 4 pair of data in the original HTML and does a 5 second counter on client side and posts this 4 data pair as Form Data to the server, which in turn returns a new HTML containing the direct download URL. I would've shared the script here but it is deeply integrated with my automation system so it would need a lot of cleaning to work independently. 

And we are all here to grab games for "free" so the whole philosophy of paying to get "free" games is kinda silly. 

Regardless, Uploadhaven is +1 from me and my thanks to MachineGunner for adding support to this awesome host.

**Comment by chrisryan63** [comment]
We all have to pay for something, it can't be freeloading for everything if that's your philosophy on life. I don't mind paying for good service. What may work for you may not work for others.

Anyway many thanks to MachineGunner and all his efforts

**Comment by bokugaoyori** [comment]
I didn't really meant it like that. What I wanted to say is that if I wanted to pay, I would much rather buy the games off GOG/Steam and support the developers instead of paying third party tools that profit off "streamlining" popular file hosts for warez. Regardless, I am not here to moral policing and I digressed, for which I apologize.

**Comment by chrisryan63** [comment]
No problem..all the best

**Comment by 8086K** [comment]
Hi MachineGunnur you are the best, yours site it's my favourite, for last try UploadHaven was good, normally I use alldebrid with Multyupload link, but my Internet connection it's not fast, for me is the same, for me the most important thing is the Healt of all links.
Offtopic: can you reupload the file 27 of Dishonored - Definitive Edition, the zippyshare link it's die and the multyupload link was totally missing, was not uploaded :)
Thanks for all and best Regards

**Comment by MachineGunnur** [comment]
@8086K new links are there

**Comment by 8086K** [comment]
Respect, My Fella 😆

**Comment by chotnik** [comment]
UploadHaven automaticaly trims all `_` in filename on download request.
When you upload `xxx_yyy_zzz.rar` is becomes `xxxyyyzzz.rar` when you try do download it.
Problem with this is you cannot then use those rar parts interchagably with Zippyshare (as naming is different) without manual renaming all parts after download to common format.

**Comment by DanielDuesentrieb257** [comment]
pls switch back to multiupDOTorg or try letsuploadDOTco (even 1fichier would be better as this horrible uploadhell)

**Comment by MachineGunnur** [comment]
uploadhaven lets uploads come through yet downloads are 0 bytes. back to mulitup now... may try letsupload

**Comment by Jamesstevens-3rd** [comment]
> 
> 
> uploadhaven lets uploads come through yet downloads are 0 bytes. back to mulitup now... may try letsupload

links do not resolve anymore and seem to be a hash number? and uploadhaven url reports  500 | Server Error
