### ISSUE TITLE
tor2web bug

### ISSUE THREAD

**Issue by revertinglife** [MachineGunnur/GOG-Games#14]
**Describe the bug**
404 on clicking the link to download

**How to reproduce**
https://gyazo.com/62d3a00ae1e0d5c3d44dcbf66f6648d5
**Expected behavior**
You get a zippyshare link
**Screenshots**
see above

**Additional information**
You can remove the onion.ws link and make it only the zippy share link to get the link, see here 
https://gyazo.com/b340ab1419f9edd48f925cc563f3b0aa

**Comment by MachineGunnur** [comment]
cant fix these bugs just how tor2web site work. but if you have jdownloader2 up and click COPY LINKS button jdownloader2 will get all link loaded for you ;)
