### ISSUE TITLE
Some links not working

### ISSUE THREAD

**Issue by metablaster** [MachineGunnur/GOG-Games#147]
Hello,
2 games: Age of wonders 3 and Age of wonders 3 Planetfall,
not all zipyshare links are reachable.

I was able to download some parts of the zipped files, but others never load.

btw. thank you for such a good site!

**Comment by Sibbs** [comment]
same with neverwinter nights enhanced edition, parts 1,6, & 7 zippy never load, and uploadhaven doesnt work at all, it always downloads 0kb rar files

**Comment by Meat-bag** [comment]
Low Magic Age links are having the same issue too. zippyshare doesn't load and uploadhaven is 0kb.

**Comment by dhaos21** [comment]
both Dying light and trails of cold steel 3 links also not working

**Comment by MachineGunnur** [comment]
> 
> 
> Hello,
> 2 games: Age of wonders 3 and Age of wonders 3 Planetfall,
> not all zipyshare links are reachable.
> 
> I was able to download some parts of the zipped files, but others never load.
> 
> btw. thank you for such a good site!

links are fine.. tested.



> neverwinter

all there to....

> 
> 
> Low Magic Age links are having the same issue too. zippyshare doesn't load and uploadhaven is 0kb.

again test it fine also... 

> both Dying light and trails of cold steel 3 links also not working

fine here.... i dont know why you all have issues GEO BLOCK possible?

**Comment by dhaos21** [comment]
Yeah i did more testing about 10 mins ago, i think it is down to GEO block, im in the UK, i used a VPN to Amsterdam still wouldnt work, i ended up VPNing to Austria, works fine now and also downloading via J2 at my max speed.

**Comment by Meat-bag** [comment]
Uploadhaven link for Low Magic Age is still downloading as a 0 byte .rar, however zippyshare link is working fine this time. Not sure what was going on, sorry for the confusion.

**Comment by MachineGunnur** [comment]
> Uploadhaven link for Low Magic Age is still downloading as a 0 byte .rar, however zippyshare link is working fine this time. Not sure what was going on, sorry for the confusion.

sorry i see, UH is downloading 0 byte here to. my guess? they ran out of space on server? switching back to mulitupload.

**Comment by Sibbs** [comment]
im in the US, zippy isnt blocked here, also if i was none of the links would load, i just tried neverwinters zippy links, they all work now, but uploadhaven still downloads 0kb files

**Comment by Jamesstevens-3rd** [comment]
Uploadhaven is working again

I can confirm that zippy is geo blocked in the UK (reported by JDownloader), browser reports 403 Forbidden
