### ISSUE TITLE
Re-upload request not available for games without date

### ISSUE THREAD

**Issue by kevinj93** [MachineGunnur/GOG-Games#148]
It is not possible for some older games that have dead links to request a re-upload.

**Comment by MachineGunnur** [comment]
30 days have not passed since that game was last uploaded. give name of the game and i can override this one time

**Comment by kevinj93** [comment]
Looks like you were right about the last upload date, but The Witcher 3 has
most of its links dead for a strange reason. (Zippyshare links, UploadHaven
is slower compared to ZS)
Much appreciated for the fast reply.

**Comment by MachineGunnur** [comment]
DMCA bots.. will be up for a few days before it gets down again probably..
