### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by quiapho** [MachineGunnur/GOG-Games#15]
Hi! How to contact without an Issue? Is it possible to add Discord for Chat or something alike?

**Comment by MachineGunnur** [comment]
hello, what is you like to talk about? send pm to me on reddit https://www.reddit.com/user/MachineGunnur1965 and i will provide private line of communication. thanks,

**Comment by quiapho** [comment]
Thanks! Reddit is a very good choice, now I see the acc is official. I've https://www.reddit.com/user/quiapho and it's several topics to talk about but not in public.

**Comment by MachineGunnur** [comment]
i seen the message,, sorry been busy i'll send you my tox id in next days. been busy finishing some other projekts up :)

**Comment by quiapho** [comment]
Don't worry! Not an emergency. Tox as fine as Jami or even Briar. Work on projects,  it is OK. Let's continue on Tox. ;)

**Comment by quiapho** [comment]
OK. Understand. I've sent mine already. Please send the ID on Reddit, too.
