### ISSUE TITLE
[IDEA/NOT A BUG] Encrypted file names for rar files

### ISSUE THREAD

**Issue by kevinj93** [MachineGunnur/GOG-Games#151]
In order to keep the links alive longer/ avoid DMCA takedown, Some of the other sites use encrypted file names for their rar files. That makes it undetectable, thus making the links stay alive for longer and thereby minimizing the chance of having to re-upload the files and overloading the server with upload requests.

**Comment by MachineGunnur** [comment]
most DMCA is automated and no check is done to prevent abuse (on zippyshare at least). may implement some captcha in future were have to complete to view download links. the MFM links should stay up longer as harder to DMCA at reading their site.
