### ISSUE TITLE
No Separate Patch/Update Downloads for Certain Games

### ISSUE THREAD

**Issue by Lynkzz** [MachineGunnur/GOG-Games#152]
IDK if this is intentional or fixable but I have noticed that for some games when there is an update the 'Game Items' will update with the full game on the latest patch but there is no 'Patch/Other Items' section where one can download just the patch instead of the full game.

An example of this is X4: Foundations. When the major update 3.0 released only the full game 3,0 files were available, then two days after a hotfix was released and only the full game with the hotfix was available, and now version 3.10 is available and again only the full game 3.10 download is available. 

This leads to a situation wherein for some games one is unable to update unless they are wiling to redownload and reinstall the whole thing.

**Comment by MachineGunnur** [comment]
person giving update games DOES NOT supply patches. sad but their choice. don't own.
