### ISSUE TITLE
Divinity: Original Sin - Enhanced Edition .EXE Install not present

### ISSUE THREAD

**Issue by 8086K** [MachineGunnur/GOG-Games#155]
Hi MachineGunnur, everythig good I hope :)
Yesterday I was download Divinity: Original Sin - Enhanced Edition, but when I was extract the release, Opps surprise, the .exe file for install it is not present, only .bin files, please can you re-upload?
And I saw you Uploaded The Evil whiting 2 AMAZING THANKS, but so what do you think about to upload The Evil within 1 with all Dlc?
Thank for your hard work, have a nice day

**Comment by MachineGunnur** [comment]
its there.

**Comment by 8086K** [comment]
Thanks you very much for The Evil Within, but for Divinity? I need to try ro redownload? Is it a problem of download corruption?
Best Regards

**Comment by MachineGunnur** [comment]
i download all 21 parts form zippy and extracted. fine here.

**Comment by 8086K** [comment]
Ok, later a try again,finger cross
