### ISSUE TITLE
Vote reupload

### ISSUE THREAD

**Issue by dhaos21** [MachineGunnur/GOG-Games#157]
Is it still 30 days for a reupload? seeing releases that have been updated longer than 30 days ago and no option to vote.

**Comment by MachineGunnur** [comment]
working.

**Comment by Anyfurry** [comment]
I see you were confused in April as I am in September. Take a look at [this issue](https://github.com/MachineGunnur/GOG-Games/issues/219), @dhaos21, maybe have a say.
