### ISSUE TITLE
Witcher 3 multi-link error message in JDownloader

### ISSUE THREAD

**Issue by Jamesstevens-3rd** [MachineGunnur/GOG-Games#158]
I have this error in JDownloader2 (fully updated) for The Witcher 3 & Goodies when I try to add-all-links to clipboard.
(workaround) I can click each links individually and it takes me to the files uploaded on multiup and from there I can click download for each one (takes a bit of time) most are broken/deleted and file 14 has only 1 source so this release really need reuploading.

`Plugin Defect!game-the witcher 3 wild hunt game of the year edition game`

**Comment by MachineGunnur** [comment]
cloudflare is now using hCaptcha. mulitup uses cloudflare. update jdownloader again. work here now. game is uploaded again though.
