### ISSUE TITLE
DUNGEON SIEGE 3 - IS BROKEN - UPDATE IT!

### ISSUE THREAD

**Issue by SilentMRG** [MachineGunnur/GOG-Games#161]
Please, acording this: https://www.gog.com/forum/dungeon_siege_series/dlc_dungeon_siege_iii_doesnt_work/page1

The .exes files are broken both game and DLC. 

Here more information: https://www.gog.com/forum/dungeon_siege_series/dungeon_siege_3_freezes

Aparently, the .exes fixed after by GOG, but, in your site, the .exes still broken.

Thanks very much!

**Comment by deadair3210** [comment]
yelling at someone to update something tends to not end well....

**Comment by SilentMRG** [comment]
> yelling at someone to update something tends to not end well....

I wrote in "Caps Lock" and used the dot "!", to highlight the title and state a problem. You should have looked at the body of the message, you probably haven't read it. I have great respect for the developers of the old site and the new one!

**Comment by deadair3210** [comment]
I read the body, most people don't though. Most people will see a title like that and immediately ignore or close it because it looks like you are demanding someone to fix it

**Comment by deadair3210** [comment]
Wasn't meaning to be harsh, just a warning lol

**Comment by SilentMRG** [comment]
> I read the body, most people don't though. Most people will see a title like that and immediately ignore or close it because it looks like you are demanding someone to fix it

It depends on the point of view of each one. In many forums in which I participated, "Caps Lock" was required in the titles, and this became a habit for me, within what I already mentioned. Now, who am I to demand something? I am nobody. I was only kind enough to report the error before the developers had a "headache" with other users. It may even seem like an exaggeration ... But a broken game can lead them (developers) to lose donors! And this is something I don't want to happen to them, because their work is top notch!

**Comment by SilentMRG** [comment]
> Wasn't meaning to be harsh, just a warning lol

No problem ... Rest assured ... I understand your warning. =)

**Comment by MachineGunnur** [comment]
fixed
