### ISSUE TITLE
UI Enhancement Suggestion: Popular Downloads

### ISSUE THREAD

**Issue by KWottrich** [MachineGunnur/GOG-Games#163]
Currently, you can view games on the site in the following categories:
- New Releases
- Recently Updated
- Alphabetically
- By Date

It would be great to also have a Popular sort option, where sort order is based on the number of clicks on a given game's Download button.  While this would be imperfect because you can't actually know if a user downloaded the files or not, it would be sufficient to roughly determine popularity.

Each game could track "Download" clicks per day, which could be stored in the SQL database for a set period (e.g. 7 days).  Then the "Popular" sorting would show the top _n_ games sorted by the sum of their Download clicks over the set period.  The lookup would be a relatively expensive DB query, but the result could be cached for 5 minutes or so to help with that.  Data older than the set period could be deleted from the DB using a daily cron command.

**Comment by MachineGunnur** [comment]
why not just use gog.com and see whats popular then come to the site?
