### ISSUE TITLE
"GOG Games Search" in Tor Browser's Search Bar fails

### ISSUE THREAD

**Issue by quiapho** [MachineGunnur/GOG-Games#17]
**Describe the bug**
If add a custom engine into Tor Browser, does not work, uses an old domain

**How to reproduce**
1. Open Tor Browser (v.8.5)
2. Open Browser's Menu
3. Add "Search" via "Customize..." to Toolbar
4. "Done" the Menu
5. Go to the GOG Games Site
6. Click the Browser's Green Plus Sign
7. Click "Add 'GOG Games Search'"
8. Try a Search Query: For example, "Games"

**Expected behavior**
"Add 'GOG Games Search'" allows to search on the web site without an error

**Additional information**
Tor Browser takes an engine from [opensearch.xml](https://github.com/MachineGunnur/GOG-Games/blob/master/web/opensearch.xml), its domain is not in sync

**Comment by MachineGunnur** [comment]
fix https://github.com/MachineGunnur/GOG-Games/commit/ed38c859526b06eccf494204c8fa8c38cd250e51
make sure remove and re-add works then

**Comment by quiapho** [comment]
Thank you!
Now searching performs perfectly good.
