### ISSUE TITLE
Outdated Version For Terraria

### ISSUE THREAD

**Issue by EternalEclipse-Git** [MachineGunnur/GOG-Games#170]
Hello, Sorry for posting something that isnt an issue with the website for any glitches or messed up codes but I didnt know how to directly reach you guys so I decided to use GitHub. I wanted to let the GOG-games team that Terraria is Outdated as current there are 2 small / minor updates for 1.4 which is 1.4.0.1 and 1.4.0.1, I would appreciate if you can update Terraria as soon as possible. I love your website and you guys are doing an awesome job, keep up the good work! :)

**Comment by MachineGunnur** [comment]
yes will update next

**Comment by nous3r** [comment]
Hi, sorry if this is not the right place but there was another update today and i am unable to play with my friends, i tried to create my own version of gog but i am having some problems(the onion link nots work but the docker-compose up ok, but here is not the right place for that), so if possible i would be very grateful if you updated, thanks.
