### ISSUE TITLE
More corrections

### ISSUE THREAD

**Issue by rasay1** [MachineGunnur/GOG-Games#172]
Apsulov: End of Gods - Wrong background image, also check the other pictures/icons

Asura: Vengeance Edition - Wrong background image

Blackwood Crossing - Corrupt picture/icon on site

Blacksad: Under the Skin - Wrong background image, it is slightly changed

The Black Mirror 1 - Changed title - The Black Mirror ⇒ Black Mirror 1

**Comment by MachineGunnur** [comment]
very minor, tho fix later.

**Comment by rasay1** [comment]
Can you cancel this? I will make a complete instead when I am finished.

**Comment by MachineGunnur** [comment]
dont spent to much time. pain to keep up with all gog changes make :)
