### ISSUE TITLE
Not able to extract downloaded archives

### ISSUE THREAD

**Issue by Ajatasatru** [MachineGunnur/GOG-Games#173]
Hi, 
Upon trying to extract some of the recent downloaded .RAR files, it says can't open as archive.
 I am pretty new to this thus, it would be very helpful if you could guide me.

**Comment by MachineGunnur** [comment]
https://duckduckgo.com/?q=how+to+extract+to+.rar+file&ia=web

**Comment by Ajatasatru** [comment]
Thanks for the link, but I know how to extract .RAR files. But for particularly the two games I downloaded; Bad North and In Other Waters, both seem to be showing the same error. I don't have any issue in extracting other .RAR files, therefore I dont think it's an issue particular to my system. Thanks for the help.
![Annotation Error](https://user-images.githubusercontent.com/13168679/83175147-16720380-a139-11ea-86fd-032e139cdc9b.jpg)
