### ISSUE TITLE
Previously available Master of Magic: Caster of Magic DLC no longer available

### ISSUE THREAD

**Issue by Kharhazarad** [MachineGunnur/GOG-Games#175]
As of April, the separate setup for the new Caster of Magic DLC for Master of Magic was available on GOG-Games, so I'm confident it's part of your library. It hasn't been the included after the last two updates which have included only the base game. The plain Master of Magic setup has CoM in the name, suggesting it's included, but the launcher has a "Buy Now" link over the option to launch Caster of Magic.

https://www.gogdb.org/product/1539536778#downloads

**Comment by MachineGunnur** [comment]
dont own DLC.
