### ISSUE TITLE
Many DLCs are missing from many games

### ISSUE THREAD

**Issue by extesy** [MachineGunnur/GOG-Games#177]
Games with missing DLCs (just the ones I've checked):

* Stellaris
* Project Hospital
* Warhammer 40000 Gladius
* AI War 2

I think it's a common issue so I didn't check too many games, only the recently updated ones. Also Prison Architect has two different builds at the same time. So overall the problem seems to be with a script that maintains the current database.

**Comment by coreyemtp** [comment]
Just wait, they eventually are added. Sometimes some parts of the game are released before others.

**Comment by extesy** [comment]
Nope, those are old games. In some of the previous versions those DLCs were there but now some are missing. Not all DLCs, just some of them.

**Comment by askvittorio** [comment]
I agree with extesy. In case of Stellaris all DLCs are updated in the same time as the main game. Recently they are missing from listing.
Issue mentioned here: https://github.com/MachineGunnur/GOG-Games/issues/176

**Comment by extesy** [comment]
@MachineGunnur Can you take a look please?

**Comment by MachineGunnur** [comment]
i have said MANY times. updates are done manually. it is a matter of human error or dont have DLC owned, or its not sh ared.

dont have a gog account that has everything owned so cant do anything ^^

**Comment by extesy** [comment]
@MachineGunnur Why are you doing this manually? I use a variation of https://github.com/gatl/gogrepoc script to automatically update my own backup of my personal GOG collection. You can schedule this script to run every few hours and download all updates for you.

**Comment by MachineGunnur** [comment]
> 
> 
> @MachineGunnur Why are you doing this manually? I use a variation of https://github.com/gatl/gogrepoc script to automatically update my own backup of my personal GOG collection. You can schedule this script to run every few hours and download all updates for you.

**dont have a gog account that has everything owned so cant do anything ^^**
**dont have a gog account that has everything owned so cant do anything ^^**
**dont have a gog account that has everything owned so cant do anything ^^**
**dont have a gog account that has everything owned so cant do anything ^^**

**Comment by extesy** [comment]
I know, but it will work for games that you already own. And it will not miss any DLCs because of human factor.

**Comment by extesy** [comment]
The missed DLCs in the list were all uploaded before, for previous versions. So it's not like your GOG account suddenly lost access to those DLCs.

**Comment by deadair3210** [comment]
Maybe they were donated by someone else? Not everything is the result of ignorance you know

**Comment by extesy** [comment]
@deadair3210 I have never mentioned ignorance, please don't put your words in my mouth. @MachineGunnur mentioned human error in https://github.com/MachineGunnur/GOG-Games/issues/177#issuecomment-637017812. Automation scripts are supposed to eliminate human errors. Do you disagree?

**Comment by coreyemtp** [comment]
I understand they're (sometimes) old games, but for whatever reason when they're updated sometimes not all DLCs are included in the update. I brought up this same issue in the past. However, eventually they do find their way in another update, usually in the "patches" section.

**Comment by Anyfurry** [comment]
After a few months, well, turns out MachineGunnur was and is [not interested](https://archive.is/fk0Bh#issuecomment-685921847) in that, quote:
> have more pressing issues than making sure pirates/collectors/gamers have lastest and greatest games and dlc for free.

An account or a human error is an excuse, one of many, the real reason is above. The GOG Games owner doesn't care about both full and freshness, they don't care if a DLC is missing or not, don't want to give latest and greatest games for people who donate.

**Comment by Masamune3210** [comment]
Dude, if you don't like it, either fork it and do it better yourself, don't donate, or just get the games somewhere else. They don't have drm, so its literally as easy as finding someone to give you the file or buying it yourself. Endlessly whining does literally nothing other than make people eventually get fed up and close it down completely
