### ISSUE TITLE
Many outdated games (not only "classic" ones)

### ISSUE THREAD

**Issue by shakeyourbunny** [MachineGunnur/GOG-Games#178]
There are many outdated games for download, which do have GOG updates. The first version is the version on GOG-Games, the second one is the latest.

- BioShock Remastered 1+2
- Agarest Generations of War 2: 2.0.0.1 -- 2.1.0_(20458)
- Age of Wonders: 2.0.0.13 -- 1.36.0053_(22161)
- Age of Wonders 2 - The Wizard's Throne: 2.0.0.6 -- 1.20.0.3100_(22162)
- Alone in the Dark 1: 1.0_(24275) -- 1.0_cs_(28043)
- Alone in the Dark 2: 1.0_(24275) -- 1.0_cs_(28191)
- Alone in the Dark 3: 1.0_(24276) -- 1.0_cs_(28191)
- Anachronox: 2.0.0.28: -- 1.02_(22258)
- Battle Chess: 2.1.0.26: -- 1.0_(28043)
- Castles: 2.1.0.26: -- 1.0_(280430)
- Cook, Serve, Delecious 2:  2.6.000m1.1_(27644) -- 2.6.000m1.1_(27724)
- Dark Quest 2: 0.1.0_36278 -- 1.0.0_36776 [no changelog]
- Darkest Hour a Hearts of Iron game: 2.0.0.2 -- 1.05.1_(31339) [big patch]
- Detective Gallo: 1.21_(29072) -- 1.21_(29213)
- Dungeon Keeper 2: 2.0.0.32 -- 1.7_(22280)
- Elder Scrolls IV: 1.2.0416_cs_(12732) -- 1.2.0.416_cs_(12788)
- Eschalon Book 1: 2.0.0.4 -- 1.06_(18470) [no changelog]
- Freedom Force vs the 3rd Reich: 2.1.06 -- 1.0_(22094)
- Gateway to the Savage Frontier: 2.0.0.3 -- 1.2_(28044)
- Homeworld Emergence: 1.01_(12687) -- 1.01_(12948) [hotfix patch]
- Independence War 2: 2.1.09 -- f14.6_(22136)
- Journeyman Project 2: 2.0.0.11 -- 1.0_(22114)
- Kholat: 2.1.0.3 -- 1.03_(22352)

Dunno, but I have two things to add:
- don't rely on the changelog for updating games, you should parse the build number (the number in brackets for in the filename) for changes. This is obvious in cases like Elder Scrolls IV, where an update was published, but without a changelog to reflect it.
- It seems that you don't have access to the older games, they all seem have to have the AlVro versions of the games at best (which are now stone cold-old and VERY outdated)... It is true that they don't change much, but for completeness sake' they also should be updated if there are some.

**Comment by shakeyourbunny** [comment]
A have a whole batch of other games in downloading, but it also seems that at least the Tomb Raider games, M.A.X., Moto Racer 2, Nosferatu, the Ultima games, the Total Annilihation games and Total Overdose also may be outdated and not have been updated properly.

**Comment by shakeyourbunny** [comment]
Massive Chalice is outdated.

**Comment by shakeyourbunny** [comment]
Pathologic Classic HD: 1.0.3_(2795) -- 1.0.3_(16813)

**Comment by shakeyourbunny** [comment]
Rad Rodgers World One: 1.1.4480_(18638) -- 1.5.2_(27873)

**Comment by shakeyourbunny** [comment]
Sine Mora EX: 1.0_(14058) -- 1.0.1_(14266)

**Comment by shakeyourbunny** [comment]
Slain Back from Hell: (5487) -- (16908)

**Comment by MachineGunnur** [comment]
all i can do is try to find. no promise

**Comment by shakeyourbunny** [comment]
Tomb Raider 2: 20180103_(17606) -- 20180108_(17720)
Tomb Raider Chronicles: 20170908_(14793) -- 20171024_(15901)
Tomb Raider - The Angel of Darkness: 2.0.0.14 (~2013) -- 20171016_(15707)
Total Annilihation Commander Pack: 2.0.0.21 -- 3.1_(22139)
Total Overdose: 2.0.0.2 -- 1.00_(18925)
Treasure Adventure Game: 2.1.0.5 -- 1.0_(22308)
Ultima 1: 1.0_(22309) -- 1.0_cs_(28189)
Ultima 2: 1.0_(22309) -- 1.0_cs_(28045)
Ultima 3: 1.0_(22309) -- 1.0_cs_(28045)
Ultima Underworld 1: 1.0_(22310) -- 1.0_cs_(28190)
Ultima Underworld 2: 1.0_(22309) -- 1.0_cs_(28190)
Unrest: 2.0.0.1 -- 1.0.0.1_(22308)

**Comment by shakeyourbunny** [comment]
Is no problem .D

**Comment by extesy** [comment]
@MachineGunnur Do you need help with adopting a script like https://github.com/gatl/gogrepoc to automatically download updates for all games?

**Comment by shakeyourbunny** [comment]
Well, just run lgogdownloader or gogrepoc instead of doing your own download scraper ;D

Pronto, the updates should be pouring in.

**Comment by MachineGunnur** [comment]
i got most found i blieve... rest soon

**Comment by shakeyourbunny** [comment]
Well... you could have asked me, I have all the newer updates here in my archive (legally bought all) ;D
 So..

**Comment by RickyVanz** [comment]
is there any way i could request for updating certain games? would like to request updating Terraria to 1.4.0.5

**Comment by MachineGunnur** [comment]
> is there any way i could request for updating certain games? would like to request updating Terraria to 1.4.0.5

just open own issue next time and will see

**Comment by RickyVanz** [comment]
got it.
