### ISSUE TITLE
Linux installers?

### ISSUE THREAD

**Issue by MegaArthur** [MachineGunnur/GOG-Games#18]
Hey, is it possible to get Linux game installers on the site?

Thanks!

**Comment by MachineGunnur** [comment]
requires database restructure and a overhaul of uploading scripts. 
also limit of space on rented server where games are archived. also bandwidth limit too. more games = more $$$ monthly :(
no for now but keep issue open so others see this.

**Comment by awsms** [comment]
Lol I was going to ask the exact same question.
If you change your mind a day, it would be very very very cool!

**Comment by static77** [comment]
GOG games linux installers you can find at torrminatorr forum

**Comment by awsms** [comment]
> GOG games linux installers you can find at torrminatorr forum

also on rutracker, but I don't really trust these websites since there is now way to know if the installer is the original sh or if the guy added some scripts in the middle of it

**Comment by Lustyn** [comment]
Any plans to add Linux (and Mac?) installers now that you've switched over to Drive?

**Comment by MachineGunnur** [comment]
No, rented server has a monthly limit it can upload
