### ISSUE TITLE
Fixes list 1

### ISSUE THREAD

**Issue by rasay1** [MachineGunnur/GOG-Games#180]
Too much work to make a complete list right now, but here you have some fixes you can make.

Changed title - The Black Mirror ⇒ Black Mirror 1

Changed title - Dark Queen of Krynn, The ⇒ The Dark Queen of Krynn

Changed title - Shivah, The ⇒ The Shivah

Changed title - Masterplan, The ⇒ The Masterplan

Changed title - Westport Independent, The ⇒ The Westport Independent

Changed title - Feeble Files, The ⇒ The Feeble Files

Changed title - Last Express, The ⇒ The Last Express

Changed title - Ballads of Reemus, The: When The Bed Bites ⇒ The Ballads of Reemus: When The Bed Bites

Changed title - Elder Scrolls: Arena, The ⇒ The Elder Scrolls: Arena

Changed title - Manhole: Masterpiece Edition, The ⇒ The Manhole: Masterpiece Edition

Changed title - Lords of Midnight, The ⇒ The Lords of Midnight

Changed title - Marvellous Miss Take, The ⇒ The Marvellous Miss Take

Changed title - Wolf Among Us, The ⇒ The Wolf Among Us

Changed title - Elder Scrolls Adventures: Redguard, The ⇒ The Elder Scrolls Adventures: Redguard

Changed title - Settlers® 4: Gold Edition, The ⇒ The Settlers® 4: Gold Edition

Changed title - Journeyman Project 1: Pegasus Prime, The ⇒ The Journeyman Project 1: Pegasus Prime

Changed title - Elder Scrolls: Chapter II - Daggerfall, The ⇒ The Elder Scrolls: Chapter II - Daggerfall

Changed title - Journeyman Project 2: Buried in Time, The ⇒ The Journeyman Project 2: Buried in Time

Changed title - Last Tinker™: City of Colors, The ⇒ The Last Tinker™: City of Colors

Changed title - Night of the Rabbit, The ⇒ The Night of the Rabbit

Changed title - Aquatic Adventure of the Last Human, The ⇒ The Aquatic Adventure of the Last Human

Changed title - Ball, The ⇒ The Ball
New Installer? - The Ball

Apsulov: End of Gods - Wrong background image and logo on site

Asura: Vengeance Edition - Wrong background image

Blackwood Crossing - Corrupt picture/icon on site

Blacksad: Under the Skin - Wrong background image, it is slightly changed

BIT.TRIP BEAT - Corrupt image/logo on site

Bloodstained: Ritual of the Night - Wrong background image and logo

Blair Witch - Missing Goodies

Bright Memory - Wrong background image and logo on site

Caesar™ IV - Corrupt picture/icon on site

Children of Morta - Wrong background image and logo on site

Conquests of the Longbow: The Legend of Robin Hood - Corrupt image/logo on site

Crawl - Wrong background image

Curious Expedition - Wrong background image

Depth of Extinction - Wrong background image and logo on site

**Comment by MachineGunnur** [comment]
curropt images are beacuse of issue at GOG.com end. using their CDN which they recently changed for images. Cant fix those :)

See here:https://images.gog-statics.com/4ebddcbc30342fdec0a95841361a2b0a0b9203010d7a4bd1229e3b6d30a30111.jpg

**Comment by rasay1** [comment]
ok, but the wrong icons and background images can be fixed? Auto updating pictures are not an option, do you have to manually update changes?

**Comment by MachineGunnur** [comment]
initial adding games is done auto. updates changes require manual fixing.

**Comment by MachineGunnur** [comment]
fixed titles

**Comment by MachineGunnur** [comment]
updated logos/bgs
