### ISSUE TITLE
OUTBUDDIES is OUT OF DATE

### ISSUE THREAD

**Issue by SilentMRG** [MachineGunnur/GOG-Games#188]
Please, update OUTBUDDIES for OUTBUDDIES DX

![c53df8cd3f8b5a8395eeb334a225b7248c96dd7a6a9b3c3a081a14a52421c127](https://user-images.githubusercontent.com/62117728/85044740-70784e80-b164-11ea-83fa-a000818014ca.jpg)

This version is very out of date: https://gog-games.com/game/outbuddies

You see here the last version: https://www.gogdb.org/product/1485699348#downloads

Thank you very much!!!

**Comment by MachineGunnur** [comment]
if game is out of date. most likely dont own or none shared. exact issue with this game,

have good day

**Comment by SilentMRG** [comment]
I understand ... However, I thought it was possible to update immediately, considering that the game is in the catalog of "gog-games".

Another thing that made me think it was possible, refers to the topic that another user opened asking for updates to several games ... And all (or almost) were updated in a few days.

Anyway, thank you for your attention and have a nice day for you also!

**Comment by SilentMRG** [comment]
Thank you so much for uploading Outbuddies! And thank you so much for all the work you do! For me, your website is the definitive source of downloads. =D
