### ISSUE TITLE
"Something Went Wrong" on Starbound

### ISSUE THREAD

**Issue by quiapho** [MachineGunnur/GOG-Games#19]
Starbound's txt said report the bug, its page hasn't expected data but some script data instead

**Comment by MachineGunnur** [comment]
game is now there. 
also updated upload script will a potential fix (hopefully...)
will monitor and push to [GOG Games: Upload Scripts](https://github.com/MachineGunnur/GOG-Games-Upload-Scripts) if works  =)

**Comment by quiapho** [comment]
Thanks!
