### ISSUE TITLE
Download thingy is too long with 1 row of games.

### ISSUE THREAD

**Issue by GooUckd** [MachineGunnur/GOG-Games#193]
Alright, heres a bug or something.
So, when I was searching for S.T.A.L.K.E.R..
I found out, the download thingy is too long!
I was only able to see/download like a few parts, instead of the 7 or 9 or something.

But there is a way to fix this, either you zoom out with your browser..
Or you, the creator of the site; Make like the download list into a shorter way?

This is the end of da report..

**Comment by MachineGunnur** [comment]
scroll down in your browser after you click download and the list expands down?
