### ISSUE TITLE
ATOM RPG v1.16 cannot install

### ISSUE THREAD

**Issue by Candidate34** [MachineGunnur/GOG-Games#194]
The source file is corrupted, i download twice still have this problem

**Comment by MachineGunnur** [comment]
fixed when it next uploaded

**Comment by MachineGunnur** [comment]
mistake. fixed in next upload

**Comment by frostbytion** [comment]
Why don't you verify by GOG Times before uploading?

**Comment by frostbytion** [comment]
Mistakes happen. Well, please use `./gog-times.sh -v [EXE/ZIP]` ([GOG Times](https://gitlab.com/mjr-awesome/gog-times)) in the future.
