### ISSUE TITLE
No Man's Sky failed files integrity check

### ISSUE THREAD

**Issue by VonDach** [MachineGunnur/GOG-Games#195]
There is a big bug in Windows who corrupt big files (GB sized) copied from drive to drive.

Took me months to find a fix for it. Here it is:

In the registry change HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem NtfsMemoryUsage from 0 to 1
or
open CMD: "fsutil behavior set memoryusage 1"
Reboot

0 is auto but is bugged, you manually have to enforce default (1).

May fix your corruption problem.

Thank you for your nice work!

**Comment by Masamune3210** [comment]
I have never heard of this bug, and literally move TB's of data around daily! are you sure it's not hardware issues?

**Comment by VonDach** [comment]
I'm sure I downloaded it good. Your rar repacking is good, it's the big .bin file inside who is corrupted. Same thing happened with Atom RPG two weeks ago, corrupted .bin, your last release is fine throught.
You can check yourself your *.bin by installing it with the file integrity checked, just cancel it after integrity runtime to not install it.

I stopped corrupting good *.bin copying/moving them from differents drives weeks ago with that tweak.

**Comment by Masamune3210** [comment]
I'm not the repo owner, just someone who watches the issues, I use teracopy so I haven't run into the issue, and have no bearing nor care if it happens to stock explorer. It's advisable to use a alternative copy system instead of explorer anyway since stock explorer is missing a lot of things like file verification and chunked copies. But even when I was using stock explorer I never ran into this issue

**Comment by frostbytion** [comment]
Folks, no one needs "check BIN by installing with file integrety checkbox and then cancel before it starts install" at all. Well, Linux. I have made [GOG Times](https://gitlab.com/mjr-awesome/gog-times)  like 5 months ago, among all things it can do file verification automatically, no install, no Wine, no start of EXE. Only Bash.

Let me tell how easy this is. Firstly, `osslsigncode` verifies the EXE signature integrity by SHA-1/SHA-2, thus EXE is valid. Secondly I `tac` the end of the EXE and `grep` its raw line of [MD5#X][Total Count]. Thirdly I `md5sum` the same way like the installer does but without its crappiness.

There are a few downsides. Some weird games like Mafia 3 seem to have no integrity check whatsoever but multiple BIN. In that case I usually take my checksums from an independent source who seem to buy own games and to hash those.

The games who don't have MD5 probably would fail. I hope GOG doesn't do that anymore but everything is possible. In addition the Bash script does verify ZIP too if I remember right. However, I sadly seem to lost access to my repo and can't do anything for now.

I will say that if this is MachineGunnur's issue, I already took care of. Would you kindly use the tool to verify uploads' integrity of ZIP/EXE/BIN after copying on the file server or before uploading a game please? You already use it for timestamps anyway.

If this is not MachineGunnur's issue and they already use, I ask MachineGunnur to not only prohibit creating issues on missing but on "corrupted" as well except when no built-in MD5 or if you don't do the right thing and skip my verification.

This is not strictly MachineGunnur's issue but Windows'. Like, are you expecting me to verify all 2 thousand games by hand? No, impossible, no way that one will do it: There is no way to go at the scale of MachineGunnur without Linux and I reaspect that.

**Comment by MachineGunnur** [comment]
down from zippy, extract fine and passes integ check and installs fine.  C;osing
