### ISSUE TITLE
Instant Upload URL Refresh

### ISSUE THREAD

**Issue by ghost** [MachineGunnur/GOG-Games#197]
May I please request a feature in connection to [the bug](https://github.com/MachineGunnur/GOG-Games/issues/196)? Could you just not the "Game is currently uploading" but show old links while updating (i.e. static HTML) and then instantly refresh the page with all new links instead?

**Comment by MachineGunnur** [comment]
links are cleared when its game next turn. api just bugged out or something rare issue. just internet being internet
