### ISSUE TITLE
API Ghost Slugs on Queue

### ISSUE THREAD

**Issue by ghost** [MachineGunnur/GOG-Games#200]
2020-08-01 13:43:51 (UTC): prison_architect_cleared_for_transfer prison_achitect_psych_ward_wardens_edition and prison_architect_island_bound poped up on Queue.
2020-08-01 18:17:43 (UTC): prison_architect_cleared_for_transfer hasdisappeared from the list and the DLC is OK.
2020-08-01, after 18:31:09 (UTC): Two others disappears but nowhere to be found, like a ghost.

Notice an Anomaly within: The game's slug itself didn't popup but DLCs, no data on the page were truly updated.

Clicking on a slug in Queue was giving an error at the time. Not appeared on Updated and New. I expected not that but the prison_architect slug and correct data on the files who are actually existing. Does API have old slugs or a bug at? Hope no else is bugged by this.

Previously the database knew the below info names:
`setup_prison_architect_-_cleared_for_transfer_the_rock_1.02_3593_(64bit)_(39465).exe`
`setup_prison_architect_-_island_bound_the_rock_1.02_3593_(64bit)_(39465).exe`
`setup_prison_architect_-_psych_ward_wardens_edition_the_rock_1.02_3593_(64bit)_(39465).exe`
`setup_prison_architect_the_rock_1.02_3593_(64bit)_(39465).exe`
`pa_artbook_pdf.zip`
`pa_soundtrack_flac`
`pa_soundtrack_mp3.zip`

**Comment by MachineGunnur** [comment]
someone voted on hidden slug(s). no suppose to happen. bug that needs looked into. for now, dont have time not big issue. 

i fixed. not suppose to be there.
