### ISSUE TITLE
Witcher 3 missing part (29)

### ISSUE THREAD

**Issue by Szogun420** [MachineGunnur/GOG-Games#202]
Hello
I wanted to download witcher GOTY but there is one part missing,(part 29)  Could you help me please?
Zippyshare doesnt work, and there is one part missing on multi file mirror.

**Comment by MachineGunnur** [comment]
done

**Comment by Szogun420** [comment]
> done

Thank you very much

**Comment by breadloads** [comment]
In theory I could make a script who might check them by itself. No sure it will be used, looking at the past. Luckily the person knows Bash, PHP and JavaScript, I don't think this is impossible for 'em: Simply check that a file is present afterwards (after an hour or so) is relatively [easy for Zippyshare](https://github.com/ffluegel/zippyshare) (after [a fix](https://github.com/ffluegel/zippyshare/issues/10)). No idea what to do with MultiFileMirror, can't Bash that up. I just think that checking against dead should have been automated.
