### ISSUE TITLE
Witcher 3 dubbings

### ISSUE THREAD

**Issue by Szogun420** [MachineGunnur/GOG-Games#203]
Hello, I wanted to install Polish dubbing on my game but i cant find dubbings for both dlc's.
I installed dubbing for main game but it doesnt work. 
Could you help please?

**Comment by breadloads** [comment]
Let say directly, GOG Games was never interested in other translations too much, me too. It saves space and at the end of the day no other language gives you The 100% Coverage and ability to play all GOG games whatsoever. Interestingly enough the game could have an issue and looking at [DHT](https://btdig.com/search?q=+patch_witcher3_pl_goty_2.0.0.51.exe), I don't really see what you can do. Not like a person has a magic hat and can make what doesn'e exist. I am sorry.
