### ISSUE TITLE
The 13th Doll: A Fan Game of The 7th Guest – Missing Extras (Bad File)

### ISSUE THREAD

**Issue by Tuvalis** [MachineGunnur/GOG-Games#204]
The 13th Doll: A Fan Game of The 7th Guest is missing the complete Extras file. It's supposed to be nearly 500MB but it's only 1.2 MB and it says the archive is corrupt.

https://gog-games.com/game/the_13th_doll_a_fan_game_of_the_7th_guest

**Comment by Tuvalis** [comment]
Thanks for the fix! You do awesome work!

**Comment by breadloads** [comment]
They are supposed to check every file, I wrote a script who checks ZIP automatically. Yes, good they've fixed the mistake, a right move. No, not good in general, it wasn't supposed to even exist in the first place.
