### ISSUE TITLE
.bin missing in downloads for "Ticket to Ride"

### ISSUE THREAD

**Issue by SanosukeArg** [MachineGunnur/GOG-Games#208]
Ticket to Ride has all the .exes files but it's missing the .bin (not sure if this is where I should report this).

**Comment by MachineGunnur** [comment]
will fix

**Comment by breadloads** [comment]
They could avoid this if were using the script which I wrote and who allows to check (`-v`) a game, they knew it. Currently it only gets used for timestamps, it looks. The script will instantly say failed on an unexisting BIN file. Several times was made a suggestion on Issues to always use, no luck.
