### ISSUE TITLE
Regarding Dead Cells

### ISSUE THREAD

**Issue by MasterXYZ5** [MachineGunnur/GOG-Games#209]
I'm not here to request any DLC of the game, but just to point out something. The previous version of Dead Cells (1.9) included both DLCs available for the game, one which is free and the other one is a paid DLC. After the new update was released (1.10), the files on gog-games only include the base game and the free DLC, but there is no trace of the other one. So I just wanted to ask, are games coming from the same source, or they come from different sources (thus explaining the absence of the DLC file)? Because if a specific game comes from the same source, then it is just a missing file error that can be fixed by reuploading the game with all its files. Thanks for reading, have a great day.

**Comment by MachineGunnur** [comment]
just dont have at that time. the less information, the better. sorry

**Comment by MachineGunnur** [comment]
added soon though.

**Comment by breadloads** [comment]
Unfortunate that the sorry was not honored and everything is [repeated](https://github.com/MachineGunnur/GOG-Games/issues/215) after 14 days, again.

**Comment by Anyfurry** [comment]
Now [fixed](https://archive.is/W6WnQ) again.
