### ISSUE TITLE
Change file hoster

### ISSUE THREAD

**Issue by vujaja** [MachineGunnur/GOG-Games#21]
I guess you are aware of this but Zippyshare is unavailable around the entirety of europe because they are mad about something so around 741 million people is unavailable to use the links on your site.
Please look for some alternative host.

**Comment by MachineGunnur** [comment]
there are ways around it. closing

**Comment by MachineGunnur** [comment]
re-opening, looking at file hosters. openload is viable alternative. will test upload (and download) to it.

**Comment by MachineGunnur** [comment]
another possible one: https://letsupload.co/

**Comment by MachineGunnur** [comment]
rclone + google drive another option.

**Comment by MachineGunnur** [comment]
tested Google with rclone, it's fine. just need unlimited account for more games... if can help, please let know here!

**Comment by MachineGunnur** [comment]
do not want google EDUCATION email. those get deleted fast. need team drive.

**Comment by MachineGunnur** [comment]
i found kind person who will share. will switch over to Googledrive in next few day.

**Comment by MachineGunnur** [comment]
upload from now on use googledrive. closed

**Comment by shakeyourbunny** [comment]
You know that switching only to Google Drive is very dumb.

There is a hard limit how **many** people may download a file for a certain period of time, and you really really cannot circumvent that.

You just put the whole world in the "cannot download" category instead of the restrictions of zippyshare. Thank you.

**Comment by hellwalker31** [comment]
it is so easy to bypass it... but... it is tiring...
and i prefer zippy over gdrive... if 700 million people cant reach zippy? so... 
the world population is over 6billion... 
and why dont think about cloud mail ru instead of gdrive... 
this is not enhancement... this is f***
