### ISSUE TITLE
[RECOMMENDATIONS] Download Manager and Unpacker

### ISSUE THREAD

**Issue by SilentMRG** [MachineGunnur/GOG-Games#210]
**_Hello everybody!_**

**Are you looking for a good Download Manager + File Unpacker?!**

_I recommend using the Free Download Manager which is available for Windows, macOS, Linux and Android!_

_He is also a great Bittorrent Client._ ^^

**Follow the link to download the FDM:** https://www.freedownloadmanager.org

**For more information:** https://en.m.wikipedia.org/wiki/Free_Download_Manager

---------------------------------------------------------------------------

**_Difficulties to extract the files?!_**

**Use 7-Zip:** https://www.7-zip.org/

**For more information:** https://en.m.wikipedia.org/wiki/7-Zip

_Both programs are 100% free and free of advertisements and viruses!_

**_Thank you for your reading and attention! =)_**

**_I hope I helped you! :D_**

**Comment by Masamune3210** [comment]
Go spam your scheisse somewhere else

**Comment by SilentMRG** [comment]
> Go spam your scheisse somewhere else

Spam???

The links are authentic!

Checking before assaulting you didn't do it right?

Take a look before you talk nonsense.

**Comment by Masamune3210** [comment]
May not be spam, but also isnt the spot to be promoting things. This is for issues with the website, not to promote random downloaders

**Comment by MachineGunnur** [comment]
doesnt even work with zippyshare and/or multifilemirror hosts..........
