### ISSUE TITLE
Error 522 Connection timed out

### ISSUE THREAD

**Issue by confever** [MachineGunnur/GOG-Games#213]
Got this today : 

Error 522 Ray ID: 5cae366b2a440585 • 2020-08-30 11:36:10 UTC
Connection timed out

You
Browser
Working

Los Angeles
Cloudflare
Working

gog-games.com
Host
Error

**Comment by SilentMRG** [comment]
> Got this today :
> 
> Error 522 Ray ID: 5cae366b2a440585 • 2020-08-30 11:36:10 UTC
> Connection timed out
> 
> You
> Browser
> Working
> 
> Los Angeles
> Cloudflare
> Working
> 
> gog-games.com
> Host
> Error

That mistake happened to me these days ... Now everything is normal. =)

The error, if my memory serves me correctly, occurred at 6:30 pm or 7:30 pm on a business day.

**Comment by breadloads** [comment]
A one hour "blackout" is not the end of the world. Still makes me wonder what causes it.

**Comment by MachineGunnur** [comment]
shit happens.
