### ISSUE TITLE
Missing File in Dead Cells

### ISSUE THREAD

**Issue by MasterXYZ5** [MachineGunnur/GOG-Games#215]
A couple of weeks ago, the game Dead Cells was updated to version 1.10.0 with both DLCs included (Rise of the Giant, The Bad Seed); since the last patch 1.10.1 updated 2 days ago, the game is missing one of the DLCs (The Bad Seed). Is it possible to upload a fix with all the files? Thanks

**Comment by breadloads** [comment]
I understand you, all of you, including SilentMRG. To others, who want Quality and Quantity, not speed, please use [my backup](https://web.archive.org/web/20200824192621/https://gog-games.com/game/dead_cells) of the page with 1.10.0. Meanwhile, I [cannot find](https://btdig.com/search?order=0&q=%22setup_dead_cells_-_the_bad_seed_1.10.1_%2840622%29.exe%22) the latest version with the said DLC anywhere on the P2P network. In my opinion this is pointless and I am very disappointed.

**Comment by MachineGunnur** [comment]
have more pressing issues than making sure pirates/collectors/gamers have lastest and greatest games and dlc for free. when get around to it all will be updated...

**Comment by Anyfurry** [comment]
If you're not for latest and greatest games on literally GOG Games, what you are for, for Beer? I do understand you work solo but lefts me wondering about the "pressing" issues and how it can be solved that GOG Games can do what it supposed to do.

P.S. Repeating the same messages 3 times makes no sense.
