### ISSUE TITLE
Vote for Re-Upload doesn't Work on a 2 Months Old Game

### ISSUE THREAD

**Issue by breadloads** [MachineGunnur/GOG-Games#216]
[The Elder Scrolls IV: Oblivion - Game of the Year Edition Deluxe](https://gog-games.com/game/elder_scrolls_iv_oblivion_game_of_the_year_edition_deluxe_the_game) got busted. Both choices are dead, totally. I hoped after a while I could vote and fix this. No way, no vote, no choice except to rise an issue. I think this is a bug, the site of yours said, quote, "All games are available to be voted on for a re-upload 30 days after they were last uploaded to guard against dead links." No clue why it didn't work as should.

**Comment by MachineGunnur** [comment]
game was LAST UPLOAD on August 5. It's all working.

**Comment by Anyfurry** [comment]
The "Updated" label is kind of confusing.
