### ISSUE TITLE
Please Put Quality and Quantity Above Speed

### ISSUE THREAD

**Issue by breadloads** [MachineGunnur/GOG-Games#217]
I'm a collector and a player. As the Collector I worship Quality and Quantity the most. As the Player, I can't accept nor technically play an updated game with my old saves without add-ons. What I see right now is basically trying to put fresh yet Green and tasteless non-full tiny apples who are only a few days old against apples which is a week old but Big, Tasty and Red. You claim to be a Russian, let's see. We have a proverb, "Поспешишь – людей насмешишь" ("Hurry too much in action, will make people to laugh at yourself as a fool"): Suggests a person shall do things mindfully and steady.

Honestly, I don't know who thought to repeat the same mistake twice as it is with "Dead Cells" recently and a few weeks ago: When people say "Sorry," it usually means they won't do an alike mistake again. Well, like the apples, Green is put instead of giving Red. Please put Quantity and Quality above Speed, people don't seem to be interested in getting an inferior version. Getting a fresh cheap phone against your flagship from the same month makes no sense. All want BTR. The 2 below are not only fresh but good, came a day before you updated to the same version without all the DLCs.

[**setup_pc_building_simulator_1.8.7_(64bit)_(40597)**](https://btdig.com/search?order=0&q=setup_pc_building_simulator_-_good_company_case_1.8.7_%2864bit%29_%2840597%29.exe)
[BLAKE2b, SHA-2 and SHA-3 Checksums](https://pastebin.com/cjf10rSj)

[**Age of Wonders Planetfall - Rutracker Edition**](https://btdig.com/search?q=setup_age_of_wonders_planetfall_-_invasions_1.315_%2864bit%29_%2840740%29.exe)
[BLAKE2b, SHA-2 and SHA-3 Checksums](https://pastebin.com/z3U9PQcf)

**Comment by Masamune3210** [comment]
Perhaps step down from the high horse a bit, they have already stated multiple times that they are under circumstances out of their control

If you don't like it so much, perhaps go get the game from the literal million other websites offering it as well....

**Comment by MachineGunnur** [comment]
have more pressing issues than making sure pirates/collectors/gamers have lastest and greatest games and dlc for free. when get around to it all will be updated...

**Comment by Anyfurry** [comment]
If you're not for latest and greatest games on literally GOG Games, what you are for, for Beer? I do understand you work solo but lefts me wondering about the "pressing" issues and how it can be solved that GOG Games can do what it supposed to do.

P.S. Repeating the same messages 3 times makes no sense.
