### ISSUE TITLE
Separate "Updated" for Files and Links

### ISSUE THREAD

**Issue by Anyfurry** [MachineGunnur/GOG-Games#219]
At the time nothing distinguishes the two. A user may see all links non-working (i.e. a takedown), know nothing except "Last Update: 2 Months ago," not understand why no vote, be disappointed, confused. Confusion harms donations, presents the site less reliable.

Maybe a good idea to remove Vote to Re-Upload entirely and check dead links automatically each month on game by game basis after a month is gone, silently re-uploading without adding the second field: Needs no User interaction, saves traffic by prohibiting unnecessary re-uploads. 

Alternatively simply show a game's date when a new vote can be cast by graying out the Vote button and showing the date on Top.

**Comment by MachineGunnur** [comment]
last update is when the game was last updated. it has nothing to do with last upload. i dont see how it is confusing

**Comment by Anyfurry** [comment]
"Update" links is technically upload as well, you bring links up to date by [definition](https://www.merriam-webster.com/dictionary/update) this is an update:
> To bring up to date

Update files is what you call update for some reason. The confusion as a user, not GOG owner, arises from. Its ambiguity can be erased by using "Updated Items: x months ago." Simply replacing "Last Update" with should not be unreal. In the end, I see no way to know after a takedown when I can vote and that's the issue in a nutshell, no data on the last upload shown.
