### ISSUE TITLE
More fixes

### ISSUE THREAD

**Issue by rasay1** [MachineGunnur/GOG-Games#220]
A Plague Tale: Innocence
gogdb link: https://www.gogdb.org/product/1901367087

Age of Wonders: Planetfall
gogdb link: https://www.gogdb.org/product/1918301028

An Elder Scrolls Legend: Battlespire
gogdb link: https://www.gogdb.org/product/1435829464

BEAUTIFUL DESOLATION
gogdb link: https://www.gogdb.org/product/1295420179

Bubsy: The Woolies Strike Back
gogdb link: https://www.gogdb.org/product/1503510643

Call of Cthulhu: Dark Corners of the Earth
gogdb link: https://www.gogdb.org/product/1189711155

Close Combat: The Bloody First
gogdb link: https://www.gogdb.org/product/2096044923

Colonization, Sid Meier's
Changed title - Colonization, Sid Meier's ⇒ Sid Meier's Colonization

Crystal Caves
This should be removed, it is included in "Crystal Caves HD" as a goodie

Cthulhu Saves Christmas
gogdb link: https://www.gogdb.org/product/1620010340

Daemonsgate
Missing version number in filename

Darksiders II
This has been replaced by: Darksiders II: Deathinitive Edition

Fallout & Fallout 2 are updated and different from classic editions

Good Night, Knight
This is IN DEV

Legend of Keepers: Career of a Dungeon Master
This is IN DEV

Saint Kotar: The Yellow Mask
This is another "prologue" or "Demo game" until the final version comes out

The World Next Door
Missing goodies (Comic)

True Fear: Forsaken Souls
Changed title - True Fear: Forsaken Souls ⇒ True Fear: Forsaken Souls Part 1

Neighbours From Hell 1 and Neighbours From Hell 2 has been replaced by:
Neighbours Back From Hell (Both games are in 1 installer now)

Neon Chrome - Arena (Wrong title)
Neon Chrome

"Hearts of Iron II" and "Hearts of Iron II: Doomsday and Armageddon"
Why do they have the same file?

Pushover
Missing version number in filename

Sorcerer King has been replaced by:
Sorcerer King – Rivals

STRAFE: Millennium Edition
Changed title - STRAFE: Millennium Edition ⇒ STRAFE: Gold Edition

Space Haven
This is IN DEV

Vagrus
This is IN DEV

Urtuk: The Desolation
This is not IN DEV

Incomplete games removed from GOG (Just for info, can keep them for collection purposes):

Armello DRM Free Edition (No updates or DLC for DRM Free Edition)
Dark Matter (It was an unfinished game)
Descent: Underground (Removed while IN DEV)
Startup Company (Removed while IN DEV)
Wolcen: Lords of Mayhem (Removed while IN DEV)
Gremlins, Inc. - Not updated and it is not possible to start the game
Gremlins vs Automatons - Same developer, not updated anymore

**Comment by MachineGunnur** [comment]
Thank you.

indev/removed games are just collection purposes i guess

**Comment by MachineGunnur** [comment]
all fixed except wrong GOGDB links.

**Comment by rasay1** [comment]
Updated main post

**Comment by dtrail** [comment]
Stellar Tactics
gogdb link: https://www.gogdb.org/product/1170879692#builds

Latest build on GOG-Games: 0.563
Latest build on GOG: 0.569
