### ISSUE TITLE
Freedom Fighters - Stuck in the upload list and with incomplete hosters

### ISSUE THREAD

**Issue by SilentMRG** [MachineGunnur/GOG-Games#222]
Hi,

The game in question was uploaded only on Zippyshare and one part of the game on LetsUpload. In addition, it is stuck in the Upload Queue.

Thank you!

**Comment by SilentMRG** [comment]
It looks like it wasn't a mistake. Maybe a delay...

**Comment by SilentMRG** [comment]
Hello,

The Game and Extras have not been uploaded to MultiFileMirror. In the other hosters everything seems to be fine.

Taking this information into account:

"The upload script has been updated to now upload to all three file hosts simultaneously."

There was probably an error in the script.

Best regards!

**Comment by MachineGunnur** [comment]
letsupload and mfm are having issues.
