### ISSUE TITLE
Some Notes - Sphinx and the Cursed Mummy

### ISSUE THREAD

**Issue by SilentMRG** [MachineGunnur/GOG-Games#226]
Hi,

The soundtrack files are incorrect.

On the website, the file size in MP3 is 193.14 MB and the FLAC format is 292.78 MB.

1 - While here: https://www.gogdb.org/product/1281140155#downloads

2 - And here: https://www.gogdb.org/product/1281140155#changelog

Obviously the size of the files on the website refer to the compressed size, however, in a previous observation they are incorrect, and the second link makes this clear.

I may be mistaken ... But I don't think the site's files were compressed that much.

Apparently the "Authoring Tools" file is also the wrong size according to: https://www.gogdb.org/product/1792083431#changelog

This is not a request! It is just a note to improve the reliability of the site.

Thank you for your attention!

**Comment by SilentMRG** [comment]
Hi,

Another complementary observation is about "Authoring Tools".

It is not a game file, it is actually a DLC (just like the soundtrack) and should be compressed separately (along with the soundtrack in the Extras file).

With that, users of the site would not need to download more than 2 GB of data, this would save time. And there are also users who don't care about extras, in which case, these users would only download the game file, which is only 786.4 MB.

I think that's it.

If anyone wants to complement something ... Feel free!


Thank you for your reading!
And sorry for the mistakes... I am not North American.

**Comment by MachineGunnur** [comment]
the only files were not up to date were soundtracks. 

its not big deal but i move the Tools over to goodies now.
