### ISSUE TITLE
OUTBUDDIES DX - "Wrong" version? Or "future" version?

### ISSUE THREAD

**Issue by SilentMRG** [MachineGunnur/GOG-Games#228]
Greetings...

The site has version 1.60_ (1.0.5);

However, according to:

https://www.gogdb.org/product/1485699348#downloads

and...

https://www.gogdb.org/product/1485699348#builds

The latest version is 1.60 (1.0.4b);

How is it possible for the site to have a version that has not yet been released?

How strange... (I think)...

Grateful for the attention!

**Comment by MachineGunnur** [comment]
idk.
