### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by Balroth** [MachineGunnur/GOG-Games#231]
Hello, I was reading the "Frequently Asked Questions" section of your site
![14](https://user-images.githubusercontent.com/25630803/96350894-a3a1fe80-10c0-11eb-866d-63112f518a97.PNG)

I used it on `/game/kingdom_under_fire_the_crusaders` but it doesn't have the game's download itself.
![14](https://user-images.githubusercontent.com/25630803/96350964-35117080-10c1-11eb-8365-efe6a1465f16.PNG)

That said, the reason I downloaded and used this software, is because of google captcha tbh. I mean, the main reason people don't use [the classic site] is because it tracks your IP. Just giving access to the site's javascripts to run the captcha, gives the IP away, even if you use Tor. As in, you can use Tor and give no information but you cannot download the game if you don't give it access

**Comment by MachineGunnur** [comment]
hi, you use the copy links function on site in conjunction with jdownloader2.

the site uses google recaptcha to prevent DMCA crawling bots from reporting links.

why are you so paranoid about recaptcha and your IP? no one cares if you download games.

**Comment by Balroth** [comment]
>hi, you use the copy links function on site in conjunction with jdownloader2.

Where is the copy links function? I cannot find it on that link above, nor its gogdb equivalent

>the site uses google recaptcha to prevent DMCA crawling bots from reporting links.

oh lel

>why are you so paranoid about recaptcha and your IP? no one cares if you download games.

Not paranoid at all, otherwise I wouldn't post this, linking my account and email, though others may care but I understand if not for a good captcha method (manual is hard but possible) then DDOS could happen and ofc the aforementioned bots, damn, never thought of them

**Comment by MachineGunnur** [comment]
> Where is the copy links function? I cannot find it on that link above, nor its gogdb equivalent (pre-captcha)

![image](https://user-images.githubusercontent.com/45913297/97118065-f18db680-16ff-11eb-8894-0cf7caf1e70f.png)

icons next to right of hoster name. expand/retract, **copy links,** open all links in tab
