### ISSUE TITLE
Captcha System

### ISSUE THREAD

**Issue by Hashnoob** [MachineGunnur/GOG-Games#232]
Please change to any other captcha system, google forces you to answer way to many for each title, making the process of getting links very tedious.

**Comment by Masamune3210** [comment]
they all will do that eventually. the more you solve them in a period , the more you will get. it's part of the anti-bot stuff

**Comment by MachineGunnur** [comment]
using google invisible captcha. its not that bad really, and no. sorry.

**Comment by mequare** [comment]
It makes the site a real nightmare to use. The rest of the users are under Tor or VPN, i.g. Germany, ReCapcha is very, very, very aggressive to 'em. You didn't re-upload or fix few games when some bad people nuked links eirher, it is disappointing twice. Can only feel sorry to those who cannot automate it.
