### ISSUE TITLE
Zip Extras - Like the good old days.

### ISSUE THREAD

**Issue by Hashnoob** [MachineGunnur/GOG-Games#233]
Please consider zipping extras like they use to be on the site, so JDownloader does not just group all of the extra files into a "Various" folder for dozens of titles which making you stop every title and merge the links into a new folder.

**Comment by Masamune3210** [comment]
the only time it won't merge them barring a glitch is when it's only one item, as it automatically bunches parts together if it can follow the naming pattern

**Comment by MachineGunnur** [comment]
what? 
![image](https://user-images.githubusercontent.com/45913297/96358699-9bb28080-10f9-11eb-896f-6e26991405b4.png)

**Comment by mequare** [comment]
Please no changing game files, let it be as GOG provides originally.
