### ISSUE TITLE
website broken on firefox for android

### ISSUE THREAD

**Issue by binocry** [MachineGunnur/GOG-Games#234]
I can't load section for download it only loading like on screenshot

Latest stable firefox 81.1.4

![Screenshot_2020-10-18-14-00-51-547_org mozilla firefox](https://user-images.githubusercontent.com/69342001/96360816-a5b09f80-114a-11eb-94d1-dc3ed411d35c.png)

**Comment by MachineGunnur** [comment]
Refresh the page on mobile. Try again. Recaptcha does work on firefox on mobile.
