### ISSUE TITLE
Inconsistency in the Database

### ISSUE THREAD

**Issue by mequare** [MachineGunnur/GOG-Games#235]
Megaquarium is [on the site](https://gog-games.com/game/megaquarium), not on the "All Games" list and [the search](https://gog-games.com/search/all/52/title/asc/any)  doesn't work. "X4: Foundations" suddenly [vanished](https://gog-games.com/game/x4_foundations) just like with a "Starpoint Gemini" game in the past. Please fix.

**Comment by MachineGunnur** [comment]
they were hidden. welcome.

**Comment by mequare** [comment]
Thanks!
