### ISSUE TITLE
ReCapcha to CryptoURLs

### ISSUE THREAD

**Issue by mequare** [MachineGunnur/GOG-Games#236]
Good Old Downloads was facing no issues with its link encryption. It was highly user friendly. No bots were taking down links, no spying on us, no Google ReCapcha. The history proofs: The site worked great and the users were happy: A way to be donatable and successful on the road of progress it is.

The current is torture for us, people who respect privacy: We use Tor or VPN, we don't want to go to jail or pay fines. So guess what, folks? ReCapcha is really heavy on, especially when Firefox is in Private Mode, always torture, sometimes it doesn't even show up, it calls a human a bot, nonsense. Cannot imagine how anyone would want to humbly save all GOG of yours offline from the site or update few hundreds games: Too many, too much manual labor to 'em. 

Please, really, I understand your target but in the current shape you deeply harm the very User Experience of Interaction with the site for many privacy folks, badly putting down all donators whom were supposed to support and be thankful. I know the one wants money and donations: Would a user whom the one "torture" do so? No. Maybe install ads if you don't care anymore about us. In the end the user would go on Torrminatorr, your rival, and support it or any other: Many users hate ReCapcha and in turn may start to hate you, the site or leave it forever.

I wish you no harm, only knowledge. I'll say briefly that no capcha system is perfect and just gives you a sense of false security, like an antivirus. Well, let be honest, if you do nothing and close the issue with changing nothing, you do you, it doesn't matter to me, at all, have an already automated download bot system. But ReCapcha harms unexperienced users, that's what bothers me with. Look, I proudly remember Good Old Downloads, I even donated to, a nice site: I wish someone would remember yours like that, not as ReCapcha Hell. Hope you choose well.

**Comment by Masamune3210** [comment]
It's not even close to torture, especially for the normal use case which isn't scraping the site for all of its contents. ReCapcha is only hard on Private mode and Tor because it removes most of the information that ReCapcha would use to avoid the manual check. Most sites involving downloads use ReCapcha or hCapcha, its pretty normal.

Also, no one unless they are acting maliciously has any rivals in true malice in the scene, its all the same goal in the end

**Comment by MachineGunnur** [comment]
Here is the thing:

we remove RECAPTCHA and replace with hCaptcha invisible in next few days.

I watching URLs like high profiel games; witcher, prey, etc and they were being removed from zippyshare 1 day after upload. that smells of DMCA bots.

**Comment by MachineGunnur** [comment]
@Masamune3210

i agree. normal users will not raise any voice as they get a few games and maybe solve 1 or 2 captcha to build trust.

you must be doing scraping and automation to keep your games up to date. which is fine, but we not supporting that and will not remove the captcha protection.

**Comment by MachineGunnur** [comment]
@mequare 
no promise, but when/if get around to re-write or add new features a public API access from donating would be on the list.

just time is short with me right now.

**Comment by mequare** [comment]
Forget it.

**Comment by mequare** [comment]
@MachineGunnur hCapcha is less effective and worse built against bots than Google. I do not know how hCapcha behaves towards these systems, if it goes like the before, better sit still. If it will not be effective enough, somebody may use Sodium and this is not good.

I saw the takedown issue, heck, it made me trouble on "The Elder Scrolls 4: Oblivion" and forced to do P2P. Whoever did it, they should burn in Hell.

**Comment by MachineGunnur** [comment]
the google captcha is keep prey, witcher, etc. links alive. certain games are targeted by bots, bethesda, etc tomb raider. as such.

you can bypass google recptcha with online services. the dmca bots dont bother to pay and use.

just need something to interrupt them. which proves it is working. just can try hcpatcha and see

**Comment by mequare** [comment]
Short:
1. Don't/do API, you do you;
2. Please no hCapcha, it's worse.

**Comment by mequare** [comment]
If keeps alive efficiently, then fuck me.

**Comment by mequare** [comment]
I remember how thd oe tried different cloud providers, it didn't go well. Let maybe be strateguc then and change tactics of it faild. All of that movement would only bring risks while the old is proven to work.

**Comment by mequare** [comment]
Right now this is honestly fine. The issue was made against capchas in general and ReCapcha in particular, no ask of a switch to another capcha and no logical reason to do the unknown, especially if you tell it protects fine already. From the security standpoint, I will rather trust to run Google's JavaScript. Currently it is both worlds: Protects against DMCA bots, doesn't create too much trouble to me. If @Masamune3210 is correct in their "normal" (not normal to my normal) usage, then nevermind, I'm silly.

**Comment by MachineGunnur** [comment]
i prefer hcaptcha as they are more privacy oriented. i not aware of them and having invisible aptcha. i plan on switching as fuck google, you know?

**Comment by mequare** [comment]
"I not aware of them," "As fuck Google" what? No, I don't know on that. Are you really a Russian native speaker? Speak Russian then, be clear. I'm a native, even if I tend to dislike the language personally. So, the one said the provider is more privacy oriented yet missing that if somebody will breach its security system, then bye-bye privacy: Less likely a breach with Google. 

Additionally did you test if CryptoURLs work against the bots or it is prefered to speculate on no basis? Speculation makes no honour, let be objective. I am using the site daily, the encryption was never used. "You must be doing scraping and automation to keep your games up to date" and "not supporting that and will not remove the captcha protection:" This is the real reason of the actions.

Links and privacy are probably an excuse, the target seems to be to make trouble for those who download games broadly or or were using The Wayback Machine to be prepared if something like with GOD may happen. Think of it: A site for downloading games wants to make downloading harder. Otherwise the one would see if the least intrusive way helps. 

If I wanted to nuke you, folks, I could but I won't 'cause not my thing. I've all links up to date right now, uncapched. If I wanted to rival you, I've two VPS servers and dozens of TBs with a lot of traffic but I don't, obviously. So pay no be afraid of us, GOG Collectors.

**Comment by mequare** [comment]
Wait a minute, was the site DMCAed while on Onion? Don't remind, troubles arrived after the transition. Maybe provide two versions, like BtDigg or The Pirate Bay does: One is on Cloudflare, the other is Onion.

**Comment by MachineGunnur** [comment]
keep getting captcha with hcaptcha invisible even after solving some. stick with RECAPTCHA :) less annoying

**Comment by MachineGunnur** [comment]
i can try disable captcha and turn on cloudflare things and test and monitor links that were gong down fast.

**Comment by MachineGunnur** [comment]
i am sure these bots have no problem access Tor and reporting links either, btw

**Comment by MachineGunnur** [comment]
Looks like you have to buy: https://www.cloudflare.com/products/bot-management/

Would "under attack mode" suffice and provide similar action? not buying their product.

**Comment by MachineGunnur** [comment]
Alternative:

Bot Fight Mode

Challenge requests matching patterns of known bots before they can access your site.

Requests matching Cloudflare-identified, non-legitimate automated traffic patterns will be challenged and/or blocked by Cloudflare.

https://support.cloudflare.com/hc/en-us/articles/360035387431

**Comment by mequare** [comment]
Thank you.

**Comment by mequare** [comment]
You tested hCapcha. Smart. Respect to you. As such I deleted what is no longer true or reflects the current time

Okay. I read what was done, this is too risky

Sad on Tor, my sorrow is infinite. Rest in Peace, Onion, Rest in Peace.

Don't pay Cloudflare, don't overfeed 'em, it doesn't deserves it and may be a waste of money, I don't read prices, I'm just a traveller, I hoped it could be not paid but I was wrong.

Well, I will be ghost honest, Cloudflare checked my native IP (85.26.241.0/24) and then disappeared. But, it is a big but, it is totally useless on 51.210.80.127 and other Tor IPs, it didn't check anything. Run yourself and test, you know. I suspect it is not on per device basis and it worries me to death, really.

I don't think it works. Sorry. Turn the new weird heck off and let continue to stick to what works instead, be conservative, like with Zippyshare, you know. Fuck this Cloudflare then. Don't disable ReCapcha, please, don't disable protection, it is critical, it helps, I don't want dead links, dead makes me trouble. ReCapcha does not skip bots like the above weirdness: It doesn't even do what promised efficiently.

Please read, "Bot Fight Mode does not utilize captchas, blocks, or cookies." Thus it works per IP and may allow a bot to operate and wreck havoc, no good, a piece of crap. I ask to don't risk enabling this and disabling ReCapcha, no interest in dead links. I know it would harm many users who keep no backups, I don't want them to be sad even a little bit nor I want you to loose traffic. See, "Slows the bot with a computationally intensive challenge," it said, it doesn't block, it said, this is not what is needed, the need is to prevent DMCA, not that, this is just garbage.

**Comment by mequare** [comment]
Short:
0. Respects for testing.
1. ReCapcha is good, it proven itself work.
2. The Cloudflare stuff doesn't work and it's place is in Recycle Bin.
3. Rest in Peace, Onion.

**Comment by mequare** [comment]
Short:
0. Respects for testing.
1. ReCapcha is good, it proven itself work.
2. The Cloudflare stuff doesn't work and it's place is in Recycle Bin.
3. Rest in Peace, Onion.

**Comment by Pringlesium** [comment]
"**Slows the bot** with a computationally intensive challenge," "Bot Fight Mode **does not utilize** captchas, **blocks,** or cookies." LMAO.

**Comment by Pringlesium** [comment]
CryptoURLs: Unknown. Not tested, won't work against Sodium bots, as "useful" as Cloudflare, read "pretty risky."
ReCapcha: OK. works against the bot, keep and don't listen to anybody, even me.
hCapcha: Failed. Made in Hell, as I expected in advance.
Cloudflare: Failed. To be turned off, only slows, not blocks, this is practically antiDDoS, doesn't protect against what we need, I can say that much from the desc.

**Comment by fable-cable** [comment]
Stop jamping to conclusions. It wasn't shown to not work for now. Go back only when DMCA reemergences.

———

Не беги впереди паровоза. Не было доказано, что, мол, не работает. Давайте-ка в обратку только если DMCA опять доставать начнет.

**Comment by fable-cable** [comment]
> i can try disable captcha and turn on cloudflare things and test and monitor links that were gong down fast.

It doesn't seem you do the test, now both are pushed up.

———

Хреново кудябликов жарите, теперь две беды без еды.

**Comment by fable-cable** [comment]
The punishment of a liar is that they are never believed, even when they speak the truth.

———

Лжецу и в правде не верят.

**Comment by MachineGunnur** [comment]
This is what will happen for future:

Site will be re-written next year and public API will be implemented which you can gain access to by donating a minimum amount. You will not see any captcha either if logged into your account if you don't know what the fuck an API is.
