### ISSUE TITLE
X4 Foundations

### ISSUE THREAD

**Issue by dtrail** [MachineGunnur/GOG-Games#237]
There was an update around the time, but the actual patch (3.30.414400 HF-1) is still missing.

Also part 11 has disapperead from several mirrors and is only available on 3 of them.

**Comment by mequare** [comment]
3 mirrors are still no apocalypse, this is fine. GOG doesn't have that patch, no way to get, only for Steam.

**Comment by MachineGunnur** [comment]
whole new version upload coming today or tomorrow. be on look out.
