### ISSUE TITLE
Provide Resilience for the Site | Обеспечить выживание сайта

### ISSUE THREAD

**Issue by fable-cable** [MachineGunnur/GOG-Games#238]
I hope you have staff members now or a trustworthy friend, please be safe and don't get COVID-19, it will be extremely sad if so and I'm afraid there is no person like you on the whole Internet. Not great that you cannot afford to leave the country and be safer.

Russia [might start to block TLS 1.3 and others](https://www.privateinternetaccess.com/blog/russia-wants-to-outlaw-tls-1-3-esni-dns-over-https-and-dns-over-tls/) in the next year, when the linked draft becomes a law. It wants to replicate a bad [Chinese law](https://www.zdnet.com/article/china-is-now-blocking-all-encrypted-https-traffic-using-tls-1-3-and-esni/). Please prepare, I already rent a Shadowsocks server over a Knock daemon for my family, it is China-proof.

If you are from Russia, like me, a native (though, I dislike Russian personally, it doesn't fit me mentally anymore), then beware, both "vaccines" [didn't complete](https://www.thelancet.com/journals/lanres/article/PIIS2213-2600(20)30402-1/fulltext) the 3rd trial, sound skunky bogus. I don't wish you to have health issues due to this, this is terrible.

I genuinely hope the drugs will work but for now I'm only worry much on and another worry is that Russia may lockdown itself at some point or do something odd again. Very important to have a person who can continue your work, please find a successor, like, just in case.

———

Надеюсь, что теперь не работаешь в одиночку, а с друзьями, пожалуйста, будь осторожнее и не заразись COVID-19'ым, будет очень грустно тогда, и, боюсь заметить, ,нет таких же людей во всем Интернете. Прискорбно, однако, что не можешь позволить покинуть страну и быть в безопасности.

Россия [будет начать блокировать](https://meduza.io/feature/2020/09/21/ministerstvo-tsifrovogo-razvitiya-hochet-zapretit-sovremennye-protokoly-shifrovaniya-v-runete-togda-roskomnadzoru-budet-prosche-blokirovat-sayty) TLS 1.3 и другие в следующем году, когда данное безобразие станет законом. Оно копирует неладный [китайский закон](https://xakep.ru/2020/08/10/great-firewall/). Пожалуйста, подготовься, я арендую  Shadowsocks сервер с `knockd` демоном для моей семьи, работает даже в Китае.

Если из России, как я, и язык родной (правда, мне лично не нравится, т.к. не подходит по духу), то будьте осторожны, обе их «вакцины» [не прошли](https://www.bbc.com/russian/features-54425984) третью фазу испытаний, короче, проходняк полный на сегодня. Не желаю иметь проблемы со здоровьем из-за этого никому, ужасы эти.

Искренне надеюсь, что лекарства наши будут работать, но пока сильно беспокоюсь о том, что Россия может заблокировать себя в какой-то ответственный момент или наломать дров опять. Очень важно иметь людей, которые смогут продолжить работу сайта, пожалуйста, найдите преемников, поможет в случае чего.

**Comment by MachineGunnur** [comment]
chill - all alive and well here!

**Comment by SilentMRG** [comment]
The site is top notch! An example to be followed... Gog-Games is a golden pearl amid so much garbage that exists on the internet.

I am very grateful for everything the developer has been doing in these months! If it weren't for him, "GoodOldDownloads" would be buried next to its source code.

**Comment by fable-cable** [comment]
Good you well. C'mon with praise, even good shouldn't be too much. The risk is still here unless they, the person who may be he or she or else actually, will be a team. The issue is certainly not resolved and this is what worrisome, potentially dangerous. Divide is not a friend but the weakness.

They are in Russia. I'm, as a Russian, a person with citizenship of the 4th top infected country with no trustworthy vaccine, media and a horrible tendency in censorship and isolation, I know what I'm talking about first hand.  
 
———

Отлично если в порядке. Давайте-ка в меру с похвалой, лучшее враг хорошего. Риск по-прежнему существует, если только MachineGunnur, кто может быть им или ей, не станет командой. Вопрос, конечно, не решен и это беспокоит, потенциально опасная ситуация. Вместе сила, а разделение хило.

MachineGunnur из России. И я, как 1 из граждан России, 4-й страны по количеству инфицированных, без нормальной вакцины, медиа и с ужасной тенденцией к цензуре и изоляции, знаю о чем говорю как есть.
