### ISSUE TITLE
RSS is Broken | RSS убит

### ISSUE THREAD

**Issue by fable-cable** [MachineGunnur/GOG-Games#239]
It doesn't work anymore in an app like Feeder after the latest changes to the site. It can't even find the feed. Please fix.

———

Не пашет ни капли в Feeder'е и в других прогах после последних изменений сайта. Не может даже найти подписку. Прошу, исправь.

**Comment by MachineGunnur** [comment]
![image](https://user-images.githubusercontent.com/45913297/97117282-84c3ed80-16fa-11eb-9312-b68f54204727.png)

Hmm? working here?

**Comment by fable-cable** [comment]
![Screenshot_2020-10-26-10-47-55](https://user-images.githubusercontent.com/73414640/97121207-67038200-1714-11eb-8157-abaff808c2c1.jpg)
[Feeder](https://f-droid.org/app/com.nononsenseapps.feeder) (Open Source) and others do not.

———

[Feeder](https://f-droid.org/app/com.nononsenseapps.feeder) (Open Source) и ему подобные не работает.

**Comment by zerouser10** [comment]
Same problem with [QuiteRSS](https://quiterss.org/en)

![Captura](https://user-images.githubusercontent.com/73450216/97124082-52af8d00-16f4-11eb-9e66-6d6ca1b5461d.PNG)

**Comment by PoopsMcButt** [comment]
I believe this is due to Cloudflare DDOS protection? At least that's my issue right now.

**Comment by fable-cable** [comment]
![Screenshot_2020-10-27-16-00-00](https://user-images.githubusercontent.com/73414640/97255622-f0947c00-1808-11eb-952e-d2da0c857305.jpg)

Thank you, folks. Yes it was, I see that thankfully the culprit is off now, like, a few hours ago or shorter and the app shows the feed again. Hope it'll remain this way and working well. The issue is solved.

———

Спасибо всем вам. Да, смотрю, отключена зараза недавно, несколько часов назад или около того, и прога ленту кажет как раньше было. Надеюсь так и будет, в полнейшем порядке. Тема закрыта.
