### ISSUE TITLE
Password?

### ISSUE THREAD

**Issue by Pseudocrat** [MachineGunnur/GOG-Games#240]
On The Outer Worlds zippyshare the file requires a password?

**Comment by fable-cable** [comment]
GOG Games packs games automatically, [the script](https://github.com/MachineGunnur/GOG-Games-Upload-Scripts/blob/master/upload-script.sh) never encrypts a file.

———

GOG Games автоматически компрессит игры, [скрипт] (https://github.com/MachineGunnur/GOG-Games-Upload-Scripts/blob/master/upload-script.sh) никогда не шифрует файлы.
