### ISSUE TITLE
The Script doesn't consistently RAR up | Скрипт не всегда RAR'ит

### ISSUE THREAD

**Issue by fable-cable** [MachineGunnur/GOG-Games#241]
More than 250 files and 115 games are affected, including at least 116 executables, 130 ZIP and 4 BIN files. Examples: [overcooked_2](https://gog-games.com/game/overcooked_2), [8bit_hordes](https://gog-games.com/game/8bit_hordes), etc. RAR is important to be sure that files on a cloud server are not corrupted and all do match the source after downloading.

———

Заколбасило не менее 250 файлов от 115 игр, т.е. 116 EXE, 130 ZIP и 4 BIN файла по некоторым оценкам. К примеру: [overcooked_2](https://gog-games.com/game/overcooked_2), [8bit_hordes](https://gog-games.com/game/8bit_hordes), и т.п.. RAR заботится о том, что файлы не повреждены на шаре и соответствуют источнику, важная штука.

**Comment by MachineGunnur** [comment]
changed it while ago to scan each file category, patch, game extras. if no files are above 524288000b bytes in one. the raw files are uploaded.

i can make it for say, zippyshare where it will always be RAR'ed.

**Comment by MachineGunnur** [comment]
read: https://github.com/MachineGunnur/GOG-Games/issues/236#issuecomment-718141615

**Comment by fable-cable** [comment]
> i can make it for say, zippyshare where it will always be RAR'ed.

Better than nothing. Will be appreciated.

———

Лучше так, чем никак. Хотя бы что-то.

**Comment by MachineGunnur** [comment]
will look into changing in next few days

**Comment by MachineGunnur** [comment]
zippyshare will always be rar'ed now. see: fallout classic: https://gog-games.com/game/fallout_classic
