### ISSUE TITLE
Fixing Game Thumbnail Images

### ISSUE THREAD

**Issue by MachineGunnur** [MachineGunnur/GOG-Games#242]
Some cover images for games are broken. See BIT.TRIP BEAT: https://gog-games.com/search/BIT.TRIP%20BEAT

Hunting: most broken images are 95% completely black with some of real cover  at the top

To fix:
- Find broken image (manual process yay)
- List game name
- List fixed image (can find under Deatils for the game on gogdb: https://www.gogdb.org/product/1460735408#details , then scroll down to **Logo image**) (only need the string at end no .jpg needed either, so **b6d70974b59df029524af449631a1d1b1997162ea4a6f48327c3b4134f5a58e3**)

**Comment by MachineGunnur** [comment]
Example:

Blackwood Crossing
8856c5ba02eb94138c62640399e55f15634af1a6535c31c62dbfdf5e0a04d8fa

**Comment by MachineGunnur** [comment]
If many people want to help, I can assign page ranges i.e. person 1 handles pages -50, person 2 pages 50-100

**Comment by MachineGunnur** [comment]
Conquests of the Longbow: The Legend of Robin Hood 
a6709d910111bb234e9835a84030739acc02231b6292c07e1174e662e32caeef

**Comment by MachineGunnur** [comment]
I did pages 1-20

**Comment by JohnStephenEvil** [comment]
Tomb Raider: The Angel of Darkness
7a85079e0613d576d09f59b05c05a337881123ffa792f2f10c6a8cd1cef4ffb3

**Comment by MachineGunnur** [comment]
only one i found too. thanks. closing

**Comment by fable-cable** [comment]
What did you mean broken? For the future, finding truly broken is never manual for JPG unless wanted. Autodownload all of 'em and then the `jpeginfo` package from almost any Debian repo can reliably check corrupted without watching.

———

Сломан чего? На будущее, найти реально углубленные JPG'и можно и без ручек. Загрузи все, а затем `jpeginfo` с Debian в помощь, он нормально проверяет на повреждения без всякой нервотрепки.

**Comment by MachineGunnur** [comment]
broken images on gog's CDN. fixed. was their problem, not ours.

**Comment by fable-cable** [comment]
Indeed, these days GOG CDN is truly a mess. For example, "[Metamorphosis](https://www.gogdb.org/product/2147483117#media)" has two same images. GOG should do a better job at checking integrity and removing duplicates, also it's better to begin using SHA-2 for EXEs too to be safer for. Only mitigating is left for now, not much to do.

———

Мда, на сегодня GOG CDN просто хаос. Смотри, две одинаковых изобры у "[Metamorphosis](https://www.gogdb.org/product/2147483117#media)". GOG обязан лучше работать над целостностью данных и удалением одинаковых, и лучше б начал юзать SHA-2 в EXE. Что ж, ничего не поделать, приходится выколбасываться.
