### ISSUE TITLE
Calc Free CRC32 Sums

### ISSUE THREAD

**Issue by ghost** [MachineGunnur/GOG-Games#243]
I remember a long time ago you wanted to add CRC32 for files on a page. I made [uncrc](https://tinyurl.com/zAwbH1Nr) (TAR.GZ, CRC32 of the archive is "4f93498b"): It allows to extract and display or save to a file its CRC32 RAR hashes of a directory or a file in order to be used elsewhere, like insert into HTMLs. No recalculation, it needs all RAR of an uploading process only.

**Comment by MachineGunnur** [comment]
Neat tool. 

Was probably think end up having sfv file for GOG raw files in rewrite.

**Comment by fable-cable** [comment]
Upgraded the script: Download TAR.GZ (Mirror). Any feedback is welcome, as well as criticism. Changes are:

Fixes
1. "--verbose" now works correctly
2. Saving by "-s [FILE]" no longer rejects to overwrite all existing files
3. Made Saving to don't touch existing GOG files and foreign TXT, rendering overwriting by an accident impossible
4. Added ability to make Saving readable from Windows
5. Providing Examples on Help to make the script less obscure

New Features
1. Make CRC32/MD5/SHA-1 or BLAKE2b/SHA-2/SHA-3 at once via "-c --unsafe"
2. Uploading files to PixelDrain (30 days)
3. Uploading files to The Web Archive (Forever, never expires) with optional shortening links for the latter

NOTICE
PixelDrain will limit uploads speeds of files when using direct links (.../api/file/...`) more than 10 times. The only way to avoid that is to use "`https://pixeldrain.com/u/${id}`" to generate views. The Web Archive links are all direct and never expire.

**Comment by fable-cable** [comment]
Updated the script. Download: [TAR.GZ](https://pixeldrain.com/u/iH6n4Uat) ([Mirror](https://tinyurl.com/yyz9b5sg))

Fixes
1. "--verbose" now works correctly
2. Saving by "-s [FILE]" no longer rejects to overwrite existing 
3. Saving won't touch existing GOG files and foreign TXTs who don't look like an SFV, making rewriting by an accident impossible
4. Added ability to make Saving readable from Windows
5. Providing Examples on Help to make the script less obscure to use

New
1. Make weak CRC32/MD5/SHA-1 or strong BLAKE2b/SHA-2/SHA-3 at once via "-c --unsafe" for the 1st or "-c" for the 2nd
2. Uploading files in a directory to PixelDrain (30 days), optionally retry forever
3. Uploading files to The Web Archive with optional shortening links for  (Never Expires) 

Notice
PixelDrain will limit upload speeds of files when using direct links (`.../api/file/...`) more than 10 times. The only way to avoid that is to use "`https://pixeldrain.com/u/${id}`" to generate views. The Web Archive links are all direct and have no limit by date.

———

Скрипт обновился. Загрузка нового: [TAR.GZ](https://pixeldrain.com/u/iH6n4Uat) ([Зеркало](https://tinyurl.com/yyz9b5sg)). Только английская версия - советую читать список изменений выше. В основном исправлены мелочи и добавлены 2 фишки: загрузка файлов в интернет на PixelDrain; создание 3 хэшей за раз.

**Comment by fable-cable** [comment]
Sorry, "Close" and "Comment" are too cloose on a touch-screen. It was not intended, I'm writing from a phone with a small screen. Hope the updated script version would be helpful, nevertheless.

———

Простите, "закрыть" и "закомментить" расположены очень уж близко на экране.  Нажато непредвиденно, с просони. Надеюсь хотя бы новая версия скрипта будет полезна.

**Comment by fable-cable** [comment]
The main post updated. The script was simplified, polished:
1. Only needs "unrar" and (optional) "unix2dos," nothing more;
2. No troubling for edits "self checks," please use BTRFS/ZFS instead;
3. Allows both a folder and file(s), not folder only;
4. No require all RAR present, i.g. can work with half;
5. Less options, only: --tag, -s, -w, -q
6. Safe Saving speeded up and improved;
7. No examples in Help, it's simple;
8. No Russian, it's not used as seen nor required;
9. Uploading or making hashes was removed.

P.S. This is an info post, will be deleted after a day or two. Have a nice day!

**Comment by fable-cable** [comment]
"--save" and files with 2 spaces fixed. Don't do? Skip me.
1. "--save" didn't work correctly and was saving to the "save" file. Not critical, other code won't allow to accidentally touch not originally script-made file. Users tend to use short option, it couldn't be a problem.
2. Filenames with two spaces were not pricessed. Not related to GOG. Not a single GOG file has two spaces in the name, looking at the site. The worst can happen is a checksum won't be print because the checking code won't accept it.

My apologies for a late update and a notification in eMails, I sent the script two days ago to a friend and they said it is generally OK and promised to test it, it wasn't fast, finding these two tiny bugs I missed after my initial testings against my downloads. It shows importance of testing by a 3rd party and that no check is unnecessary and can help in this cases.
