### ISSUE TITLE
Fallout New Vegas .bin file corrupted

### ISSUE THREAD

**Issue by fallenveil** [MachineGunnur/GOG-Games#248]
I think the .bin file no. 1 is corrupted. I tried re-installing and using 7-zip but nothing works,idk if i could even reach out here because it may be misplaced but i just had to reach out in any way i can. I hope you fix this!!! Thanks :)

**Comment by MachineGunnur** [comment]
i have download the game from zippy and extracted fine AND passed GOG integrity check. closing. issue on your end.

**Comment by fable-cable** [comment]
Confirm no errors, redownloaded and checked via scripts by using MD5 from the EXE, allrighty. The 1st BIN is in the 8 to 16 parts. Your CRC32 is: 67C0D144. Make no mistake, most likely 7-zip just silently unpacked with an error, please run a RAR integrity check. Another possibility is the drive, see if S.M.A.R.T. is odd. Either way, hope you'll find what makes it fail.

———

Подтверждаю отсутствие - повторная загрузка и проверка с помощью скриптов с  MD5 из EXE - все норм. Первый BIN - 8-16 части RAR. Его CRC32: 67C0D144. Думаю, что 7-zip втихую распаковал с косяками, запусти-ка лучше проверку целостности RAR. Другая возможность - диск, посмотри-ка S.M.A.R.T. в норме ли. В любом случае, надеюсь, что найдешь причину ошибки.
