### ISSUE TITLE
PixelDrain testing

### ISSUE THREAD

**Issue by fable-cable** [MachineGunnur/GOG-Games#249]
"[Divinity: Original Sin 2](https://gog-games.com/game/divinity_original_sin_2)" mishandles 82 links (84.69%) for PixelDrain; "[AI War 2](https://gog-games.com/game/ai_war_2)" for half of; so on for many of them, making it useless on its own. It'll be appreciated if do the same policy of "upload until success." Currently the process probably does not seem to do, looking at such huge numbers. Maybe simpler to not use if makes issues.

———

"[Divinity: Original Sin 2](https://gog-games.com/game/divinity_original_sin_2)", убиты 82 ссылки (84,69%) PixelDrain; "[AI War 2](https://gog-games.com/game/ai_war_2)" не имеет половины; также к остальным перезалитым, что превращает их в нечто бессмысленное. Будет отлично, если применять ту же политику "не сдаваться до победы", как и к другим. На сейчас, похоже, что-то идет не так.  Наверное лучше вообще не использовать, если создает проблемы.

**Comment by MachineGunnur** [comment]
Testing PixelDrain. It's A WIP so please don't nitpick it. PixelDrain has HTTP Transient Error after completing uploads sometime and it retries over and over wasting bandwidth until it finally outputs upload links. 

TLDR PD not viable from testing.

**Comment by fable-cable** [comment]
Understand. Sorry, I didn't see the full picture. Yes, the service should fix that unpredictable bug then. If it makes wasting traffic that much, no way, better to cut it than to have none left. Such a shame it has the bug, really.

Better to relate on what is proven to work. Thanks for trying, will hope it can fix someday.

———

Понятно. Извиняюсь, не видно было полной картины. Да, тогда должны исправить эту хаотичную ошибку. Если приводит к прожиганию траффика, то не ладно, лучше уж вырубить, чем остаться без ничего. Жаль, что такие ошибки имеются.

Лучше иметь дело с тем, что нлрм. Благодарю за попытку, надеюсь, что потом исправят.

**Comment by MachineGunnur** [comment]
It's OK, rather annoyed, PixelDrain is good hoster!!~ Hopefully dev can work with us to de-bug, it's on their end. Happens tons on big uploads i.e. Divinity.

**Comment by MachineGunnur** [comment]
I am looking at other file hosters to direct upload too and cut out multiup.org, too. Was thinking about 1fichier, they allow full speed on files every 60 minutes. Would be great to compress games into one RAR and upload to them. Be great for 60GB+ games one click, one download.

**Comment by MachineGunnur** [comment]
I think for PixelDrain could in mean time, have a check if game is to large, it won't upload to Pixel, i.e. if under 20GB fine to upload, if not, don't

**Comment by fable-cable** [comment]
Agree on PixelDrain and on searching but let me make a point. 1fichier is not bad but as the history tells and our wise Russian proverb, "1 old friend is better than 2 new." Fine to be as an addition and interchangeable, so if a few links on either fall, can get from others. Making a single huge RAR will make it not possible.

Additionally a single RAR may badly impact users with bad Internet connections, slow or with traffic limits, which are many. If at downloading the file got corrupted, they will need to redownload the entire thing again and pray for no errors instead of just a small unlucky part. I think the current is good enough.

I understand the intention, it comes from the idea of having a great Internet connection, amazing. But the reality is: Most don't. Honestly, I won't be affected by this with my 1 Gbps and a nice ISP with a good routing table, not everyone has it, only a minority. GOG is played offline, many people of that kind don't have a great connection.

———

Соглашусь с PixelDrain и поиском, но позвольте высказаться по-свойски. 1fichier - это прекрасно, однако, как говорит история и мудрая пословица, "старый друг лучше, новых двух". Отлично в качестве дополнения, спору нет, и взаимозаменяемо лучше, чтобы если несколько ссылок упало на одном, можно с других. А вот создание одного огромного RAR сделает данное преимущество нереальным.

Кроме того, единый RAR может ужастно сказаться на пользователях с плохим интернетом, медленным или ограниченым, их много. Если при загрузке поврежден, нужно будет повторно и молиться об отсутствии передряг, а не только с небольшой частью. Думаю, что сейчас и так годно 500 MB - торт.

Понимаю намерение, исходит из идеи отличного подключение, радостно за вас, что сказать. Но реальность такова, что большинство не имееи. Честно, меня не коснется с моим 1 Gbps, хорошим провайдером с нормальной таблицей маршрутизации, не могу сказать за других. В GOG играют в офлайне же, у многих людей такого плана нет отпадного интернета.

**Comment by MachineGunnur** [comment]
dev of PD got back with me. said most likely connecting to Germany server and that one is frequently at maximum capacity. Then gave subdomain of server closer to ours. will try.

**Comment by fable-cable** [comment]
Nice, nice, truly nice. Good they're so responsive and wish well. Will see how goes, hope all go smoothly and great, like, no errors.

———

Прекрасно, что сказать. Хорошо, что 1 так отзывчиво и желаю вам всего наилучшего. Посмотрим, как оно пройдет с доменом.

**Comment by MachineGunnur** [comment]
Yes closing ...
