### ISSUE TITLE
Move PixelDrain Down, Copy Off / PixelDrain пониже, убрать копирку

### ISSUE THREAD

**Issue by fable-cable** [MachineGunnur/GOG-Games#253]
I suspect that JDownloader users think, like, having PixelDrain above Zippyshare means "it is Supreme." The folks seem to copy the 1st often. JDownloader uses direct links and doing PixelDrain very wrong, no views, making itself Captcha. Moving PixelDrain below others may help that and enforce people to use only when others are unokay and not as primary, else it harms us and themselves as well.

In addition must be far more effective to simply disable the copy button on PixelDrain, it'll help.

———

Думается, пользователи JDownloader воображают, что PixelDrain над Zippyshare значит "оно круче". Они похоже не редко берут 1-х подвернувшихся. JDownloader косячно идет на прямые ссылки и без просмотров, откапчивая себя же. Помещение PixelDrain пониже может помочь вынудить идти тогда, когда надо, иначе вредят и нашим, и вашим.

Впрочем, круче просто вырубить злосчастную кнопку копирования на него.

**Comment by MachineGunnur** [comment]
Yes, the file hoster order will be re-ordered once ironed out and have stable.

**Comment by fable-cable** [comment]
Thank you.
