### ISSUE TITLE
Stop using JDownloader for PixelDrain / Не используйте JDownloader на PixelDrain

### ISSUE THREAD

**Issue by fable-cable** [MachineGunnur/GOG-Games#254]
The app dooms itself by Captcha, see below. Its devs didn't read the API mindfully. Folks, please force the devs to change it. Like, doing fake views before downloading a file, better with a page's referrer and cookies. In a meantime, don't use at while no fix, it makes issues to all.

"The rate limit will be enabled if a file has ten times more downloads than views," "When a file is rate limited the user will need to fill out a captcha in order to continue downloading the file," "Rate limiting has been added to prevent the spread of viruses and to stop direct linking," [PixelDrain](https://pixeldrain.com/api) said.

Might be wise to pin the issue here and warn users on GOG Games until the fix.

———

Прога гробит себя капчами, см. ниже. Разрабы не курили API и все через одно место. Народ, выпрямьте им руки, прошу. Например, пусть строчат "фальшсмотры" перед загрузкой, лучше с реферером страницы и куками. Пока не вправлено - в баню косопрогу.

"Ограничение скорости применяется, когда файл под 10 раз больше загрузок, чем просмотров", "Если она ограничена, пользователю надо будет выполнить капчу, чтобы продолжить," "Для предотвращения вирусов и выдачи прямых ссылкок," - [PixelDrain](https://pixeldrain.com/api).

Верятно, пока не исправят, разумно запинить здесь и на GOG Games.

**Comment by MachineGunnur** [comment]
Yea, not viable for large games in size. Dropping PD for MegaUp (wrong script now need to do long testing).

**Comment by fable-cable** [comment]
I highly approve the move. MegaUp even has a Bash [download script](https://github.com/JuniYadi/megaupnet) and it works like a charm. One can add `--head` and del `-o "${filename}"` to the last `curl` of the script to check if the filesize (`du -b`), its name and type are correct and all is good. Better safe than sorry.
