### ISSUE TITLE
> Because they are ignorant and don't care. There will never be Linux section.

### ISSUE THREAD

**Issue by edwardbas-pl** [MachineGunnur/GOG-Games#256]
It would be just nicer from you if you in your response to my issue instead only write Back just No, some justifications why you can't add Llinux support. I understand windows is most popular. And if whole project is on Github and open source you can just simply add option to support linux versions and someone (probably me when I would end my studies) would make some sort of your site but with linux games. I could study your code and try to commit changes to codebase or just fork it but at the moment i don't have time. Back to main topic if you would explain why you can't add linux support. It just would be nicer from your side. I very   appreciate your work.

**Comment by mozo78** [comment]
Windows is most popular only for desktop. Globaly Linux is the most popular OS - cars, supercomputers, cloud infrastructure, telecommunications, Internet, servers, NASA, CERN, SpaceX, IoT, Routers, SmrtTV's, Smartphones, etc - it's literally everywhere. But they are ignorant and don't know it.

**Comment by edwardbas-pl** [comment]
but we are talking about linux in context of gaming. and at this aspect linux is marginal os.  We can ask wherever its possible to ask for linux support but we can't demand it.

**Comment by mozo78** [comment]
It's marginal for no reason - it's just the users habits.

**Comment by edwardbas-pl** [comment]
that's true but we cannot force anyone. just convince.

**Comment by mozo78** [comment]
Yes but people like MachineGunnur just keeps the status quo and helps Microsoft this way to get even richer. It's stupid.

**Comment by edwardbas-pl** [comment]
And that is why we should convince people to at least try out linux and educate them. Not tell them the are stupid. Just give them alternative and ask people to support linux with projects.

**Comment by mozo78** [comment]
There's no chance, this is the reality - people are stupid.

**Comment by edwardbas-pl** [comment]
So let's educate them...

**Comment by Masamune3210** [comment]
If you seriously don't like it that much, don't use it. They do this for free, so they have the right to give as little or as much information as to their decisions as they want

**Comment by edwardbas-pl** [comment]
im not talking i don't like the project. i just asked about feature of project thet could be added. The owner has right to do everything what he want with project but good communication wit community is the key. He could be just a little bit nicer.

**Comment by fable-cable** [comment]
C'mon. The owner already does a lot, solo. It is very hard to manage all of this and it takes many TBs. Do you folks understand how much work and money this is? And the worsest part even on its own the collection size grows not slow, it concerns me.

The main issue to me personally is Linux executables are not signed, no way to verify. I trust only the store signatures. Another: May not work on a new distro version. Together, I understand why they don't, I could choose the same anyway.

Don't take me wrong, I use Linux, I like it. But will not ever consider to work on that or waste my space unless I can verify or be certain my new Debian will play it without dancing around my PC like I summon the Devil.

**Comment by edwardbas-pl** [comment]
I didn't say the owner does nothing. my complain is about his communication. It would be just nice of him not writing "No." witch in my opinion is kind of rude. Only if he add some justification why he can't do that request there wouldn't be this whole conversation. I understand your concerns about linux native installers. But let me ask. How many people even bother putting malware in linux binaries. sure there are some cases... but it aims in biger group of users, and native gaming on linux is no taht big.

**Comment by fable-cable** [comment]
https://github.com/MachineGunnur/GOG-Games/issues/18#issuecomment-502003410
> requires database restructure and a overhaul of uploading scripts and how data displayed on site.
> also limit of space on rented server where games are archived. also bandwidth limit too. more games = more $$$ monthly :(

https://github.com/MachineGunnur/GOG-Games/issues/56#issuecomment-515784577
> unless we get crazy donations and enough to also cover upgrade server disk space, no.

**Comment by MachineGunnur** [comment]
> It would be just nicer from you if you in your response to my issue instead only write Back just No, some justifications why you can't add Llinux support. I understand windows is most popular. And if whole project is on Github and open source you can just simply add option to support linux versions and someone (probably me when I would end my studies) would make some sort of your site but with linux games. I could study your code and try to commit changes to codebase or just fork it but at the moment i don't have time. Back to main topic if you would explain why you can't add linux support. It just would be nicer from your side. I very appreciate your work.

If you bother, you can search closed issues as Linux has been asked countless times: https://github.com/MachineGunnur/GOG-Games/issues?q=is%3Aissue+is%3Aclosed+linux

**Comment by edwardbas-pl** [comment]
I understand. And I'm sorry for startting this whole discussion

**Comment by fable-cable** [comment]
You know, they did not say "never," they say they need money. You will have Linux if the amount of donations will be sufficient, according to the words. They already upgraded the storage and only "get crazy donations" is left. Please don't loose hope. Or better yet, donate

**Comment by edwardbas-pl** [comment]
As soon  as I get a regular job I will donate. Unfortunately  at his moment i don't have any spare money.
