### ISSUE TITLE
Web server is sometimes unstable

### ISSUE THREAD

**Issue by fable-cable** [MachineGunnur/GOG-Games#257]
Error 521 has suddenly occured for about thirty minutes. Its [archived snapshot](https://archive.today/cllFH) available. Frankfurt, Paris, London, Adhburn, etc: None worked right. Not a problem with Cloudflare.

In some cases a game page loads but showed the 404 error. Later strangely showed "Could not establish a connection to MariaDB," then a few 521 and stabilized itself for so far. Will be good to investigate the cause and resolve it to never occur again

**Comment by fable-cable** [comment]
Showed "Could not establish a connection to MariaDB" a minute ago, then works so far. Okay.

**Comment by fable-cable** [comment]
No, still glitching. What is going on?

**Comment by MachineGunnur** [comment]
Yes was me wrecking  on the site, actually ))

**Comment by fable-cable** [comment]
I see. But couldn't be done on a test copy in VM? Good to know wasn't an unsupervised accident, however, thanks for letting know.
