### ISSUE TITLE
Not all games are zipped/rared

### ISSUE THREAD

**Issue by kevinj93** [MachineGunnur/GOG-Games#259]
Some games are uploaded as plain exe files, not zipped.

Example game:
Jet Lancer

**Comment by MachineGunnur** [comment]
yes, search issues next time: https://github.com/MachineGunnur/GOG-Games/issues/241 was intentinal.

everything is in rar archives now though.

**Comment by stringles** [comment]
No panic. See, new are processed well. Do you need it for integrity? Take a look at Connie's GOG [DAT](https://onedrive.live.com/?authkey=%21APgbl3v0s41kQUQ&id=201ECFA3DD196829%2121848&cid=201ECFA3DD196829)s, has almost all GOG checksums.

The files are basically TXT with CRC32, MD5 and SHA-1. Use as the last resort solution 'cause not official not fully match what GG has and can be outdated. Should work okay to recheck old: Better than to have nothing.
