### ISSUE TITLE
Corrupted file

### ISSUE THREAD

**Issue by jbrant143** [MachineGunnur/GOG-Games#263]
Dying Light: The Following – Enhanced Edition

game-dying.light.the.following.enhanced.edition-(42973).part37.rar

! D:\game-dying.light.the.following.enhanced.edition-(42973).part37.rar: Checksum error in setup_dying_light_the_following__enhanced_edition_1.33.1_(64bit)_(42304)-4.bin. The file is corrupt

**Comment by MachineGunnur** [comment]
Re-download the part? I downloaded game from MegaUp and tested with 7zip - all good.

**Comment by jbrant143** [comment]
Just downloaded it from both mega and zippy. Sadly the problem still persists. Ill just download another game :D

**Comment by stringles** [comment]
I'll investigate later, possibly. But from my own experience GOG Games never have had an issue with RAR itself.

**Comment by SilentMRG** [comment]
Perhaps the error has to do with the version of 7Zip you are using.

Version 19.00 (2019-02-21) of Windows 64-bit x64, works fine.

In particular, I never had any problems unzipping the games on the site. Everything works like a charm!
