### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Petyamester3343** [MachineGunnur/GOG-Games#265]
Hey

You're doing a pretty godlike job keeping the site alive. You're even faster than Free GOG PC Games! You're a good man, and we thank you.

I only want you to add the "CompatibleOSs" and/or a "SysReq" tab to those games if you insist.

**Comment by MachineGunnur** [comment]
you can click the **Cart icon** located at the end of  title after clicking on game card and go to GOG.com store which has more information. no interest in maintaining when you can get the info from on additional click.

**Comment by stringles** [comment]
Notice that "Serious Sam 4" (100% on Vulkan, tested by me) and (approximately) "Cyberpunk 2077" do run on Windows 7 despite everything.
