### ISSUE TITLE
how to update

### ISSUE THREAD

**Issue by pnoyboi916** [MachineGunnur/GOG-Games#266]
hey guys! new to all this. awesome site by the way. i couldn't find any information nor haven't received a response from an email, so with that said...if there is a game that has been recently updated...how do we update it? i know some include patches or hotfixes you can download separately, but what about ones that don't have that?

**Comment by Masamune3210** [comment]
download a patch if it exists, or downloaded updated install files if not. make sure the build number is higher than the one you already have and just install over the installed version

**Comment by pnoyboi916** [comment]
> download a patch if it exists, or downloaded updated install files if not. make sure the build number is higher than the one you already have and just install over the installed version

so pretty much download the same game/files again? im looking at smaller games that only have just one file and no patches to download.

**Comment by MachineGunnur** [comment]
no patch, re-download whole game & reinstall, unfortunate.

if you stay in touch with new games (large), sometimes patches, and can patch with small file. sub to RSS and see.

enjoy
