### ISSUE TITLE
Reporting single dead links

### ISSUE THREAD

**Issue by smiglo5** [MachineGunnur/GOG-Games#267]
Hey there!
Is there a chance of reporting single links being 404'd? There already couple of them on Cyberpunk release, sadly

**Comment by stringles** [comment]
I think they will reupload the entire thing

**Comment by MachineGunnur** [comment]
no, use mirrors. unless those are down too.

new upload coming to fix bin 6.

**Comment by stringles** [comment]
A fix is nice. Thanks!
