### ISSUE TITLE
cyberpunk-6.bin failed integrity check

### ISSUE THREAD

**Issue by confever** [MachineGunnur/GOG-Games#268]
Just wanna report that 
_setup_cyberpunk_2077_build_3214677change_4155897_(64bit)_(43299)-6.bin_ 
is failing integrity check on gog installer.
I tried downloading from uptobox and zippyshare. same results
Using jdownloader and winrar

Thanks.

**Comment by ajhix36** [comment]
Same, and I d/l from 1fichier.

**Comment by confever** [comment]
3rd tries from uploaded. same thing.

**Comment by smiglo5** [comment]
Same thing

**Comment by confever** [comment]
4th tries, download from tus. same thing 6.bin failed integrity error

**Comment by LasmiTebra** [comment]
Same thing happened with me I think that it must have been a problem when getting the files from gog.com.

**Comment by callmenemo491** [comment]
mega missing 4 links (209 rar's) used zippyshare to get the remainder 4...
ended up with same integrity check fail

**Comment by stringles** [comment]
The same

**Comment by confever** [comment]
so, just for additional info :
the file i try is from tus, uploaded, upto and zippy all of them 6.bin have an md5checker result of : EC25F658933BB0643E2EE74C332645D9

by searching, i got one from other sources, i just donload the 6.bin one, and got this md5checker result : 79E8EEAF8920ECE76BD2912E49DCEC8C
it passed the integrity check, and can install normally.

**Comment by snayto** [comment]
> so, just for additional info :
> the file i try is from tus, uploaded, upto and zippy all of them 6.bin have an md5checker result of : EC25F658933BB0643E2EE74C332645D9
> 
> by searching, i got one from other sources, i just donload the 6.bin one, and got this md5checker result : 79E8EEAF8920ECE76BD2912E49DCEC8C
> it passed the integrity check, and can install normally.

can i have the link please ?

**Comment by LasmiTebra** [comment]
I have a uncorrupt 6.bin file I have it on filepizza link will work for an hour or two until I close the page so gl to those who snag it 
https://file.pizza/download/ab9mauoe

**Comment by LasmiTebra** [comment]
> I have a uncorrupt 6.bin file I have it on filepizza link will work for an hour or two until I close the page so gl to those who snag it
> https://file.pizza/download/ab9mauoe

P.S. I bought the game on gog so the file is from there <3

**Comment by snayto** [comment]
> > I have a uncorrupt 6.bin file I have it on filepizza link will work for an hour or two until I close the page so gl to those who snag it
> > https://file.pizza/download/ab9mauoe
> 
> P.S. I bought the game on gog so the file is from there <3

The download won't start ':)

**Comment by LasmiTebra** [comment]
> > > I have a uncorrupt 6.bin file I have it on filepizza link will work for an hour or two until I close the page so gl to those who snag it
> > > https://file.pizza/download/ab9mauoe
> > 
> > 
> > P.S. I bought the game on gog so the file is from there <3
> 
> The download won't start ':)

I'm sorry then, cant spend the next 3 hours uploading to google drive wait a bit more its gonna get updated

**Comment by MaxMega12** [comment]
I have a 6.bin that works, uploading now.

**Comment by auxford** [comment]
> > so, just for additional info :
> > the file i try is from tus, uploaded, upto and zippy all of them 6.bin have an md5checker result of : EC25F658933BB0643E2EE74C332645D9
> > by searching, i got one from other sources, i just donload the 6.bin one, and got this md5checker result : 79E8EEAF8920ECE76BD2912E49DCEC8C
> > it passed the integrity check, and can install normally.
> 
> can i have the link please ?

As I tried, any sites, like 1773 or thepiratesbay or rarbg, that hold a GOG version of 2077 except this one, have the right 6.bin file, download that single file and replace then check with md5checker as he said, problem sovled.

**Comment by MaxMega12** [comment]
[GDrive](https://drive.google.com/file/d/1K7U49tW9GkxV4oJOSD16nh0Gvfs6mxwB/view?usp=sharing)

**Comment by MachineGunnur** [comment]
thanks, will push patch in 3 minutes or so :)

> [GDrive](https://drive.google.com/file/d/1K7U49tW9GkxV4oJOSD16nh0Gvfs6mxwB/view?usp=sharing)
> [Mediafire](http://www.mediafire.com/file/tk63yy4tvru3p03/setup_cyberpunk_2077_build_3214677change_4155897_(64bit)_(43299)-6.bin/file)

**Comment by MachineGunnur** [comment]
removed links everyone shared so github doesn't get dmca. thanks again

**Comment by stringles** [comment]
May I know why hasn't it been tested in advance? This is supposed to never happen at all because the tool to check on Linux was provided. It could be easier to all of us if the tool was mandatory for every game.

In case it was lost, below is a simple quickly written Bash version with no exceptions for old games and namings. It allows to check newer games and not make these kind of issues in the future. I use own versions of `strings` who isn't always installed and of `grep` who isn't needed in full force. 

License: Unlicense
Tested on: Debian 9, 10, Ubuntu 18, 20
Size: 137 lines, 2,231 bytes
Requires: osslsigncode, coreutils.
Usage: sigchk "${EXE}"
Download:
https://pixeldrain.com/u/3SkP81Vw

**Comment by stringles** [comment]
@MachineGunnur Beware, the URLs are absolutely not deleted. It makes me worry. Please delete in the "edited" history as well: By clickung on  all raws in "edited" except the last, then "Options" and "Delete revision from history." Thus all will be good.

**Comment by CRC-Mismatch** [comment]
Link for part 9 of the fix seems to not be available on ZippyShare

**Comment by MachineGunnur** [comment]
issue on zippy's end. file uploads but doesn't append on their end to server>? idk. use mirror.

**Comment by MachineGunnur** [comment]
> @MachineGunnur Beware, the URLs are absolutely not deleted. It makes me worry. Please delete in the "edited" history as well: By clickung on all raws in "edited" except the latest, then "Options" and "Delete revision from history." Thus all will be good.

oh yes, all gone now

**Comment by stringles** [comment]
Okay. Now you're safe, nice.

> Link for part 9 of the fix seems to not be available on ZippyShare, says the file does not exist on that server.

This is bad. I see uploads are done likely improperly. Haven't you said retries were infinite, why is it even a thing if [the words](https://github.com/MachineGunnur/GOG-Games/issues/251#issuecomment-737764986_) were the truth? I never expected it to suddenly emerge like that.

Obviously it shouldn't just simply upload but test the size and existence properly by [the Github Zippyshare script](https://github.com/ffluegel/zippyshare) (change the last `curl` to `--head`, no need to actually load a file). Could set it real and fix the error forever.

The same to this whole issue. The checking Linux script, performing absolutely the same as GOG's own check, was supplied in the past. The issue shouldn't be happening in the first place if checking was mandatory.

I know it isn't too fast nor the first version is perfect. You can improve if necessary. In regards to uploads, shall be checked for existence, this is easy. It'll save time and resources to all of us and make users more satisfied and potentially increase your donations.

**Comment by stringles** [comment]
> rip zippyshare.com 504. uploads paused until it comes back. 

Oh no. The site [said](https://archive.today/SRrwD) "Cyberpunk 2077" essentially "killed" Zippyshare's upload, I see. The game is indeed, popular. For years never saw anything like that. What the day!

> Link for part 9

> file uploads but doesn't append on their end to server>?

Don't you both worry. It has no errors on, absolutely.I tested the fix file right now, it exists, on my phone. The truth of the matter is the game is both big and, it seems, crazy popular, makes even giants like Zippyshare glitch.

So all the three thousand GOG games couldn't make it uneasy but 1: Impressive yet terrifying.
