### ISSUE TITLE
Uploading isn't Paused, Queue Unusually Slow

### ISSUE THREAD

**Issue by stringles** [MachineGunnur/GOG-Games#269]
Uploading isn't paused as said for on the site and it takes over 7 hours for two relatively small games ([before](https://web.archive.org/web/20201211061546/https://gog-games.com/queue), [now](https://web.archive.org/web/20201211134556/https://gog-games.com/queue)). Please shutdown Voting if it wasn't the intended behavior. In addition it could be great to do uploading in parallel to better utilize resources and not do one by one unless high speeds.

By my approximation, it may take over 2.5 days to upload what is in Queue now. I do not know why this is so horribly slow and hope there is a way to resolve the issue.

**Comment by MachineGunnur** [comment]
was paused...

**Comment by stringles** [comment]
Now it changed and see only "Baldur's Gate 3." Hopefully will pass fine. Alright.
