### ISSUE TITLE
Provide seperate archives for each .bin file

### ISSUE THREAD

**Issue by HurSirU** [MachineGunnur/GOG-Games#271]
I think if you could provide seperate archives and download links for each file, redownloading a single corrupt one would be much easier for users.
That way no one has to download like 100GB of Cyberpunk if after unpacking some of the files are corrupt.
Happened to me: downloaded cyberpunk, unpacked with 7z, 4 bin files were corrupt even though the downloaded .rars where "completed" in jdownloader. Since there's no real way of knowing which of the 200+ rar files were responsible, i had to redownload everything.
Providing individual downloads for each .bin would fix that issue.

**Comment by MachineGunnur** [comment]
you can test archive with 7zip. and it will tell you which rar was bad.

no that would be confusing.

**Comment by stringles** [comment]
I agree with the owner. There is no reason to make it all more complicated when the searched feature is already present.
