### ISSUE TITLE
Spiritfarer has issue when installing

### ISSUE THREAD

**Issue by abookbinder** [MachineGunnur/GOG-Games#273]
I've tried downloading separately from zippyshare and mega, and I always get an error of "the source file is corrupted." I've successfully downloaded other things today from gog-games and so I don't think it's an extraction issue or a download issue.

**Comment by MachineGunnur** [comment]
no issues here. dl from megaup.

issue on your end

**Comment by MachineGunnur** [comment]
SFV attached: https://www44.zippyshare.com/v/vcvYVNsx/file.html

**Comment by MachineGunnur** [comment]
yes i see.

**Comment by MachineGunnur** [comment]
fixed
