### ISSUE TITLE
Inmost just re-uploaded old version as a new version 

### ISSUE THREAD

**Issue by ajhix36** [MachineGunnur/GOG-Games#274]
New version is 1.04, but the website just uploaded 1.03 as the "updated" version.

**Comment by stringles** [comment]
You are correct and wrong. The site is used to have 1.0.2, now is 1.03, not an old version [relative to itself](http://web.archive.org/web/20201207064646/https://gog-games.com/game/iinmost as I kind of feared. However, a rival forum site whom the owner knows has updated to 1.04 by Catastic. Thankfully the owner updates right now, you can count it solved and all fine.

**Comment by stringles** [comment]
[Done](https://web.archive.org/web/20201215074657/https://gog-games.com/game/inmost).
