### ISSUE TITLE
Wasteland 3 - new update

### ISSUE THREAD

**Issue by momala454** [MachineGunnur/GOG-Games#276]
Hi,
There have been an update that's not yet on gog games.
Please add it if possible.

Do you have a script that auto upload updates for games you own ?
I saw that you don't have all games so I am aware that it's not possible to auto update all games.

Thank you

**Comment by MachineGunnur** [comment]
we know. patience there were over 300GB of updates last 3 days.

**Comment by momala454** [comment]
ah, sorry, i checked the queue and didn't found it there
thanks
