### ISSUE TITLE
Happy Holidays!!!

### ISSUE THREAD

**Issue by SilentMRG** [MachineGunnur/GOG-Games#278]
![images](https://user-images.githubusercontent.com/62117728/103041570-8886bb80-4555-11eb-8d9c-e63074122e5b.jpeg)

Psalm 23

1 The Lord is my shepherd, I will lack nothing.

2 Lying down makes me in green pastures, guide me gently to calm waters.

3 Cool my soul; guide me on the paths of justice, for the sake of your name.

4 Even if I walked through the valley of the shadow of death, I would fear no harm, because you are with me; your rod and your staff comfort me.

5 You prepare a table before me in the presence of my enemies, you anoint my head with oil, my cup overflows.

6 Certainly, goodness and mercy will follow me every day of my life; and I will dwell in the house of the Lord for long days.

And Merry Christmas to everyone!!! =D

**Comment by SilentMRG** [comment]
https://youtu.be/VNjCNgGlRWc

**Comment by MachineGunnur** [comment]
and happy 2021 soon.
