### ISSUE TITLE
Implement Proper Data Verification before RAR

### ISSUE THREAD

**Issue by stringles** [MachineGunnur/GOG-Games#282]
You can [download](https://github.com/guental/sigchk/archive/main.zip) from Github. Allowed filetypes: 7Z, EXE (BIN), GZ, JPG, PNG, XZ, ZSTD, RAR and ZIP. 27 times faster* in verification: Where `innoextract` spends 27 days, `sigchk` needs one for a far more delicate testing. 
\* _Tested on "Toca Race Driver 3:" Terrible 402 seconds for InnoExtract, 15 for Signature Check, both include BINs_

**EXE**
1. Test integrity of a setup file;
2. Extract checksums for BIN tests from the file;
3. Test the BINs and warn on missing or corrupt.

Never allows any corruption to pass unseen. Does not require buggy `wine` or flawed `innoextract`. Not dependent on an EXE's InnoSetup version. The same as to run Windows' "Digital Signature Details" and then GOG's "Check file integrity before installation." Any changed bit will be noticed instantly and then output "FAILED" and exit with Exit Code "1."

Installers without a signature will always rise an error and not extracting checksums for BINs because the latter could be invalid and shall not be trusted. Verification of non-GOG BIN files or BINs alone is not supported, only with EXE. It may not notice a missing BIN if the corresponding signed EXE file has no built-in checksum: Fortunately only very old games do it, new don't.

To avoid troubles with legacy stuff, it includes built-in exceptions based on an independent checksum database for some old games like "Mafia III" or "Toca Race Driver 3" where GOG has not provided MD5 for BINs and/or has no signed executables.The process has been tested and will work on more than 2,839 GOG games.

**ZIP**
1. Test ZIP offsets;
2. Test ZIP contents.

The offset verification would miss non-critical corruption of ZIP itself. Eternal data shall be extractable and valid, preventing random data corruption.

**JPG**
JPG actually doesn't have a checksum. The way how testing works is it checks for irregularity. There is a small chance it can miss something. PNG is far better and has a built-in checksum.

**Others**
It runs default tests by a filetype's native application.

**Example Usage**

`find . -type f -iname '*.exe' -execdir sigchk '{}' \;`

**Example Response**

```
setup_toca_3.exe: OK
setup_toca_3-1.bin: OK
setup_toca_3-2.bin: OK
setup_toca_3-3.bin: OK
setup_mafia_iii_1.090.0_(19569).exe: OK
setup_mafia_iii_1.090.0_(19569)-1.bin: OK
setup_mafia_iii_1.090.0_(19569)-2.bin: OK
setup_mafia_iii_1.090.0_(19569)-3.bin: OK
setup_mafia_iii_1.090.0_(19569)-4.bin: OK
setup_mafia_iii_1.090.0_(19569)-5.bin: OK
setup_mafia_iii_1.090.0_(19569)-6.bin: OK
setup_mafia_iii_1.090.0_(19569)-7.bin: OK
setup_mafia_iii_1.090.0_(19569)-8.bin: OK
setup_mafia_iii_1.090.0_(19569)-9.bin: OK
setup_mafia_iii_1.090.0_(19569)-10.bin: OK
setup_mafia_iii_1.090.0_(19569)-11.bin: OK
setup_mafia_iii_1.090.0_(19569)-12.bin: OK
setup_mafia_iii_1.090.0_(19569)-13.bin: OK
```

**Uses Packages**
`p7zip-full tar gzip xz-utils unrar zip unzip osslsigncode coreutils jpeginfo pngcheck`

**Comment by MachineGunnur** [comment]
innoextract is pretty slow. 

what about raw PDF files? i.e. horizon:ZD?

**Comment by MachineGunnur** [comment]
nvm works on pdf

**Comment by stringles** [comment]
A great question. GOG has 8 PDFs outside of ZIP in total.

It won't be a big deal to add an exception. Even though it will be not like other checking ways, not capable to do by itself: It will need constant manual care with getting checksums from [Connie](https://onedrive.live.com/?authkey=%21APgbl3v0s41kQUQ&id=201ECFA3DD196829%2121848&cid=201ECFA3DD196829) who is not fast on updates, their DATs are stuck on November. I use these SHA-1/MD5 when for old games when no inside checksum available, obviously there is no other way.

I parsed their 5 DATs and extacted checksums for all, it can be used with `sha1sum --ignore-missing -c`. The "Manual.pdf" is for "MissionForce: CyberStorm," it is said to be in the installed game directory, thus meaningless to provide separately.
```
331e0d62e010ce5b9a56d303f5d6c572a3a651df  blade_runner_conceptual_art.pdf
52457bfaa14ed6210023f5dc599649d9e8f258fd  blade_runner_manual_french.pdf
efcfcb8392ad7f0f435e3117273d6ae704b772de  blade_runner_manual_german.pdf
5a525da567018d1e92dcda1c592cce62830286ce  blade_runner_manual_polish.pdf
aa356cf6a307d45e4c7a1b5c0546da73911da4f2  emperor_of_the_fading_suns_manual.pdf
7a412d43f5c8eacbf4cc4086db8e3e2c14cab275  eternam_manual.pdf
b630870d16e5d37b48b347b031b897c64d433f1f  Manual.pdf
c72b1e7231adc324e6e8c2de2ceb79d9ef55f3e7  warhammer_40000_da_orks_manual.pdf

```

**Comment by stringles** [comment]
Meanwhile, the script was updated and added optional verification for AVI, MP4 and MKV. It as reliable as testing JPG, it checks for irregularities and is based on `ffmpeg`.

**Comment by MachineGunnur** [comment]
Thanks, using this now instead of innoextract, way faster.

**Comment by stringles** [comment]
You're Welcome! Good to know it fits the bill.

**Comment by stringles** [comment]
Two major changes: Made it parallel; Included all hashes.

Checking faster, from 2 to 8 simultaneous reads depending on the number of cores. The only case when it disables `parallel` is when `"` and `'` are in the name. To enable, one needs `moreutils`. Still prefering EXEs' own hashes 1st but if missing, the huge integrated 3rd party database (14,524 EXEs with BINs) shall cover all, absolutely.

**Comment by stringles** [comment]
My apologies, it has a tiny mistake with "return 1" and "exit_code=1" in not a correct order, leading to not exiting with "1" at the end but still saying "FAILED" to some new formats on an error. Fixed. Otherwise the version works as expected. I commonly use it on `find` and then read logs, haven't noticed, my usecases are fairly limited, mostly checking EXEs.

`parallel` has been added, from 2 to 8 files simultaneously, depending on a PC's CPU. Noticed the Exit Code error when working with it and not always getting the correct code on some "junk" files even though the manual said explicitly, which made me pay attention. I included all Connie GOG hashes to be sure no corner cases are missing.

It bugs me that errors like this occur and may go unnoticed for a long time. Generally a good idea to not simply get as is but to review and rewrite if you don't like some. Feel free to do. It is written in Bash for this very reason: To be easy to fix, edit or understand. It was only made to avoid `wine` or `innoextract` actually.

The exit code for EXEs and BINs was always correctly done by the way, so zero worries on that. I just thought this is critical to know. As a replacement to the function of InnoExtract, it performs fine in any version.

**Comment by SilentMRG** [comment]
> You can [download](https://github.com/guental/sigchk/archive/main.zip) from Github. Allowed filetypes: 7Z, EXE (BIN), GZ, JPG, PNG, XZ, ZSTD, RAR and ZIP. 27 times faster* in verification: Where `innoextract` spends 27 days, `sigchk` needs one for a far more delicate testing.
> * _Tested on "Toca Race Driver 3:" Terrible 402 seconds for InnoExtract, 15 for Signature Check, both include BINs_
> 
> **EXE**
> 
> 1. Test integrity of a setup file;
> 2. Extract checksums for BIN tests from the file;
> 3. Test the BINs and warn on missing or corrupt.
> 
> Never allows any corruption to pass unseen. Does not require buggy `wine` or flawed `innoextract`. Not dependent on an EXE's InnoSetup version. The same as to run Windows' "Digital Signature Details" and then GOG's "Check file integrity before installation." Any changed bit will be noticed instantly and then output "FAILED" and exit with Exit Code "1."
> 
> Installers without a signature will always rise an error and not extracting checksums for BINs because the latter could be invalid and shall not be trusted. Verification of non-GOG BIN files or BINs alone is not supported, only with EXE. It may not notice a missing BIN if the corresponding signed EXE file has no built-in checksum: Fortunately only very old games do it, new don't.
> 
> To avoid troubles with legacy stuff, it includes built-in exceptions based on an independent checksum database for some old games like "Mafia III" or "Toca Race Driver 3" where GOG has not provided MD5 for BINs and/or has no signed executables.The process has been tested and will work on more than 2,839 GOG games.
> 
> **ZIP**
> 
> 1. Test ZIP offsets;
> 2. Test ZIP contents.
> 
> The offset verification would miss non-critical corruption of ZIP itself. Eternal data shall be extractable and valid, preventing random data corruption.
> 
> **JPG**
> JPG actually doesn't have a checksum. The way how testing works is it checks for irregularity. There is a small chance it can miss something. PNG is far better and has a built-in checksum.
> 
> **Others**
> It runs default tests by a filetype's native application.
> 
> **Example Usage**
> 
> `find . -type f -iname '*.exe' -execdir sigchk '{}' \;`
> 
> **Example Response**
> 
> ```
> setup_toca_3.exe: OK
> setup_toca_3-1.bin: OK
> setup_toca_3-2.bin: OK
> setup_toca_3-3.bin: OK
> setup_mafia_iii_1.090.0_(19569).exe: OK
> setup_mafia_iii_1.090.0_(19569)-1.bin: OK
> setup_mafia_iii_1.090.0_(19569)-2.bin: OK
> setup_mafia_iii_1.090.0_(19569)-3.bin: OK
> setup_mafia_iii_1.090.0_(19569)-4.bin: OK
> setup_mafia_iii_1.090.0_(19569)-5.bin: OK
> setup_mafia_iii_1.090.0_(19569)-6.bin: OK
> setup_mafia_iii_1.090.0_(19569)-7.bin: OK
> setup_mafia_iii_1.090.0_(19569)-8.bin: OK
> setup_mafia_iii_1.090.0_(19569)-9.bin: OK
> setup_mafia_iii_1.090.0_(19569)-10.bin: OK
> setup_mafia_iii_1.090.0_(19569)-11.bin: OK
> setup_mafia_iii_1.090.0_(19569)-12.bin: OK
> setup_mafia_iii_1.090.0_(19569)-13.bin: OK
> ```
> 
> **Uses Packages**
> `p7zip-full tar gzip xz-utils unrar zip unzip osslsigncode coreutils jpeginfo pngcheck`

Hey, can you please, check the integrity of the files: Overlord + Raising Hell and Overlord II?

I read on the GOG forum that the game files were corrupted! According to GOG support, they have already corrected them, however, I cannot see if the website's files are corrected or not.

I could download them and check, but
my internet connection sucks.

Thank you for your help!

**Comment by stringles** [comment]
Okay. Most likely it has a do with Windows 10. I use 7, all works. The installer and the game on a system it was made for are not to blame. Nobody made it for Windows 10.

I checked by my `triosum` (512-bit checksums) from years ago to be sure that my disk haven't corrupted a single bit, then `sigchk` with deleted exceptions just in case. The file's data match what is in Connie's database and what the signed EXE has. As a reference, below are BLAKE2b, SHA-2 and SHA-3 hashes.
```
BLAKE2b (setup_overlord_pack_2.0.1.10-1.bin) = 8911f6a72a0e2493d88718cc1b4f5d7dfe6f92f5d410dfa4bd08ce216ca6195b64261c15f778aae3fd8b5680fcbd293f33a31375f0af3c8f3e62af46e4e81df2
SHA512 (setup_overlord_pack_2.0.1.10-1.bin) = 548a9286309806ed5d55f2d7c8840918542c264506ab32ea0f93abe5bcfe143e5d2455f038c8c7ede7283245b246a95157c4b76c6d96790d5b31f3a0742ba405
SHA3-512 (setup_overlord_pack_2.0.1.10-1.bin) = 719f663ed180db48acc9a8c4d614ffd060424e5ab6e62b7cc47ae3a2eb1c0499f96e4439b2910ae3b7f9db0d044b6127e0e6b6eafbe3b200339001fab1d92c99
BLAKE2b (setup_overlord_pack_2.0.1.10-2.bin) = 62d494b68cd2493785f896ef55f411e993458998f59cf2fce1b742e0915cb06476a1b24f4377a3fdfefb8b09289ffef9ec0a92052f694354771ebda1693c0f5b
SHA512 (setup_overlord_pack_2.0.1.10-2.bin) = 4c653f97b15f16bad56f1eb5c31a21e289613d161a5b6559a1055602a94ac72fd573828e2331d3cc1a959280f326e2d5ea5cb10796ee5cfa4512fbf92ac2ec84
SHA3-512 (setup_overlord_pack_2.0.1.10-2.bin) = db2e22528bf6d4fa3dde48fef7e7db63c8b8a27e6321130396a1413223f0022e32c310915b189063a920ad519afc758e44c49b5c1194c001349c2d30698f9547
BLAKE2b (setup_overlord_pack_2.0.1.10.exe) = 51a021904d9231af26e6069f61a7cb24a5aee77f37260dd599037fed82962563bc7c6c5c7f124ec008bc505bb82c81fae191d116a02846634a815a75f6db2c94
SHA512 (setup_overlord_pack_2.0.1.10.exe) = 26ba99a358db83e4911f159b2f9ae5427acc9a211cf5cf20434fb653b472b6243f249850303ef4fcd543bb1e71e4c582192fc1ed148126a683e9aa51801ce8e5
SHA3-512 (setup_overlord_pack_2.0.1.10.exe) = 9792c39e96d4d6cbef61da8e47a1d26c225c9f6de748a7677f894449c77894aaf9e1dcd1cbda8eae9e383f5bd21907c02ba91b743cb111df5c3dd12dcb973b0f
BLAKE2b (setup_overlord_ii_1.0_(22015)-1.bin) = af02750fe8bd0961e0e1f6f5d1370ffeae043baa8abaa6ae2eab440528848ff96431ab881612bc5bbc06a04af96eab4fcf9f6ce371e2284006ee31287f65c797
SHA512 (setup_overlord_ii_1.0_(22015)-1.bin) = b720d0ef3291b2ed68c9289643ddadb6da7aeff309702b8b1c0abc3dad742e53f29013a788656a5b5071c691f5ed01717c4db98e25aa0c563aec9f32538a4dfe
SHA3-512 (setup_overlord_ii_1.0_(22015)-1.bin) = 14b2aac0c36c8852a28db601f590be211d6c44bf24c95ce3dff42313637bfe2ed55959cae40cbd6b535de02704af72bc4fa0ad747ab1e2c6631a1e7468f8e8f4
BLAKE2b (setup_overlord_ii_1.0_(22015).exe) = 7d6f0d0d8fdc344dc1f790ad4eb53bc22fb262265d2a6d05b0ba68dd843f6446345c26772dcb7bd60609c1d4df767c9a72339d627364226f81c32347066b8d98
SHA512 (setup_overlord_ii_1.0_(22015).exe) = 7506e854bbdd6c1984e59f8664063efba59eae29b203ff79713432774d56be518e5c40ef3ddd5be3e4f24cd30e4081b6579fc51740942669964d8fc3963a1a95
SHA3-512 (setup_overlord_ii_1.0_(22015).exe) = e51869a36a329fa69857c05f19ae175f48f13137f7d9a23197ec9d658994de9a76157c11dfbe122acf7c7e438905db503488911e0a0beef0bf66388dcd6746a4
```

**Comment by stringles** [comment]
I checked GOGdb, there are no new installers. I suspect GOG has issues with the way how GOG Galaxy downloads. The offline installers are a bit another story. The Overlord 2 installer is after the issue has been fixed, 2020-07-17 1:49 PM (UTC). On the matter of the 1st game, it is solely a  Windows 10 problem.

**Comment by SilentMRG** [comment]
> I checked GOGdb, there are no new installers. I suspect GOG has issues with the way how GOG Galaxy downloads. The offline installers are a bit another story. The Overlord 2 installer is after the issue has been fixed, 2020-07-17 1:49 PM (UTC). On the matter of the 1st game, it is solely a Windows 10 problem.

I sincerely thank you for your help!

**Comment by SilentMRG** [comment]
> The Overlord 2 installer is after the issue has been fixed, 2020-07-17 1:49 PM (UTC).

I think you meant 07/17/2018 at 8: and little in the morning. Because in Overlord II this is more or less the date and time of the .bin file. If I'm wrong... Sorry for the inconvenience.

**Comment by stringles** [comment]
I appreciate pointing out the mistake. Thank you, really. You can confirm below.

![overlord_ii](https://user-images.githubusercontent.com/75202086/103433999-9cd05580-4bf2-11eb-9737-89cf751aa99d.png)

**Comment by stringles** [comment]
I `diff`ed what is uploaded on Github against offline just because I suspected there can be a mistake in one of 8 repos. Found it matches except the 1st line of the `sigchk` file has `pngcheck` for some reason. Removed. Other lines match.  It did not affect `bash -- sigchk -- [FILE]` critically and below worked. Sorry, my bad.

I will take a break for now, writing many scripts affects my attention. It can be related to kind of burn out on the stuf. If I find something wrong again in upcoming months, fix, yes. Please if somebody finds a mistake in the files or in my statements, fear not to challenge the wrong. For instance, write here, publish a fix or open an Issue on the repo. However, I may be slow to respond. The point is to make an issue known. 

I hope the future improvements or fixes of missed typos will be done or taken care of by the owner of the repo I comment now. The main advantage of this format is that if GOG suddenly breaks stuff and changes installers, it'll be quick to adapt `sigchk`. Adding new functions for more formats is quick and easy too. Hope the future will be good.

**Comment by SilentMRG** [comment]
> I appreciate pointing out the mistake. Thank you, really. You can confirm below.
> 
> ![overlord_ii](https://user-images.githubusercontent.com/75202086/103433999-9cd05580-4bf2-11eb-9737-89cf751aa99d.png)

No need to thank ... I am the one who thanks you for all your help! Well, I will try to install both games on Saturday, and if they are installed correctly, I will not post anything here, if an error occurs I will post the error. I suspect that, perhaps, Overlord II has an error during the installation ... However, I hope to be 100% mistaken. Anyway, that's all.

**Comment by stringles** [comment]
The break ended. Cannot help but notice, looking at the recent issue with "Stellar Tactics," a definitely not related cause, that some alternative version is used here. As such, time to move on. 

I looked closely and recently found [`signify`](https://github.com/ralphje/signify) for verifying PE signatures and some others alike. Most verification apparently can be done in Python instead of Bash. EXE verification was the part why it wasn't from the start, I couldn't find the package. Bash was a "temporary" choice but it stuck, as it often happens. It works but may work better.

A rewrite of the Bash version on the base of an universal template to eliminate some minor yet present issues is planned. The dev branch with a stricter Issuer Verification process exists for now: Not in the main branch yet, no sure to have all the certificates, getting takes the longest time.

The app likely will be simple and do only EXE/BIN & ZIP. Of course before that the new version shall be tested, will take a while.
