### ISSUE TITLE
Wing Commander 4

### ISSUE THREAD

**Issue by TechXero** [MachineGunnur/GOG-Games#284]
Hello,

Trying to vote for re-upload on https://gog-games.com/game/wing_commander_4_the_price_of_freedom Not allowing me. Kindly fix and re-up.

Thanks

**Comment by SilentMRG** [comment]
Already in the queue and possibly already online. Take a look...

**Comment by TechXero** [comment]
Yep just saw thanks for quick fix.. 100+ games in my download Q.. Love that site don't ever go down EVER !
