### ISSUE TITLE
More ZIP Goodies from GOG Media

### ISSUE THREAD

**Issue by stringles** [MachineGunnur/GOG-Games#286]
Is it a silly idea to parse links from an URL and download all official screenshots and videos of a game, verify integrity and to pack as i.g. "gog_games_${slug}_bonus.zip" or so? Writing a script for that (gog-games, api.gog, gog and gogdb are supported) but it has some issues, takes time. It'll require `wget`, `youtube-dl` from PIP. Just wondering what you think of. It is, honestly, unnecessary.

**Comment by MachineGunnur** [comment]
no interest if being honest ))

**Comment by stringles** [comment]
No problem, you do you.

**Comment by stringles** [comment]
To any who is interested in more, [`gog-dl`](https://github.com/guental/gog-dl).

It parses a URL for a game, gets its logo, screenshots and videos, downloads and checks, then optionally packs into ZIP. Found a way to avoid ne necessary need for `youtube-dl` for videos because built-in [`invidious-dl`](https://github.com/guental/invidious-dl) to get YouTube direct links and MP4. It can use Extended Attributes if available.

Please don't add it to GOG Games as decided, be on the way you are, you're good. These are available publicly anyway and only may waste your precious time and space. But think some people and completionist-like collectors could find some use for it: Scrabbing manually makes no sense for a big collection and too tiring.

Never bad to have more Official Goodies in my opinion.

***Example Usage***

gog-dl -b gog_games -w ~/Downloads/ -o ~/Documents/ -z -- https://gog-games.com/game/z https://gog.com/game/zed https://www.gogdb.org/product/1282350952#changelog https://api.gog.com/products/2106942030?expand=downloads,expanded_dlcs,description,screenshots,videos,related_products,changelog

***Example Output***
```
[gog-games] https://gog-games.com/game/z: Downloading webpage
[gogdb] https://www.gogdb.org/product/1207664893: Downloading webpage
[gog] z: Downloading images
logo: OK
screenshot 1: OK
screenshot 2: OK
screenshot 3: OK
screenshot 4: OK
screenshot 5: OK
screenshot 6: OK
screenshot 7: OK
screenshot 8: OK
screenshot 9: OK
screenshot 10: OK
screenshot 11: OK
screenshot 12: OK
[youtube] z: Downloading videos
[youtube] kJTgntUDhzE: Downloading webpage
[download] Destination: Z trailer.mp4
Z trailer.mp4       100%[===================>]  11.73M   904KB/s    in 13s     
video 1: OK
z: gog_games_z_bonus.zip: OK
```
[...](https://pastebin.com/V35JU3uj)

***Example Files***

[gog_games_z_bonus.zip](https://pixeldrain.com/u/y6mrvimi)
[gog_games_zed_bonus.zip](https://pixeldrain.com/u/8cRLVVvd)
[gog_games_forager_bonus.zip](https://pixeldrain.com/u/RbeJBmXG)
[gog_games_the_colonists_bonus.zip](https://pixeldrain.com/u/MV4m5PeE)
