### ISSUE TITLE
Add games for Linux and Mac

### ISSUE THREAD

**Issue by Rode1000** [MachineGunnur/GOG-Games#287]
There are games that have Linux and Mac installers available, it would be great if they also added them to the website.

**Comment by mozo78** [comment]
There are thousands of Linux games but they will never be added. Here are the Windows Institutionalized Fanboys club.

**Comment by Masamune3210** [comment]
@mozo78 you just won't stop will you, even after the owner of the project told you too?

**Comment by Masamune3210** [comment]
It's nothing to do with the os like the other one is obsessed with spamming issues about. It's about the fact that hosting multiple installers multiplies the amount of storage needed to host them

**Comment by mozo78** [comment]
Yeah, but for Windows there is always space. Windows is our live, Windows is our fate. It's very important to support Microsoft in their mission to plague the whole world and to strengthen their positions. Viva la Microsoft, our king, our heart!

**Comment by Masamune3210** [comment]
It's the most common os, especially for gaming. It makes sense to stock the more common items if you can't afford to stock all. It's common logic and you are either a griefer or seriously touched in the head

**Comment by SilentMRG** [comment]
> Yeah, but for Windows there is always storage space. Windows is our live, Windows is our fate. It's very important to support Microsoft in their mission to plague the whole world and to strengthen their positions. Viva la Microsoft, our king, our heart!
> 
> And the issue is not mine. I just told the OP there's no chance here - the Windows land.

If it's not good here, then look for a better place! You judge us by our obvious, functional preference for Windows, but, you show yourself as a Linux fanboy. You are just being the flip side of the coin! Think about it...

**Comment by mozo78** [comment]
> It's the most common os

Very wrong. Linux is the most used OS globally and it's literally everywhere - supercomputers, NASA, CERN, stock exchanges, telecommunications, Web, automotive industry, cloud compiting, IoT, Internet, networks, servers, TV's, phones, to name a few. It's the desktop - the last bastion and the only reason is the users habits.

> > Yeah, but for Windows there is always storage space. Windows is our live, Windows is our fate. It's very important to support Microsoft in their mission to plague the whole world and to strengthen their positions. Viva la Microsoft, our king, our heart!
> > And the issue is not mine. I just told the OP there's no chance here - the Windows land.
> 
> If it's not good here, then look for a better place! You judge us by our obvious, functional preference for Windows, but, you show yourself as a Linux fanboy. You are just being the flip side of the coin! Think about it...

There's no a single supercomputer in the top 500 running Windows and there's a reason. NASA left Windows in 2013. Musk sent people in space with Linux, not with Windows. And no, I'm not the flip side of the coin for I don't use a crap, bloatwared, inconvenient, insecure and paid piece of **** boasted as OS. There's a big difference. Use Linux for a year or two as a main OS and you'll understand. There's no reason supporting monopoly, closed source OS and the status quo as a whole.

**Comment by Masamune3210** [comment]
I use all three big OS's, they all have strengths and weaknesses. You are nothing but a fanboy who seems to be think that the louder they yell and the more they use big boy words, that they will eventually save the world from the tyranny of Big Windows. 

News flash, not everyone cares. And screening about something tends to drive people away more than towards.

**Comment by mozo78** [comment]
I don't yell at all. And yes, I used to be like you but now I'm using the better OS and I'm not dependent from Microsoft. This is not a fansomething - it's called freedom and consciousness.

**Comment by MachineGunnur** [comment]
**@mozo78 I** told you to stop instigating the OS debate in the last issue thread. Oh and I guess you should stop using Github to: https://news.microsoft.com/announcement/microsoft-acquires-github/


**@mozo78** You can view issues RE linux/mac games in closed issues. It has been brought up before.
