### ISSUE TITLE
Darksiders 3 Broken Links and can't vote to re-upload

### ISSUE THREAD

**Issue by ajhix36** [MachineGunnur/GOG-Games#29]
Hi, for darksiders 3, it has about 5 broken links out of the 43, but I can't vote to re-upload even though it says last upload was 2 months ago. And when I tried to vote on it, it says not old enough.

**Comment by MachineGunnur** [comment]
sadly, seems it zippyshare error server side. these are two links that don't resolve:
https://www115.zippyshare.com/v/iln3Kwpx/file.html
https://www116.zippyshare.com/v/Ab0WdAXQ/file.html

game was last uploaded on July 11. why you can't vote. will change it so can

**Comment by MachineGunnur** [comment]
pushed to top - will be next

**Comment by MachineGunnur** [comment]
oh ya, if cant vote for re-upload it because game was re-uploaded in last 30 days ;) 

signing off!
