### ISSUE TITLE
Stardew Valley Version

### ISSUE THREAD

**Issue by Stardevv** [MachineGunnur/GOG-Games#291]
Sorry if this not the right place...
On official website they said that the lastest version is 1.5.2
is the lastest update on the web is the same version, or 1 version before?
because when i check in game it said the version is 1.5.1
sorry again if this not the right place, i'm new to this...

**Comment by SilentMRG** [comment]
Really... You are right! However, give the site owner time to update the game. All game updates are done manually! Wait... that in the next few days he will update the game.

And according to:

https://www.gogdb.org/product/1453375253#downloads

https://www.gogdb.org/product/1453375253#builds

The offline installer has not yet been released. Only GOG Galaxy users have the new update. In summary, for the website owner to update the game, any game, it is necessary that GOG release the installer offline.

**Comment by Stardevv** [comment]
okay, thanks for the reply...
the site just update in similar time with 1.5.2 update, so i assume it is the lastest update..
i just want to know is the site lastest update is the same at official or not...
and thanks for the answer :)

**Comment by SilentMRG** [comment]
The website update is the same as the first link. And yes, it is version 1.5.1, and the current one is 1.5.2, which was actually released today, according to the second link. About being official, all installers and goodies on the site are official! This is the quality standard of the site's creators.

And if it is possible on your part, make a donation to the site! The site is maintained through donations. Thus avoiding those malicious advertisements that many sites have.

Thank you again!
