### ISSUE TITLE
[REQUEST] Support for uploading all OS versions

### ISSUE THREAD

**Issue by Lax4ever** [MachineGunnur/GOG-Games#292]
One of the benefits of GOG is the ability to get games in multiple operating systems. As part of the project is it possible to request the ability to upload all the versions?

**Comment by SilentMRG** [comment]
Please read these topics carefully:

https://github.com/MachineGunnur/GOG-Games/issues/256

https://github.com/MachineGunnur/GOG-Games/issues/287

Thank you for your attention and welcome! And consider donating to the site, as everything is maintained through donations.

**Comment by MachineGunnur** [comment]
already be addressed. search closed issues next time
