### ISSUE TITLE
Seedbox Fundraise

### ISSUE THREAD

**Issue by MachineGunnur** [MachineGunnur/GOG-Games#293]
**Funding Progress:**
![Progress](https://progress-bar.dev/100/)

The code for torrent support for New & Updated games has been implemented and tested (see https://gog-games.com/game/fallout_classic second download option)

This will increase monthly costs, so looking for support to raise funds to cover monthly costs for a SSD and storage seedbox.

Want to raise 2 months for both boxes. **Cost:** 60 EUR (72 USD).

The best way to donate is by going to https://gog-games.com/donate and reading the options.

**If you can, the best way is via Bitcoin.**

Thank you.

**Comment by MachineGunnur** [comment]
![Progress](https://progress-bar.dev/7/)
https://progress-bar.dev/7/

**Comment by stringles** [comment]
Thank you for notifying the progress and the idea is great. May I ask, is there an end day of the fundraiser if the community itself will be found not in a great need for? I hope it'll go fine, be funded: This will prevent troubles like "Cyberpunk 2077" was. No sure about what will happen, though.

**Comment by MachineGunnur** [comment]
> Thank you for notifying the progress and the idea is great. May I ask, is there an end day of the fundraiser if the community itself will be found not in a great need for? I hope it'll go fine, be funded: This will prevent troubles like "Cyberpunk 2077" was. No sure about what will happen, though.

sadly... not much has come in with donations.... may give it 2 weeks then cancel.

**Comment by MachineGunnur** [comment]
OK, got enough. Thanks you everyone. Will finish up the last step and buy and step the seedboxes.

**Comment by stringles** [comment]
How fortunate. For a second I almost lost hope that it'll ever happen. Thanks to everyone who donated, you are incredible prople.
