### ISSUE TITLE
[THIS IS NOT AN ERROR] - Torrent - Duke Nukem 3D: Megaton Edition

### ISSUE THREAD

**Issue by SilentMRG** [MachineGunnur/GOG-Games#294]
Hello...

Does anyone here have a good torrent of this Duke Nukem 3D with the latest update 1.4.9 (03 May 2015)? I believe this is the latest version.

For me this is the best version of the game! And unfortunately it's no longer for sale and I can't find a decent torrent anywhere!

Thank you for your help!

**Comment by MachineGunnur** [comment]
this is not the place for this.

**Comment by stringles** [comment]
Exactly. It shall be put on a specialised forum outside of Github or whatnot, not here. You are putting the owner at risk of suspension and anything of that kind is not welcome due to Github ToS. Please avoid making these issues, looking forward.

**Comment by SilentMRG** [comment]
This version of the game can be considered "abandonware" as it has not been sold in years! The only version available is the "20 Years Anniversary", which has changed a lot in the files of the last penultimate version. I don't see that abandonware puts the site owner at risk. And I just asked the question here, because I know that those involved have experience with internet and programming, and I thought: "Maybe they can help me". I really like the site and I admire the work of all of you and I don't want anyone to be at risk! And rest assured, I will not open this type of topic any further.

**Comment by stringles** [comment]
Okay, you made a very valid point. But what can I do then? The best I can do for now and indefinitely to all of these is to suggest an open source GitHub project called [BTDigg](https://github.com/btdig) and that's it. All further is of your doing and legal responsibility.

You know, I can relate, some people with 10 TB drives may have 4 copies of "No Man's Sky" and 2 of "Heroes of Might and Magic III" exactly for the same reason, new versions make significant changes, not always bad but different. Keeping all old versions of old games could be too much even for me, I mostly remove unless a need.
