### ISSUE TITLE
Clicking on download doesnt open the download links

### ISSUE THREAD

**Issue by Felipefpl** [MachineGunnur/GOG-Games#295]
when clicking in the download button nothing happens, to show the links i have to keep pressing the TAB button till the cursor is in the download button, then i have to keep the ENTER button pressed in order to have the links shown, this happened here:

https://gog-games.com/game/ys_memories_of_celceta

I'm using firefox 84.0.2

**Comment by MachineGunnur** [comment]
the links are protected by google recaptcha. test with same version as you on firefox and no extensions - works fine.

**Comment by Felipefpl** [comment]
I see, thanks for the reply.

**Comment by stringles** [comment]
Everything gracefully works on the latest ESR version of Firefox on my PC and non-ESR on mobile. It could be somewhat linked to extensions, browser settings or the ISP. Either way, the site performs fine.
