### ISSUE TITLE
Streets of Rogue

### ISSUE THREAD

**Issue by SilentMRG** [MachineGunnur/GOG-Games#297]
The main installer is 64-bit, while the DLC installer is 32-bit.

Is this an error or are these the installers that GOG provides? I think the DLC installer should be 64-bit.

_setup_streets_of_rogue_v93_2_ **(64bit)** _ (43992) .exe_

_setup_streets_of_rogue_character_pack_v93_2_ (43992) .exe_

I think that maybe there will be some conflict when installing the DLC (32 bits) together with the main game (64 bits), or maybe, it has nothing to do! he he.

Thanks for reading!

**Comment by stringles** [comment]
No issue. The pack are a bunch of assets, not an executable, like the same how Linux packages have shared data for both versions of an app or "Crysis Warhead" 32/64 executables use the same maps. The "Streets of Rogue" game [has](https://www.gogdb.org/product/1600715263#downloads) two versions, the pack does [not](https://www.gogdb.org/product/1138017190#downloads) and there is no other in the Universe. Simple.

If you doubt the credibility of GOGdb, then parse a bit outdated but sufficient enough Connie's [DAT](https://onedrive.live.com/?authkey=%21APgbl3v0s41kQUQ&id=201ECFA3DD196829%2121848&cid=201ECFA3DD196829)s for or try any other place. It might be much appreciated to make an issue if there is an issue who is proven to be a problem, including by own experience, not suspected. The pack has no division, there is no error and nothing to worry.

**Comment by SilentMRG** [comment]
Got it.

I apologize for the rushed topic I opened. I like the site and when I suspect something is wrong, I always try to communicate, even if I'm not sure if it's an error or not. I trust gogdb and always use it. Anyway, if you had a bad day or week I wish you well! Really. I don't know him but I know that there is an altruistic human being on the other side of the screen.

Thanks for answering!

**Comment by MachineGunnur** [comment]
first installer ive seen without 32/64 bit in the setup name. interesting.

**Comment by stringles** [comment]
The same. Haven't read all installer but I didn't see alike before on GOG. The confusion is understandable.

> I don't know him

I don't know the GOGdb owner or "Connie" too, I only know the 1st has data on installers and the 2nd has valid signatures for old files and the collection is independent: All what I cared for. Anyways, I won't dare to mistakenly gender both Connie and the GOGdb owner unless know for sure from, it's never nice to be misrepresented. An enby myself (they/'em only). 

You can parse the DATs and get a list of misplaced or missing data: Would be incredibly helpful in this case even if manual decisions are required and not all DATs are up to date, to find EXE/DLC mismatches as a byproduct. Thankfully quering the list of files from GOG Games won't be a problem. Parsing might be an issue, their DATs are outdated, many games are missing.
