### ISSUE TITLE
Google Drive AND Zippyshare too!

### ISSUE THREAD

**Issue by dreamco3d** [MachineGunnur/GOG-Games#30]
Hello friend. I find your decision to go with Google Drive very good for people with no access to zippyshare, but considering Google's recent limitation of the "Make a copy" option, i suggest you should keep zippyshare too if its possible.

Thanks in advance :)

**Comment by MachineGunnur** [comment]
can only do one hoster, sorry.

**Comment by hellwalker31** [comment]
hey dream, check "stars" in the sky to solve this problem...  or become a "terminator"... but to be able to do one of this, u need to solve these riddles...

**Comment by specterlich** [comment]
Hey hellwalker, i get the "terminator" part but not the "stars".
I have to say though, for me, changing to gdrive from zippy was like GOD dying all over again. Since then i can't download a single file. Not one is accessible. JDL is useless. Of course i understand that zippy is blocked in places, but for me it was heaven. So for now "hasta la vista baby"... if you know what i mean. "I'll be back" to check on MG's project though.

**Comment by hellwalker31** [comment]
zippy was better for me too... i understand u really so much... i dont even really care about those countries... they can even cease to exist, why care... it is ther problem when the links are by zippy but when u go for google drive, it is whole world's problem.

BTW... "stars" is for quota thing... u need to login with ur gdrive (my bad).  it is too simple really but dont wanna tell it openly. u can imagine why.... but here a hint...
u can see "stars" as points in the sky... 
it is a kids' play really... why nobody found it i have till now no idea... even "terminators" thanked me really in surprise.
just check for the "stars" really... stars... stars... stars... stars... stars.... many many stars... just add stars in ur brain 
but stars are more beautiful when u r the one who knows about them only...
so u dont need to go off... u can download without quota problems.

**Comment by specterlich** [comment]
Well damn. I got it. Very sneaky, hellwalker. Too bad it doesn't help with jdl and google will probably fix it soon too. But until then, it's a nice workaround. Cheers buddy.

**Comment by dreamco3d** [comment]
I feel really stupid right now.  Oh well..you don't deserve me.
