### ISSUE TITLE
DRM

### ISSUE THREAD

**Issue by SilentMRG** [MachineGunnur/GOG-Games#302]
I watching Cyber ​​Shadow live and people commented that the game has a kind of "anti-piracy screen". Is this real? Although GOG games are DRM free, I in doubt. I haven't tested the game yet to find out. Has anyone tested and seen if the game is 100% DRM free?

Thanks!

**Comment by MachineGunnur** [comment]
Go post here: https://www.gog.com/forum/cyber_shadow#1611786489

**Comment by SilentMRG** [comment]
This is not necessary.
The game is DRM free!
