### ISSUE TITLE
I can't/ don't know how to install patches.

### ISSUE THREAD

**Issue by KryGuy** [MachineGunnur/GOG-Games#305]
I downloaded a patch from the developers of huniepop 2 and tried to install through mutliple ways but it didn't work, the file ends with .dat.

**Comment by stringles** [comment]
This is absolutely not a GOG Games issue.

May I know, "from the devs?" No, no, no. You are not supposed to use non-GOG executables. GOG Games is at most only responsible for integrity of the official installers and its files and Goodies being authentic, anything else is your personal problem. From all what I know, it could be for Steam. Please go to [the GOG forum](https://www.gog.com/forum/huniepop), it has these topics, try to figure out on your own. This issue doesn't belong here.

**Comment by stringles** [comment]
GOG Games is not responsible for issues of GOG itself, like censoring games which is what you are apparently trying to circumvent nor for the cases what an official patch installer does something wrong. In this case go to a GOG forum branch too. Though, it probably would be fine to notice that a patch doesn't install if there is no full installer but nothing more. GOG Games is not the official GOG support team.

**Comment by MachineGunnur** [comment]
the only patches you should be installing are the incremental ones from GOG. there is no GOG patch for that games atm i believe either.
