### ISSUE TITLE
GAME-DIVINITY.ORIGINAL.SIN.2-(40474).PART066.RAR is empty 

### ISSUE THREAD

**Issue by darungg** [MachineGunnur/GOG-Games#307]
Hello, the file number 66 is empty and the game can not be extracted.

**Comment by darungg** [comment]
![image](https://user-images.githubusercontent.com/47596353/107659925-fca52c00-6c87-11eb-8cb4-ea750d0d17ed.png)

**Comment by MachineGunnur** [comment]
hi,

this issue on your end. download form ZS and extracted fine with 7zip 18.05 x64

**Comment by stringles** [comment]
The RAR is not empty, I checked right now as well as an independent collector.

Use an alternative and be careful with the next time. If all others don't work and a product is inaccessible even from a VPN, then vote, but if no vote, then use the decentralized way, if no decentralized does work for days, then probably an issue. Usually there is no need to make any tickets.

**Comment by darungg** [comment]
Hi, i redownloaded the Game from Zippyshare and now everthing works fine. Sorry for the false issue and thank you for your help.
