### ISSUE TITLE
EVERSPACE 2 (in dev) offline installer update

### ISSUE THREAD

**Issue by fehmi1907** [MachineGunnur/GOG-Games#309]
I have read the sticky about out-of-date games; apologies in advance if this is breaking the rules. However, EVERSPACE 2 was released quite recently, on Jan 18th, and the offline update (0.4.16428) was posted on GOG subsequently, on Feb 10th. As this is a an in dev game, I thought @MachineGunnur might have missed this updated offline installer.

**Comment by stringles** [comment]
Well, the rival forum (who must not be named) has had it on Febrary 17. Technically availble, it can be flawlessly done. The range of products that GOG Games covers is incredibly broad, good there are updates on data at all 'cause this is a lot of work. Sometimes takes weeks or months to notice, usually done quite fast.

**Comment by stringles** [comment]
In my understanding, the rule exists since this is rarely useful: Can be before a week passed and availble; Can be only on Galaxy; Not released yet; etc. "Not have," as the rule said. At least that's what my observations tell and show so far.

**Comment by fehmi1907** [comment]
I totally understand that maintaining GOG Games is a huge task and genuinely respect MachineGunnur's hard work. I do not wish to sound impatient - I merely wanted to point out my observation as this is an in dev game and the procedure to keep it up-to-date updates might be different than that of regular games.

**Comment by stringles** [comment]
Thanks!
