### ISSUE TITLE
Kerbal Space Programm (Missing DLC)

### ISSUE THREAD

**Issue by dreamco3d** [MachineGunnur/GOG-Games#31]
Hello MG. Not sure if its a system bug but Kerbal Space Program is missing a dlc, and the present is not the one referred in the patch notes.

**Comment by MachineGunnur** [comment]
dont have access to that DLC. sorry. some else need to share.

**Comment by dreamco3d** [comment]
I have that DLC if you are interested!

Cheers

**Comment by MachineGunnur** [comment]
just upload then email link to machinegunnur@yandex.com

thanks btw. helps a bunch when other share things
