### ISSUE TITLE
Doubt - JDownloader 2

### ISSUE THREAD

**Issue by SilentMRG** [MachineGunnur/GOG-Games#310]
Hello...

I never used the automatic unzip function. And unfortunately I don't have any compressed files at the moment. My question is this: If I download a compressed file that contains more than 2000 compressed files, will JDownloader unzip all of them? I mean a single 2.94 GB compressed file, with more than 2000 compressed files within it.

I know this is not a problem with the site. And I apologize for opening the topic. However, I know that many of you have extensive experience with JDownloader, in light of that, I believe you can help me.

Thanks for your help and attention! =)

**Comment by Masamune3210** [comment]
There are other places for help with jdownloader...

**Comment by SilentMRG** [comment]
> There are other places for help with jdownloader...

Tips for places?

**Comment by SilentMRG** [comment]
I extracted everything manually using 7Zip. Apparently, the automatic function did not work.
