### ISSUE TITLE
Northgard -  Menu GOG Galaxy Requirement

### ISSUE THREAD

**Issue by jbrant143** [MachineGunnur/GOG-Games#313]
After i downloaded and installed the latest version in the main menu of the game i can only select the story mode to play, the other  modes cant be selected and it says I need to log in through GOG galaxy  to access the other menu. I uninstalled it and reinstalled it but the problem still occurs.

Here's a picture of it.

https://pin.it/1LHzCC4

**Comment by MachineGunnur** [comment]
I am not the game dev or GOG.com raise issue there. look at forums, not a bug, its intentional.
