### ISSUE TITLE
Good Company preorder bonus corrupted

### ISSUE THREAD

**Issue by callmenemo491** [MachineGunnur/GOG-Games#315]
`https://gog-games.com/game/good_company`

i downloaded from zippyshare + pixeldrain links,  when run the pre-order bonus install
[setup_good_company_pre-order_bonus_0.9.2_(64bit)_(45875).exe]

get popup straightaway about it is corrupted.
suspect what has been uploaded is faulty.

**Comment by factioidious** [comment]
Not corrupted. I picked PixelDrain, tested the archive and tested the EXE. The signature is absolutely [valid](https://www.virustotal.com/gui/file/7c53b18bd44d7bc2607467b4bd8c41ff302a0dd1f74b93199dc8a5f0e515589f/details): "Signed file, valid signature," VirusTotal. The file integrity is 100% as GOG provided.

**Comment by callmenemo491** [comment]
the integrity, just shows that the file has not been tampered with... so what i have is 100% the same as GOG provided.
when you run the EXE, you get:
![image](https://user-images.githubusercontent.com/13878580/115136864-81803d80-a05d-11eb-81a6-e88835e1fcc2.png)

so what i stated was correct _"what has been uploaded is faulty."_
(its corrupted on GOG side.. that they uploaded a faulty EXE)

therefore nothing GOG-Games can do., so closing ticket and will wait for update from GOG (in terms of newer EXE)

**Comment by friendlyghosty** [comment]
@MachineGunnur Please would you kindly roll back to 0.9.1? It will be highly appreciated.

@callmenemo491 I thought it meant signature integrity corruption, understand now. I never saw that before. Indeed, the only options are: To roll back a little, just the version from 3 days ago is nothing critical, else wait for updates and remove the errorful now. GOG is not perfect.

GOG Games always checks every file, be it an EXE, BIN or ZIP: However, not running EXEs, solo integrity by signatures.

**Comment by friendlyghosty** [comment]
Will for new too and roll back, nothing to do.
