### ISSUE TITLE
Good Company v.9.0.2 Fix

### ISSUE THREAD

**Issue by liketa4169** [MachineGunnur/GOG-Games#316]
Hi!

Issue #315 shows 9.0.2 is corrupted by GOG.

I've sent you the data URL on your Help eMail with the same title as here to implement the fix: To make it we can use 9.0.1 with Pre-Order from just 3 days ago, then switch to 9.0.3 when released. Free to do nothing with but it's basically a bug.

Not a new game, latest update nor a patch but a fix of GOG's fault. All what I am interested in is for GOG Games to be the best.

With regards,
liketa4169

**Comment by MachineGunnur** [comment]
done, ty

**Comment by liketa4169** [comment]
Thank you very much!
