### ISSUE TITLE
No to Begging for own Mistake

### ISSUE THREAD

**Issue by ghost** [MachineGunnur/GOG-Games#320]
This exact PayPal was your decision. Why shall we suffer from? We followed your orders.

We expected you own PayPal and have access to, not shady 3rd parties. Now a week left, you knew it could happen. Why must people pay for your miscalculation, can you tell us? Your mistake, your cost shall be.

What could be done is to extensively verify and test a contact before trusting. Instead was blindly doing so, no test. My feeling is the contact of yours took away money and left. Did you ask for WebMonay or something also? Scrap it.

Let be honest, Bitcoin is difficult. You shall mention Coinbase or other services and make reaching you a sender's issue. After all, if a donater cannot make an account, do they even care on donations in the first place?

When the boss of Nintendo made great mistakes, they cut own pay and vacations, were working hard, not hurting employees who were doing the boss' will, nor harm customers. In my opinion, for this month exclusively, you must be like Nintendo, not blame or harm us for your failure. 

Knowing you want to not take the blame but to make your supporters pay for your mistake or fail 'em soon, it breaks my heart to see that. Why do you often rush ahead without being steady, when will it stop? It isn't the first time I see you rush suddenly making a huge mistake, you know.

I am sure this isn't only my thoughts. Seeing a hundred dollars lost is sad. Please be extremly careful, trust only yourself.

**Comment by nintendoid** [comment]
Hosting the site itself  takes maximum US$10-5 without constant uploads. Shutting down is the absolute lie. In the worst case, kill the drivebox and run a bot who will download 1 byte from files on Zippyshare each week-two, then when have money, recover. If have trouble, open an issue and I can help with recovering later, I have a copy.

**Comment by liketa4169** [comment]
Let's imagine "succeess" here.

2 Bitcoin transactions in/out are 6+ days (no high fee), [18.88 is on Bitcoin](https://www.blockchain.com/btc/address/3PEnMtoDqgqANwyCXffMtVhthK22RKRJrW), 101.22 left, nobody sent anything yet: Assuming the threat is real, all are 99.99% screwed.

@MachineGunnur, be real, don't repeat the story of Icarus. Why can't you cut traffic and mirrors to only ZippyShare and make non-BitTorrent P2P links, eh? It'll cut price to 36.12 or 55 per month.

I pay 55 for my copy (20/40 TB space/traffic). Cannot help on donations, maximum an Onion mirror site, sorry.

**Comment by MachineGunnur** [comment]
the paypal contact sent the moeny in the past. they are legit. either they had life issue or something.... go rant somewhere else I am not putting up with this.

**Comment by liketa4169** [comment]
Torrminatorr is better than you. You rant, beg and cry in red on your site, behave like a child, reject to optimize, attempt to fail genuine supporters. Nice the PayPal is legit, bad you decided to be impatient Icarus.

People scrabbed 97.88 on top. Add own 22 dollars and don't be an asshole. I am tired of your childish behavior and stupid threats, unreliability, trying to kill the project because you are broke. Enough is enough.

**Comment by liketa4169** [comment]
Don't you dare to fail us, motherfucker.

**Comment by liketa4169** [comment]
I pricesely remember how you said on Antox "everything is paid by friends" and that this shit you do with threats is not really necesarry. I do not support for the life of me that you lie to people who love you. I wish you the worst, honestly, because you are an asshole.

**Comment by bunjoe** [comment]
And I am not putting up with your begging nonsense every freaking month.

It is extremely panicingly annoying and based not on true love but threats, like a toxic releationship. Are you that much broke and cannot pay even relatively small US$120, like around 2 AAA and 1 indie game? Oh yes, you said your friends pay the bills. So shut off the bogus theatre.

For reference, I live in a truly poor authoritarian country yet do find US$55 per month to keep all games and never begging. If you were smart, you could've used this opportunity to put data on me and pay only US$5 or whatever giving your simple HTMLs cost with the domain.

Just stop threatining/blaming, trying to fail your customers when made a mistake, be an adult and be prepared to bear the cost of own decision without relying on "parents" (donaters) to cover your naked ass. We are not your moneybag.

**Comment by Masamune3210** [comment]
If you dont like it fucking leave instead of ranting. You don't have to use this
