### ISSUE TITLE
Acknowledgment

### ISSUE THREAD

**Issue by SilentMRG** [MachineGunnur/GOG-Games#321]
Hi...

Yes, I want to thank the website owner for all the work done. I saw the emergence of the old site and its fall in 2018 and it was thanks to the owner of GOG-GAMES that we were able to access this sea of ​​games easily and free of charge, in addition, of course, safely.

Goodolddownloads as well as GOG-GAMES can be considered the apex of the distribution of digital (free) games on the internet.

I would like to help, but $ 120 is basically half of my salary. Yeah... I live in a very poor country.

Anyway, I wish all the best to those involved in the project, especially to the website owner. May God bless and protect you all!

My thanks!

**Comment by bunjoe** [comment]
Don't encourage the egoistic ranting/screaming/begging/threats in red behavior. Please. It gets out of hand.

MachineGunnur said to me personally that all, I repeat, all bills are paid by "friends" and it was before donations even existed, I remind you. Don't be worry. The first attempt was done with a fake threat of a site closure, they were having "fun:" It worked, now it never stops.

The site has two servers. The threat on "closure" is a lie. Maximum in a bad turn, the site will temporarily loose the pricy sharing server. In the worst case, traffic can be cut and the cost made US$55, like mine: You can get 10/20 (TB/Traffic) even from the worstest provider for that price.

The person is likely jealous of Torrminatorr who receives donations from time to time without any threats: It is 5 years old, has all games. MachineGunnur was annoting me on Antox everyday with rants on "how I hate Torrminatorr" and literally bragging on trolling the forum, sending DMCA to harm, other bad things.

The person is no saint and no god. Not an apex, all data are "stolen" from Torrminatorr, Tapochek, RIN and no credits to those who shared, there is no honour in this. The site is based on others' hard work. So, with aknowledging of the "good" side, we must remember there is the dark side too.

**Comment by moketo** [comment]
Metalschlumpf [wrote](https://archive.is/AhKbS#issuecomment-830575472) (Issue 322):
> ... The truth is he steals 99,9% of the games to run this website. ...
> He take them minutes after posting (without leaving a "Thanks" of course), rebrand them with his "gog-games.com" messages and tries to raise money here with the games. He's a thief, fraud and a lying asshole. ...
