### ISSUE TITLE
Integration with third party service

### ISSUE THREAD

**Issue by LeffdePeff** [MachineGunnur/GOG-Games#328]
Can I integrate this with my own application if yes than how can I access some sort of api or database? Hope you can help me.

**Comment by MachineGunnur** [comment]
there is no public api currently. i am gradually working on my own re-write of the site which will have a public api though.

what is your application? if it involves revealing and making download links accessible to the public without captcha, protection, etc on the links to counter DMCA - this is highly discouraged.

**Comment by LeffdePeff** [comment]
I wanted to try to make a client like steam but for free gog games. I could implement a captcha when downloading but the links aren’t revealed to the user the client only  downloads from a mirror that is up inside the client and the installer installs the game in very silent mode.

**Comment by LeffdePeff** [comment]
If I don’t reveal the links to the user is it still recommended to use a captcha?

**Comment by MachineGunnur** [comment]
drop me your email and we can discuss via IM.

**Comment by LeffdePeff** [comment]
leffdepeff@gmail.com

**Comment by Masamune3210** [comment]
Might want to delete the email comment once emails start, having a email on a public board is just asking for email bots

**Comment by LeffdePeff** [comment]
leffdepeff@gmail.com
