### ISSUE TITLE
Search doesn't return partial-word matched results

### ISSUE THREAD

**Issue by Suddow** [MachineGunnur/GOG-Games#330]
For example, searching "spirit" will not return results for Spiritfarer, but searching "shadow" will return "shadow warrior 2".

**Comment by MachineGunnur** [comment]
I am aware, thank you

**Comment by label4444** [comment]
It could be wise to ignore non-crit words like "the" or "a"/"an" when search; To do partial only from left to right, not a random part of a word; To hesitate small typos like "spurit" instead if "spirit."

Can be cool to use it for redirects from "Error 404" on an incorrect slug of a "/game/" link and even allow all related slugs/IDs to be valid for, like from DLCs.

**Comment by MachineGunnur** [comment]
moved to issues of private repo of rewrite.

not sure if the search engine i plan on using can do that but should be improvement from current.

**Comment by outboxerd** [comment]
Don't rush, take your time

**Comment by postseetiom** [comment]
Seems to work.
