### ISSUE TITLE
Can’t connect

### ISSUE THREAD

**Issue by Chris2270** [MachineGunnur/GOG-Games#331]
Code 522 or 523

**Comment by MachineGunnur** [comment]
Guessing network issues with provider or issue with VPS hosting. Opened ticket.

No configuration has changed for ~2 years and been stable. No updates - using docker to not update and break software, etc.

Let's see what they say.

**Comment by MachineGunnur** [comment]
Resolved. Most likely network. Will monitor though.

**Comment by MachineGunnur** [comment]
host has resolved.
