### ISSUE TITLE
Gamedec is in Russian

### ISSUE THREAD

**Issue by duskeer** [MachineGunnur/GOG-Games#334]
Please download the English version of the game setup.
https://www.gogdb.org/product/1921398290#downloads

**Comment by duskeer** [comment]
Please would you kindly avoid any installer with "_(russian_64bit)_" for the future? To not repeat the mistake.

**Comment by duskeer** [comment]
Also Scrapnaut is not in dev anymore:
http://www.gog.com/news/scrapnaut_leaves_the_development_stage

**Comment by MachineGunnur** [comment]
done.
