### ISSUE TITLE
Error 522

### ISSUE THREAD

**Issue by Spider-of-Steel** [MachineGunnur/GOG-Games#335]
The site has been down for more than 5 hours! At least that's what it looks like. Down for maintenance? Perhaps...

**Comment by duskeer** [comment]
The error seems to be related to Cloudflare and the host connection issue, it's like the repeat of #331 from 11 days ago

**Comment by Spider-of-Steel** [comment]
So far everything is working fine on the site.
But until when? These blackouts are harmful.

**Comment by duskeer** [comment]
I personally agree. If it'll keep happening that often, something should be done.

**Comment by MachineGunnur** [comment]
people only notice the bad. 

even amazon, google and cloudflare have downtime.

relax and take a breath of fresh air.

**Comment by Spider-of-Steel** [comment]
> people only notice the bad.

And we're on the Issues tab to report what's bad: Issues.

**Comment by MachineGunnur** [comment]
> And we're on the Issues tab to report what's bad: Issues.

then find me a hoster with 100% uptime, DMCA ignored and extremely cheap. Answer: impossible
