### ISSUE TITLE
Gamedec Update

### ISSUE THREAD

**Issue by geuks** [MachineGunnur/GOG-Games#336]
Hi, thank you for your awesome work ! apologies in advance if this is breaking the rules but please can you add the last 2 patches for Gamedec because it fix localization problems. Thank you again !
https://www.gogdb.org/product/1921398290#downloads

**Comment by label4444** [comment]
You shouldn't really make those issues. Patches were added on the yellow forum today, so please don't be in hurry. What for? Be steady. GG usually adds relatively soon after.

Just Wwait a week, if nothing then try to use the forum's mChat at the time when GG is usually updating, if it didn't work after a few days and you sure it is available on the forum, then maybe should make an issue here. But I assure you, most likely you wouldn't need to.

**Comment by MachineGunnur** [comment]
updates will come - my focus has been on my own rewrite of GG.
