### ISSUE TITLE
Hitman GOTY is not DRM Free

### ISSUE THREAD

**Issue by label4444** [MachineGunnur/GOG-Games#337]
To play the offline campaign, it requires a constant online connection to dev servers, rendering the title simular to a demo otherwise: This is very wrong and must be fixed. Please avoid this fucking shitshow until goes real DRM Free.

"All progression - mastery levels, challenges, and consequently unlocks for different starting locations, stashes, equipment and weapons - is also locked behind the online mode requiring connecting to the game's servers. So you cannot ever use anything other than the default starting status, I would consider it similar to a demo," a GOG reviewer [said](https://www.gog.com/forum/general/release_hitman_game_of_the_year_edition_11093).

**Comment by MachineGunnur** [comment]
OK? don't play it then. we just archive shit.

**Comment by label4444** [comment]
"Shit," yeah, exactly the smell of your shitty attitude without a decent quality limiter or honouring the true GOG standards.

If not me, a person respecting real quality and who gave you a prototype verification script, you still could have broken game installers because (not "we," you are 1) "you just archive shit." The case how you often have junk installers, like forgetting to delete a DLC from the previous update or having both 32/64 and 32 without DLCs, it only confirms the attitude. I made ways to detect and fix it but you are too lazy to do the same yourself.

You more care about freshness than fullness with quality. And you don't pay much attention when a game or a game version is broken, nor do to Github and still use the prototype from 2 years ago. You don't truly care about a quality collection, only of money and "shit."

As a person and collector, honestly, you have many issues.

**Comment by Masamune3210** [comment]
...you know editing your comments doesn't eliminate the contents, right? If you have such a problem with how the website is run, either don't use it, make one yourself, or shut it. It's not our fault that the game is crappily designed to require an internet connection

**Comment by postseetiom** [comment]
The content can be unlocked by:
1. Use the offline backup installers;
2. Download and install the GOTY patch found in the backup intaller page:
`setup_hitman_1_game_of_the_year_edition_dlc_base-s1-del02_gog-codecl1686781-assetcl-id5153278-dkcbld120-m-desktop_(64bit)_(49904).exe`
3. Start the game offline OR refuse the IO user agreement. It will warn you that you will be offline.

[Source](https://www.gog.com/forum/hitman_game_of_the_year_edition/how_to_remove_online_drm): Frozty_Squad

**Comment by postseetiom** [comment]
Masamune3210 , "our fault," what? Fuck you and shit up, you are not GG's stuff, nor GG is "we." MG has trust issues and always alone, and the one never downloads demos, this is pure stupidity, your attempt to excuse. What you should've done is to download the damn game and test it. Did you? No you did not. So did not I but I made the topic and people helped me. You  on the other hand, you behave like a puppy, trained to bark on a stranger, I don't respect that behavior whatsoever.

**Comment by postseetiom** [comment]
And Masamune, you are ridiculous, you jerk. A pronoun is to address the person. If a speaker cannot handle that and you ridicule a valid concern, honestly, go to hell.

**Comment by dcntrlfthcs** [comment]
> It still works as a demo for anyone who wants it
MachineGunnur does not upload demos. The attempt of an excuse is ridiculous. The nessage aboce is what you should've done instead.
> ...you know editing your comments doesn't eliminate the contents, right?
I forgot to delete it.
> If you have such a problem with how the website is run,
Every big project has issues, what said next is a waste of time and a poor attempt to be a puppy. I have no respect for an empty shell who doesn't think for oneself.
> either don't use it, make one yourself, or shut it
This may create a dangerous unforceen precedent. "Do you see an issue? Shut up!" This thinking is a threat to GOG Games. I understand that you attempted to fanatically defend the project, you originally had good intentions. But will the project be better if it'll be weak and full of holes, hesitate no criticism? The defence looks like a bullet in one's feet, this is not fine.
> It's not our fault that the game is crappily designed to require an internet connection
You are not an official staff member. Avoid to talk "our" or "we," talk for yourself and express it as a personal opinion.

**Comment by Masamune3210** [comment]
I am no ones dog, just don't like people whining for A. no reason and B. about something that has nothing to do with the project. 
Deleting doesn't eliminate anything either, especially for people with emails enabled
It's their choice to upload whatever they want. If they want to archive everything they can if they want to archive only what they want that is also a thing. 
The issue is with the game, the installer did its job. It's up to the user to figure out from there with most things
I have seen many projects rise and fall from such issues en masse so its a sore spot and I admit I reacted poorly. But all the attitude in these responses is just as bad. I'm not saying stop making issues, as that's half the point of this entire thing. But reacting like this isn't helping things either. 
and as a personal opinion, you all are acting like needy children

**Comment by dcntrlfthcs** [comment]
To be painfully honest, we all misreacted :(

**Comment by Masamune3210** [comment]
It, unfortunately, seems to be a common trait in these issues. Let's just all walk away and take a second before headbanging the keyboard and move on

**Comment by dcntrlfthcs** [comment]
OK, you are right on that. I may disagree, but thanks for expressing your thoughts.
