### ISSUE TITLE
No Man's Sky main menu

### ISSUE THREAD

**Issue by itsjaydentv** [MachineGunnur/GOG-Games#338]
unable to go to the main menu at all

**Comment by mozo78** [comment]
No problems even on Linux.

**Comment by Masamune3210** [comment]
Installer works fine, not a problem with the website or installer

**Comment by label4444** [comment]
Please submit to a game support forum. This is not a game support page, an issue must be related to GOG Games' so-call "collection."

**Comment by label4444** [comment]
And even if it does not trully work, MachineGunnur wouldn't care. The only thing they do care is to have the latest, not the fullest and the best quality nor working. For example look at Hitman GOTY. What a shitshow! This is idiotic.

**Comment by MachineGunnur** [comment]
what he said
