### ISSUE TITLE
"What he said" is Extremely Rude

### ISSUE THREAD

**Issue by Anonycrisp** [MachineGunnur/GOG-Games#339]
Never ever use this unless you are 100% sure that the person identifies themselves as such. This is an offense to use upon somebody who is not "he" and never was, no better than calling you "it," like a soulless inanimate object.

I don't know how true is your data about "Siberia" but this is not Russian and you must respect that, you're a guest in this realm. When you don't know how to address, shall use Singular "They" (the word in that sense is as old as "you") or just "the user" or "one." If you won't follow that, you only make yourself to look as a careless sexist stupid asshole instead of a good decent and smart person.

**Comment by Masamune3210** [comment]
If you get easily insulted by someone using the wrong pronoun, I'm not sure how you survive on the internet. Yes it's wrong, and if it's repeatedly intentionally wrong it's a issue. But this is ridiculous

**Comment by dcntrlfthcs** [comment]
This is not of your business.

The pronoun was an insult, no wrong to be insulted by an insult. No, not "rediculous:" No addressing a person is ridiculous, but ridiculous is in saying both "yes, it's an issue and it's wrong" with "this is ridiculous." One can't have both ways.
