### ISSUE TITLE
Hitman GOTY is not DRM Free

### ISSUE THREAD

**Issue by outboxerd** [MachineGunnur/GOG-Games#340]
> With an overall rating of 1.4 stars out of 5, it's the lowest-rated Hitman on GOG by a fair margin, with even Hitman: Absolution scoring a flat 4 stars out of 5. Most of the user reviews are critical of the newer Hitman for the same reason: "This game is not DRM free in any meaningful sense", as Sheershaw puts it in a one-star review.
>
> Hitman requires an internet connection not only for online features, like user-created contracts, leaderboards, and its time-limited Elusive Targets, but also to level up your Mastery progression. Without that you can't unlock new gear, additional loadout slots, different starting locations, or different pickup points when you replay missions.
>
> GOG users are claiming this is a betrayal both of the platform's anti-DRM stance, and the store's description of Hitman. "There is a text on the sidebar 'DRM FREE. No activation or online connection required to play.', but I could not consider it is true for more than a fraction of the game's content" writes emme. According to Neurus_Ex, "This is completely shameful, on both the side of the publisher, for not working an actual DRM-Free version and on the side of GoG, for selling this as a 'DRM-Free' version, when its clearly not the case."

https://www.pcgamer.com/gog-users-arent-happy-about-hitmans-online-requirements/

**Comment by MachineGunnur** [comment]
then take the issue up with the store **WHO PUT THE GAME UP TO SALE**. holy shit. really? this isn't GOG.com

THIS IS: https://www.gog.com/

this shit from you is getting old. stop.
