### ISSUE TITLE
Make a Warning on which Issues you Censor

### ISSUE THREAD

**Issue by ghost** [MachineGunnur/GOG-Games#341]
You have three don'ts. The banch of issues that you recently deleted does not fit into this.

Do you wanna be like a dictator and censor? Your choice, though mind you: I truly hate dictators, old jerks and assholes. The same as your choice to be sexist or work alone yet weirdly call oneself "we", like you're some kind of a royal.

And it was your choice to silence a very important warning that "Hitman GOTY" has DRM and you do allow this improper crap which violates what GOG is, and your choice to keep the old unworkable DLC for an updated "Brigador" or to always prefer freshness, not quality with quantity like I do. I am solo responsible for you being able to check installers and other things, you did nothing in that field, you only, quote, "collect shit," not games, that tells the attitude of yours well. I cannot express any respect for such lack of standards.

People for you are not people but literally your money bags to exist for free. As all the people know, you mainly take games from Tapochek or Torrminatorr with no thanks, no respect and no credits. You don't pay for buying games, the people do, then you take and want the people to pay for your rent. This is crooked. I know you from the day one, and I know and remember how you tried to kill Torrminatorr's links by sending DMCA notices. You cannot just silence me or pull away, I am younger and I hold the truth, I will live far more than you do. You may not like me but I am the future, you are the past.

Be a smart dictator and write what you censor, so everyone can see who you are.

**Comment by Masamune3210** [comment]
Are we really doing this again? What is with all the malicious issues and responses

**Comment by MachineGunnur** [comment]
omfg
