### ISSUE TITLE
About recaptcha, help pls?

### ISSUE THREAD

**Issue by hellwalker31** [MachineGunnur/GOG-Games#347]
Hi, tx for this nice work. But i have a little problem so requiring a little help. When i try to download a game, i get a recaptcha problem most of the times saying me recaptcha couldnt be load, check your connection. And ny only recaptcha problem is about this site. I check on mobile phone but no problem there btw. Any fix or suggestion about this in mind? Checked the web but nothing yet. Tx

**Comment by MachineGunnur** [comment]
This is on your end. I've had it happen when I visit the site and click a game card before the site finishes loading.

Disable anything that blocks google services.

It's an issue on your end though 100%.
