### ISSUE TITLE
BATMAN ARKHAM ORIGINS

### ISSUE THREAD

**Issue by blues5clues0** [MachineGunnur/GOG-Games#349]
Downloaded it 4 times from zippyshare,1ficher,pixeldrain,uptobox. Game file is corrupt. NO VOTE FOR REUPLOAD button available.

**Comment by MachineGunnur** [comment]
I have downloaded this game from 1ficher, extracted with errors and verified that integrity is intact. Issue on your end.

Verify which RAR parts you download are corrupted. 7zip has that functionally.
