### ISSUE TITLE
Upload Game Rise and Fall: Civilizations at War

### ISSUE THREAD

**Issue by LeeAdam258** [MachineGunnur/GOG-Games#350]
Admin Can you add the game Rise and Fall: Civilizations at War

**Comment by MachineGunnur** [comment]
Closing as:

- Game is NOT on GOG.com
- Also read the stickied issue next time

**Comment by MachineGunnur** [comment]
Closing as:

- Game is NOT on GOG.com
- Also read the pinned issue next time
