### ISSUE TITLE
RimWorld Has No Titles

### ISSUE THREAD

**Issue by ben-ronell** [MachineGunnur/GOG-Games#351]
I'm trying to use Rimworld and I installed the game, then both DLCs. Upon opening it, I found the issue that can be seen in the attached images. There's no text and I don't know how best to go around fixing it. Let me know if you have any suggestions. I installed it with Wine. Is there also any way to install a previous version? I used an older version without the ideology DLC and it worked fine. Thanks for the help.
[
![RimWorld by Ludeon Studios_009](https://user-images.githubusercontent.com/90224047/147861684-9a2a3ea8-788a-4d80-b93c-4bfba4aeed54.png)
![RimWorld by Ludeon Studios_008](https://user-images.githubusercontent.com/90224047/147861686-161a85a4-7d79-4e8c-beb9-117279d86a84.png)
](url)

**Comment by ben-ronell** [comment]
Fixed it, required a specific wine font.

**Comment by Masamune3210** [comment]
Issues like this will never be a problem of the site, as all it does is offer download of the packages pulled straight off of gog
