### ISSUE TITLE
firegirl_hack_n_splash_rescue wrong version

### ISSUE THREAD

**Issue by mjrawesome** [MachineGunnur/GOG-Games#354]
Currently "Game Items Included" show this as: setup_firegirl_hack_n_splash_rescue_1.021_(64bit)_(52247).exe
It should probably be v1.024. So either the name is wrong or an outdated version was uploaded and replaced a more recent version (v1.023).

**Comment by MachineGunnur** [comment]
The game was rolled back. 

https://www.gogdb.org/product/1154894688#changelog

Download changed: Installer, Firegirl: Hack 'n Splash Rescue, Windows, en
Version 1.023 ⇒ 1.021, Size 638.6 MB ⇒ 636.5 MB

Check GOGDB next time.
