### ISSUE TITLE
Replace Google's Recaptcha with HCaptcha 

### ISSUE THREAD

**Issue by parasiteoflife** [MachineGunnur/GOG-Games#355]
Please, make the change. I keep getting errors with ReCaptcha like `Could not connect to the reCAPTCHA service. Please check your internet connection and reload to get a reCAPTCHA challenge.`, other times it gives me challenges over and over (I use hardened Firefox).  

All I've done is open a bunch of games in a new tab (only opened, I haven't clicked on download for the links to be shown), like 30, then closed the ones I don't care about after watching their gameplay, and finally started to download and on the first one I clicked "download" it gave me that error I posted above. 
It seems like you are checking with recaptcha any time an entry is accessed and not when the download button is clicked thus google not allowing me to load the challenge.

Thank you

**Comment by MachineGunnur** [comment]
Hi, this is an issue on our end, not ours.
