### ISSUE TITLE
"Celestian Tales: Old North" FLAC is not GOG's

### ISSUE THREAD

**Issue by undeadlet** [MachineGunnur/GOG-Games#356]
Torrminatorr already fixed the bug with validation 
by JohnnyMic. "cton_ost_flac.rar" isn't GOG, [GOGdb](https://www.gogdb.org/product/1409132640#downloads) and [Connie](https://onedrive.live.com/?authkey=%21APgbl3v0s41kQUQ&id=201ECFA3DD196829%2121848&cid=201ECFA3DD196829)'s checksum show, it was a mistake that wasn't noticed for years and the checksum of the correct file is present below.
```
celestian_tales_ost_flac.zip size 235649360 crc e9038aba md5 21a74456efe936c29027ce7bb4d4cda0 sha1 d84f357bc83794e7b5ebaa20b5d1464d978e12c5
```

Your email has the bugfix for it with the same title as the issue.

**Comment by MachineGunnur** [comment]
i saw your email. i do other things and will get around to it.
