### ISSUE TITLE
Replace hCaptcha with Google ReCaptcha

### ISSUE THREAD

**Issue by Fireviewer** [MachineGunnur/GOG-Games#363]
1. Why sudden rush today, what wasp has bit you? Google ReCaptcha worked well, all stable, there is no logical reason. Proper admins know: If it isn't broke, don't touch it. Please stick with what's stable, no rush, moving steady; This feels too teenagely, all of that back and forth billion times. 
2. hCaptcha is more invasive/annoying. Google ReCaptcha recognizes people and does extensively not annoy users if proven to solve correctly multiple times, this nightmare annoys forever. It kills my soul updating just a dozen of games, I feel myself like a robot, dehumanizing, even more than Google ReCaptcha. Think of your donaters, will a donater be happy to be captcha-hunted? No human will.
3. hCaptcha is heavier/laggier. I need to wait much much longer until it pops up, up to 2-3 times, extremely irritating: Instead of 5 seconds, that's 15. Probably has to do with hCaptcha having less servers close to my location because not everyone is in the EU, a lot of people, I am not the only one.
4. hCaptcha has no accessibility option of a captcha by voice. Not every person using the site might be able to use hCaptcha, the cookie option does not work alrighty for the site in question (too limited) and is very convoluted to set in actuality, then it needs to be refereshed daily or gets lost.

**Alt**
Could you do a Captcha once and then save it for a while? It'll be enough to put away robots and at the same time stop literally harrassing real humans and especially humble game collectors or donators. People deserve to be respected, not mistreated.

**Comment by Fireviewer** [comment]
Want folks to use Torrminatorr instead? Well, you are on the right track with hCaptcha because people will go to what annoys less, remember that. Yes, I know you hate your rival a lot, with this hCaptcha way you make Torrminatorr more favourable: The more you worsen usability, the better your rival Torrminatorr looks.

**Comment by MachineGunnur** [comment]
1. Google has a limited rate for free reCAPTCHA use which is 1 million requests per month
2. HCAPTCHA works on Tor better
3. I was having issue today with reCAPTCHA not loading thus can't view links.
4. My site, not yours. I can do what i want.
5
