### ISSUE TITLE
Cyberpunk 2077 - Missing links for update patch v.1.5?

### ISSUE THREAD

**Issue by RobConner** [MachineGunnur/GOG-Games#367]
Hi MachineGunnur,

First, I want to Thank You for all of your continued efforts to maintain your wonderful site~! When "Good Old Downloads" ultimately shut down a few years back, we all thought that was the end of the era for easily finding GOG games. And now thanks to you, a new era has arisen. Cheers to you!
 
I noticed on the main page that you had recently posted an update for Cyberpunk 2077 - The previous posted update was for v.1.3 4457769_galaxydll_(64bit)_(50001) but when I visited the game page and expanded the download details, I could only see the links for the full game (108.06GB, not including the extras) updated to v.1.5 4719897_dllfix_(64bit)_(53680). The links for just the v.1.5 update 4457769_galaxydll_(64bit)_(50001)to4719897_dllfix_(64bit)_(53680) are missing. Can you please post the links for the v.1.5 update? It would be most inconvenient for me to have to download the full game all over again when all I just need is the v.1.5 update. Any help that you can offer would be very much appreciated! Thanks~!
:+1:

**Comment by Masamune3210** [comment]
Given how big the game's installers and updates can be, it might be hard or impossible to host both due to storage constraints. Just a guess

**Comment by MachineGunnur** [comment]
Due to the patch size, half the game, I decided not to upload the patch files.
