### ISSUE TITLE
Google Drive: Too many users have viewed or downloaded this file recently.

### ISSUE THREAD

**Issue by shakeyourbunny** [MachineGunnur/GOG-Games#38]
Now the whole world has its download restrictions.

To quote Google Drive:
Sorry, you can't view or download this file at this time.

**Too many users** have viewed or downloaded this file recently. Please try accessing the file again later. If the file that you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.

Thank you.

**Comment by shakeyourbunny** [comment]
And yes, I have google for Business. This restriction also applies for that.

**Comment by shakeyourbunny** [comment]
Yes, I followed your instructions, but this is REALLY tiring .. AND I have to remove the "Copy of .." name part from every download.

This is really tiring you know.

**Comment by MachineGunnur** [comment]
write a script to remove it for you ^_^. you are getting the game for free, BTW. buy it if you want an easier way.

**Comment by MachineGunnur** [comment]
rite script to remove for you auto, batch or shell file would be easy, just search Google/

you are getting the game for free, BTW. buy it from GOG if you want an easier way ^_^.

you have better idea? if not, no right to complain i think.
