### ISSUE TITLE
Mechwarrior 5 - installation error

### ISSUE THREAD

**Issue by Kazcade** [MachineGunnur/GOG-Games#382]
I'm getting an error trying to install Mechwarrior during installation/verification, and trying to unpack manually throw a checksum mismatch for Mechwarrior 5\MW5Mercs\Content\Paks\MW5Mercs-WindowsNoEditor.pak

CRCs for the archive are fine apparently.

Can anybody verify if the current version of MW5 unpacks/installs without errors?

**Comment by MachineGunnur** [comment]
fine here. issue on your end.
