### ISSUE TITLE
[suggestion]  games with separate installers for languages

### ISSUE THREAD

**Issue by atesin** [MachineGunnur/GOG-Games#384]
hi....  thanks for your work in this terrific site

in short = how can i download another language versions of some game ?? ....

![proof](https://www.gog.com/upload/forum/2022/03/3dcf7bb9eaba93b77e32e8803e01a10f5bfcc939.png)

in in depth = for example i love tron 2.0, i played decades before and got really fun, but i played in english :( .. i felt very happy when i heard gog will release it (you know, standalone installer, no drm, patched, etc),... but until the game was announced with spanish audio in gog page, i could enable it until a gog user told me about separate installers ;(

i know enough english, i played the game in english way nefore, but this time i would like to replay it in my native language, spanish, more relaxed, catch all the details and enjoy more

any way?, thanks again

**Comment by MachineGunnur** [comment]
I do not have the time or space to keep every single language of a game archived. Sorry.
