### ISSUE TITLE
Add CRC files

### ISSUE THREAD

**Issue by asqwedd** [MachineGunnur/GOG-Games#388]
It would be amazing if you could add CRC files for the games/goodies archives. Downloading can be rough sometimes with interruptions happening and some links being dead. Having an easy way to verify files would reveal all of these issues at a simple command.

I'm talking about a CRC of the compressed archives that your system would automatically create once game files are finished being compressed in a rar. And this CRC file would be placed on each game page as a separate download from the site.

With this in place everyone can be sure their download is correct and if there are corrupt/missing files it is much easier to find the issue.

**Comment by MachineGunnur** [comment]
hi, this is a planned feature once i complete my own re-write of the original project.

i have a tool to extract the checksums from RAR files, so no computing resources would be used to calculate them after compressing for upload.
