### ISSUE TITLE
Expeditions: Rome installer fails with "Source file corrupted". 

### ISSUE THREAD

**Issue by MarEe0** [MachineGunnur/GOG-Games#392]
Title. Tried downloading from two mirrors (zippyshare and 1fichier), same issue with both.

Game file integrity check fails on -1.bin and -2.bin files:
![image](https://user-images.githubusercontent.com/6161381/163282751-45e6700d-146d-4e7f-82d4-dee3f56e4aba.png)

**Comment by AmIntel** [comment]
Investigating, may take around 5 hours to do so (slow connection).

An EXE has BINs' MD5 checksum. On Linux, it can be passed to `md5sum` with the stated number of BINs. Last two numbers before "#" are the total BIN count, the rest of the line from left to right is the 1st BIN, 2nd, etc. The command (replace `"${EXE}"` by an installer's name):
`tac -- "${EXE}" 2>/dev/null | cat -e 2>/dev/null | grep -m 1 -- "[0-9][0-9]#GOGCRCSTRING" 2>/dev/null`

`tac` to read from the end;
`cat -e` to transform binary to text;
`grep -m 1` to find the line, stop searching.

**Comment by AmIntel** [comment]
Manged partial from 9 RARs. The EXE is checked successfully.

The RAR's CRC32, extraction OK:
`1BDFBF65  setup_expeditions_rome_1.4_(55044)-1.bin`

The actual 1st's MD5:
`a642dff7727044e72071fd076af60329  setup_expeditions_rome_1.4_(55044)-1.bin`

What the EXE reports internally:
```
327c4646bdb2c25dd1f58515af30e959  setup_expeditions_rome_1.4_(55044)-1.bin
e3b2d830db4fc4cc1bd9db6877d6a126  setup_expeditions_rome_1.4_(55044)-2.bin
041896ec05502dcff5500e77e08e8632  setup_expeditions_rome_1.4_(55044)-3.bin
3b82d8735012a16e4645f2762f322772  setup_expeditions_rome_1.4_(55044)-4.bin
e6d703e4cb271863d4ab9c29742068c1  setup_expeditions_rome_1.4_(55044)-5.bin
fd42cfc40b459f678b03555fb89f6033  setup_expeditions_rome_1.4_(55044)-6.bin
99019e62b8757d255af7ee2554a65469  setup_expeditions_rome_1.4_(55044)-7.bin
```
