### ISSUE TITLE
No Filelist on "Duke Nukem 2," Duplicates on "Divine Divinity"

### ISSUE THREAD

**Issue by YoshimiShinse** [MachineGunnur/GOG-Games#393]
Please fix the new old bug. Thank you!

**Comment by YoshimiShinse** [comment]
Done.

**Comment by YoshimiShinse** [comment]
"Duke Nukem 2" from 2022-04-25 (3 days ago) is affected.

**Comment by MachineGunnur** [comment]
There is a limitation of the API implemented by the original creators. The API does not return any status when POSTING things to it. So I can't implement any logic to retry if it say adding file list  failed or clearing old download links/file list failed etc.
