### ISSUE TITLE
Impossible to report a game that need the updated version

### ISSUE THREAD

**Issue by ShinyBug89** [MachineGunnur/GOG-Games#395]
As title says, there isn't a way to report a game that has a new version and still there isn't on the site. 

In my case is The Binding of Isaac as example. The download is present but it's out of date and there isn't a way to report it.

There isn't a way to give suggestions, so I opened a ticket here. Sorry for my english and thank you for your work.

**Comment by MachineGunnur** [comment]
It's impossible because I am aware of what is updated 99% as I have custom scripts that track. This would be spam.
