### ISSUE TITLE
Custom Scripts That Track

### ISSUE THREAD

**Issue by YoshimiShinse** [MachineGunnur/GOG-Games#396]
May it be possible to publish the mentioned at #395 as is, up to date, no "Issues" tab, "no guarantees" and no comments from me on it further, and so on?

I think any decent collector would be extremely interested to keep track themselves or modify the work for own needs. Of course you are 100% free to say simple "no" because everyone, who is in the pond for long enough, understands that disclosure might have some unintended consequences. Besides, to old collectors, the prime alternative sources are known, I'm just very curious on your implementation and what the sources are.

This is totally optional, any answer or no answer is welcome. Closing/deleting the issue counts as a "no" answer, making a repo counts as "yes." All fine.

**Comment by MachineGunnur** [comment]
These are private scripts I will not make public. Hint. Scrape GOGDB with python: https://www.gogdb.org/changelog-ext
