### ISSUE TITLE
close combat:the bloody first CRC failure

### ISSUE THREAD

**Issue by armygamer12** [MachineGunnur/GOG-Games#399]
after installing the game and starting it at the loading screen it pops up CRC failure please reinstalled to fix problem but every time I have it does it again please fix this issue thank you really want to play it.

**Comment by yosheer** [comment]
Let me get it straight: MachineGunnur does provide installers that are verified, that's all. It is not really a personal post-install support channel. As far as I am concerned, it's not truly this repo's issue: No problems with installer's own integrity.

My main problem here is you did not supply the essential information, it's too ambigious. Is it this odd Windows 11? It wasn't made in time of 11, it may or may not work and that's to be expected. Same to Linux Wine by the way. It does sound like a reinstall fixes the issue and something later on causing it (?). You could use some punctuation ( . , ) and capital letters (A-Z) to be better understood. I don't ask perfection, I ask it to be slightly more comprehensible.

Please do try older versions of the game and see if it resolves the issue for sure, try to run it on clean legal Windows 7 (preferably), 8.1 or 10, etc, might do Linux Wine as well, favourably do get more witnesses or better yet make a bug report to the devs, so on. Then, if it is definitely a version's fault, report back for all the other folks. Like, I understand your wishes, please understand limits of reality and lack of information.

There were records of some "technically correct" installers giving a messed up versions (rare, really rare). This is the most that can be done of it is truly necessary: Replacement. I am just requesting you to understand that MachineGunnur or I are not magical rainbow unicorn cyberfairies, it's not like any issue post-install is of this domain. Honestly, PC as a platform is nuts, so many factors. Maybe one's antivirus does something funny, maybe the drive dies while screaming in S.M.A.R.T, no idea.

For today, I am not interesyed in personally deeptesting it plus my Internet is absolute crap. Sorry but I have other things to do. You may get relevant help on:
https://www.gog.com/forum/close_combat_series

**Comment by yosheer** [comment]
@MachineGunnur, how about to make a rule to prohibit such class of issues entirely? Might be a good idea.

Simple, like: 
• Do not create issues for post-install bugs in games/DLC

**Comment by yosheer** [comment]
Turns out the devs packaged the installer improperly: It is technically correct, in reality it installs incorrect data. This should be updated and is signed as of today. Alternative (not recommended): Reverse to 1.01.08.0. That's the situation.

*Post Mon Apr 18, 2022 11:50 am*
"This should now have been fixed.
Please make sure you're updated with 1.01.10."
https://www.matrixgames.com/forums/viewtopic.php?f=10359&t=382769

GOGdb has records of a new installer with the same version:
https://www.gogdb.org/product/2096044923#changelog

Please, for any next case, do investigate like that yourself.

**Comment by yosheer** [comment]
Case closed.

**Comment by yosheer** [comment]
My bad, not April. Use this for old versions:
https://forum.torrminatorr.com/viewtopic.php?f=13&p=68319&t=11547

**Comment by yosheer** [comment]
Sorry eMail readers, I am a little chaotic :D

**Comment by heaveneer** [comment]
Judging by the silence, that helped.

**Comment by MachineGunnur** [comment]
agreed
