### ISSUE TITLE
[Suggestion] Bitcoin donation

### ISSUE THREAD

**Issue by thegreatestminer** [MachineGunnur/GOG-Games#4]
I think a lot of users would be interested in donating to you for you to be able to buy games and maybe get better server hardware.

Thanks!

**Comment by MachineGunnur** [comment]
will consider after some time! thank you

**Comment by MachineGunnur** [comment]
added (: https://github.com/MachineGunnur/GOG-Games/commit/e292d8b71ceb4c5d081cd0a87c878b53c6795a5a
