### ISSUE TITLE
[Request] a button to report new update availabe

### ISSUE THREAD

**Issue by Domiuns** [MachineGunnur/GOG-Games#40]
i have try to report you an product not update but i not have any idea how report this.
On your site ⓅⒸ Ⓑⓤⓘⓛⓓⓘⓝⓖ Ⓢⓘⓜⓤⓛⓐⓣⓞⓡ is not the last version because exist 1.3.1 and your site have only 1.2.3, you can update it? sorry for disturb.

**Comment by MachineGunnur** [comment]
no, and no one has shared that new update. that button to me, just SPAM. so no. sorry.
