### ISSUE TITLE
Missing update for Graveyard Keeper

### ISSUE THREAD

**Issue by TheMercenary333** [MachineGunnur/GOG-Games#401]
v1.405 update have been released Graveyard Keeper on 2022.04.19
Could you update this version please? 
https://gog-games.com/game/graveyard_keeper

**Comment by Floatling** [comment]
Please read the rules:
https://github.com/MachineGunnur/GOG-Games/issues/327#issue-947208481

**Comment by Floatling** [comment]
Honestly what the month: People create issues on having not installed the latest version with fixes from the site, on own patholigical inability to use Zippyshare and VPNs, and even directly violate the rules! "Impressive."

You all must know MachineGunnur doesn't usually buy games, the donations go to sustain the server, the games are from other people, many are from the "Torrminatorr" forum. This is the true reason. Another reason is MachineGunnur usually keeps track of updates quite well, if it is publicly available somewhere, it'll be taken.

Go here to ask for an update instead:
https://forum.torrminatorr.com/viewtopic.php?f=13&t=6481

**Comment by grenhunterz** [comment]
> You all must know MachineGunnur doesn't usually buy games, the donations go to sustain the server, the games are from other people, many are from the "Torrminatorr" forum. This is the true reason. Another reason is MachineGunnur usually keeps track of updates quite well, if it is publicly available somewhere, it'll be taken.

Floatling, don't you ever diss MachineGunnur. He has been buying and uploading GOG games long before Torr and without public donations. You don't even know history

**Comment by MachineGunnur** [comment]
please chill out.
