### ISSUE TITLE
DC++, eDonkey, Gnutella & Gnutella2 Mirrors for Free

### ISSUE THREAD

**Issue by unlockier** [MachineGunnur/GOG-Games#403]
The 4 allow to provide an independent download vector, while requiring 0.00% traffic and 0.00% effort from you after creating magnet links for files. Alike was asked years ago, back when "Torrent" was a "no" too, I hope you might make a more beneficial decision. The 4 are takedown-resistant, that's undeniably a big advantage in our turbulent times.

To make for a dir:
```
rhash --recursive --printf='magnet:?dn=%uf&xl=%s&xt=urn:md5:%{md5}&xt=urn:sha1:%b{SHA1}&xt=urn:tree:tiger:%{TTH}&xt=urn:bitprint:%b{SHA1}.%{TTH}&xt=urn:ed2k:%{ed2k}&xt=urn:aich:%{AICH}\n' -- "${PWD}"
```

An example result:
```
magnet:?dn=GOG-Games-master.zip&xl=3176957&xt=urn:md5:efbcf9e73f7fbac2438a07fd27c10666&xt=urn:sha1:Z4IHNDRFQIM2CW2QWA4YRKD2HJIKEXNM&xt=urn:tree:tiger:INJTBVDGZ4LUM6PT6KOXESEAU3NDVL3VUBSZSBI&xt=urn:bitprint:Z4IHNDRFQIM2CW2QWA4YRKD2HJIKEXNM.INJTBVDGZ4LUM6PT6KOXESEAU3NDVL3VUBSZSBI&xt=urn:ed2k:9b10e3cd3c66cc5994e089191caaa6a2&xt=urn:aich:SHHE42YN2QX2GUDSPJTBCT3LVHGDVFRQ

```

Please silently close-lock the issue on a very odd rejection of the opportunity or do notify on affirmative.

**Comment by MachineGunnur** [comment]
why? if you want p2p, use torrent.
