### ISSUE TITLE
DC++, eDonkey, Gnutella & Gnutella2 Mirrors for Free #2

### ISSUE THREAD

**Issue by unlockier** [MachineGunnur/GOG-Games#406]
Could you give up the habit "I have the last word, now I will say 'no,' then shut you up by locking the Issue" please? It's not fine to do that rough.

> why? if you want p2p, use torrent.
1. It's a free mirror. Who denies free stuff? If your paramount is availability and sharing, that's the way. But I guess it's not and you don't want DMCA-ressistant mirrors at all.
2. Torrent too often is dead after a while, as everyone using it sadly notices. Torrent requires people to share 1 very specific GG Magnet "file pack," not more popular R.G.GOGFan with the same files, etc. On the contrary, the 4 are independent, only require someone to share a file somewhere: It's like if R.G.GOGFan's people suddenly became a part of yours.
3. This is not about me, at all, you have totally misunderstood. I, myself personally, content with just having ZippySharre. But I do care that other people have as much access as possible.

**Comment by unlockier** [comment]
Well, my only task was to either show the public that you do not want free DMCA-ressistant mirrors and how crazy odd this is, or to achieve the benefits for others. I'll mark this as non-planned, because it is. Extremely weird.

**Comment by unlockier** [comment]
Unfortunately you chose no free DMCA-ressistant & Torrent-independend mirrors despite it requiring no effort. Crazy eh. It'll be for everyone to see. For everyone to judge your decision. Forever.

**Comment by unlockier** [comment]
Well, nevermind. I guess you don't truly stand for sharing after all.

**Comment by MachineGunnur** [comment]
accept i said no and move on.
