### ISSUE TITLE
Possible issue with FAQ or re-upload request timing

### ISSUE THREAD

**Issue by NotPubliclyAvailable** [MachineGunnur/GOG-Games#409]
FAQ seems incorrect
![image](https://user-images.githubusercontent.com/106768907/171694130-a90f5f2b-875f-4cea-bf4b-684bf6540807.png)
Says "All games are available to be voted on for a re-upload 60 days after they were last uploaded to guard against dead links."
Bannerlord is minimum 90+ days old (not a dead link, but badly out of date) and I see no vote to re-upload button.
![image](https://user-images.githubusercontent.com/106768907/171694575-b496f9be-e6c3-4e90-b904-85d0cf702b3b.png)
Maybe it's just me? But maybe either FAQ is wrong or re-uploading button isn't working?

**Comment by MachineGunnur** [comment]
Uploaded: 30-05-2022 09:07 (from zippy)
Updated: 4 months ago

Working. Know what Updated means. Doesn't mean uploaded.
