### ISSUE TITLE
Looking for the place to notify of broken links...

### ISSUE THREAD

**Issue by Hainswof** [MachineGunnur/GOG-Games#411]
Hello friend,

I am looking for the correct place to notify of broken links on a game, causing the game to be unable to be downloaded.

Reading the pinned post on GitHub, I see...

- Do not create issue(s) for adding Linux/MacOS games
- Do not create issues for missing part(s) from x/y/z hoster
- Do not create issues for out-of-date or missing games/DLC

Can someone point me in the right direction, please? 🙏

Thank you!

**Comment by MachineGunnur** [comment]
What game

**Comment by reaperguy101** [comment]
Not the original poster but the majority of links, according to JDownloader, for Cyberpunk 2077 are missing parts.

**Comment by Hainswof** [comment]
> What game

First of all, thank you for what you have created.

A central place for all DRM free games on the internet is a blessing to have. Especially how simple it is designed and how easy it is to download and play.

Regarding your question, the game I was referring to is Broken Sword: Director's Cut

Link here:
https://gog-games.com/game/broken_sword_directors_cut

Thank you

**Comment by MachineGunnur** [comment]
> Regarding your question, the game I was referring to is Broken Sword: Director's Cut

Did you even check the links? All are up......



> Not the original poster but the majority of links, according to JDownloader, for Cyberpunk 2077 are missing files.

Can't help this much. Already re-uploaded. An automated DMCA take-down company is watching this game, sadly.

Go here: https://pixeldrain.com/u/7AQrqsQQ
Reporter: Anti-Piracy Protection
Look like they automate take-downs for money: https://www.onsist.com/anti-piracy-protection/

1fichier links are up, use those.

Closing.
