### ISSUE TITLE
[Suggestion] Planescape: Torment

### ISSUE THREAD

**Issue by Spider-of-Steel** [MachineGunnur/GOG-Games#412]
Hello...

Baldur's Gate: The Original Saga, Baldur's Gate 2 Complete, Icewind Dale Complete and Icewind Dale 2 Complete, have their respective pages on the site, and this is very good: separating the original games from their Enhanced Editions. But that didn't happen with the original Planescape: Torment, it is still linked with its Enhanced Edition version, and unfortunately, to get the original version it is necessary to download unnecessary files.

My suggestion is as follows: Create a page on the site for the original version of Planescape: Torment and thus unlink it from its Enhanced Edition. This also helps organize versions, as they have significant differences. And in my humble point of view, the original versions are the best!

I think this is a simple task, and if you're not sure which file to move to the page, here's the list of files: https://www.gogdb.org/product/1207658887#downloads

Thanks for listening!

**Comment by MachineGunnur** [comment]
yes I can do.
