### ISSUE TITLE
paranoia problem

### ISSUE THREAD

**Issue by not-NEKO** [MachineGunnur/GOG-Games#417]
Hey I am a bit paranoid and I was wondering if it would be possible to have any proof that the downloaded game is indeed unmodified etc...
As it's not really an issue you can delete this "issue" whenever you want but please give me a response
Thank you

**Comment by Masamune3210** [comment]
There is no proof that could be offered through the site that wouldn't also run into the same issue you are being paranoid about. 
The installers are unmodified, the signatures are still valid from GOG themselves, and the installers check the data archives before even attempting to install them.

**Comment by MachineGunnur** [comment]
> Hey I am a bit paranoid and I was wondering if it would be possible to have any proof that the downloaded game is indeed unmodified etc...

Yes. Purchase  the game on GOG, then compare the two.

Real answer: Every game has a digital signature and you can check if it is indeed valid and signed from GOG.com
