### ISSUE TITLE
data error when i extract hotline miami 2

### ISSUE THREAD

**Issue by Door09** [MachineGunnur/GOG-Games#418]
when i try to extract hotline Miami 2 i get a data error, Miami 1 works  just fine tho

https://gog-games.com/game/hotline_miami_2_wrong_number

**Comment by MachineGunnur** [comment]
This will be closed because:

1. No info on where you downloaded from (Pixeldrain, etc.)
2. It extracted fine for me. Downloaded from Pixeldrain.
