### ISSUE TITLE
A Critical Bug with the Site

### ISSUE THREAD

**Issue by ghost** [MachineGunnur/GOG-Games#421]
> due to the current on-going conflict between Ukraine and Russia

**REMOVE THE SENTENCE TO BE SAFE** *or don't and piss off the sides of the war.*

**Delete my comment & own edit history AFTER you'd cut the quoted, NOT BEFORE.**

Not to use "conflict" because Russia's gov't prohibits the word "war," allows something like "conflict," or "special military operation," only. So you will 100% make Russia's opposition and Ukrainians think you are pro-war or deceived (I am very certain you are, after you are keeping deleting), and a skilled foreigner might read it this way too. If do replace by "war," you'll piss off pro-gov't folks or who believes in that it isn't a war at all, some might even crazily tell "it's Ukraine who fights Ukraine."

Both wording ways you lose someone, and by being so deletional you only harm yourself. Bringing politics in such a way is a tactical and strategic mistake.

> Unfortunately, I do not have the financial means to purchase every single game that is released on GOG.com.

You don't have "any" means, in practice, you said it before yourself. Your rudeness towards my comment doesn't help either. Accept the truth and be truthful with people around you. Don't try to make an illusion you buy games, because you don't.

The last GWENT game is from Razor1991, you did nothing whatsoever to buy it, the previous were from Torrminatorr, and as you said, previously new were from R.G.GOGFan. Your only "credit" is on hosting and combining and re-upload, not on actually getting it. You never even say simple "thank you" to people who make your site alive, which is, to say it lightly, crooked. Everyone working with GOG piracy long enough knows who you really are.

> I have already received very rude emails from individuals who assume they are entitled to every new game GOG puts out. This is very disheartening.

The people believe in the story that you buy games! Be honest, say you copy/steal it from other better pirates and you don't buy games, and get peace, very easy. Stop killing me the messenger, stop spilling your "I will delete you" on me, I bare no responsibility for the crowd. You made this, you must fix it.

> The bills for next month are also due on July 14th. If this is not paid, I will have to severely cut costs (such as remove torrents as I was paying out of pocket myself for seed boxes each month - 30 euros).

Do. For all I care, P2P is a gimmick, and you rejected the free P2P option. It's your choice to waste money.

Be truthful, be wiser, and stop being so ignorant. I'll be insistive this weekend. Ignorance isn't a bliss.

**Comment by MachineGunnur** [comment]
Please relax. :+1:

**Comment by MachineGunnur** [comment]
Please relax. :+1:
