### ISSUE TITLE
"Siberia" is Fake

### ISSUE THREAD

**Issue by ghost** [MachineGunnur/GOG-Games#422]
**Also Delete This Lie.** We all know you aren't in Russia nor a native, your Russian is non-existent, as we both know from Tox's conversations and the fact you were ridiculous enough to think that ".ru" is safe (it isn't) as a domain. In the current environment, it makes zero sense to show up that you're from Russia. Write you are in Armenia or Georgia (Country) instead or write the real country, stop trying to shoot oneself in the feet.

**Comment by MachineGunnur** [comment]
Please relax. :+1:
