### ISSUE TITLE
Everyone is too Lazy for Long Read, Just Say You Need Money (for P2P)

### ISSUE THREAD

**Issue by ghost** [MachineGunnur/GOG-Games#423]
...or simply say you VERY MUCH need money for hosting (true, right?), add some colour to panic up as you usually tastelessly do, with CapsLock in bloody Red. It did work before, it did all the previous years. Also add "I don't buy games" to solve the crowd problem. These people are clearly not the type to read long texts and will likely misread yours and pay wrong hopes.

Example:
"**HELP! CRITICALLY NEED MONEY FOR HOSTING. AND NO, I DON'T BUY GAMES, DON'T BOTHER ME**"

**Comment by MachineGunnur** [comment]
Please relax. :+1:
