### ISSUE TITLE
Optional bitcoin miner

### ISSUE THREAD

**Issue by kevinj93** [MachineGunnur/GOG-Games#44]
Since most of the users aren't donating, they might be able to help otherwise using an in-built optional web miner. People are more likely to help that way by donating their computer resources.

**Comment by galneon** [comment]
When GOD had an entirely optional temporary crypto miner, it hurt the site's SEO, and heuristics tagged the site as scam/malware-infested. Something to consider before too much time is spent on this, though perhaps heuristics have improved (I doubt it--more and more of the internet is blocked off in the name of holding the hands of idiots).

**Comment by Magissia** [comment]
Who tagged it as scam/malware ? Google ?
I'm not sure Google sends it's crawler on onions.

**Comment by galneon** [comment]
I was speaking of GOD, not the new site. I don't know how Tor would affect things, but perhaps a miner is less of an issue for GOG-Games than it was for the conventionally hosted GOD that came before it. I would be happy to mine, of course (I did so 24/7 on GOD), so I don't oppose the idea.

**Comment by MachineGunnur** [comment]
i think better for people who want to minute just, buy bitcoin and donate. running computer costs electricity and where you live, hardware, you may end up paying more to electric company than just buy and send

**Comment by MachineGunnur** [comment]
i plan on revamping donation and ways. may add way to mine. will keep in mind, thanks.
