### ISSUE TITLE
Really! Solution for how to copy MG's links to ur own drive and download.

### ISSUE THREAD

**Issue by hellwalker31** [MachineGunnur/GOG-Games#48]
Well MG's shared with me method also worked. So this is alternative for having a hard time
Pls keep to urselves all these solutions. i know u cant copy the links to ur own gdrive... the solution is easy which i had to find on my own, here i go...
1) sign in with ur account at gdrive (a must)
2) go to the download link provided by MG's onion... 
3) there are 3 points from up to top. click on it and next click on "add star" from the pop menu

now u have all those links in ur gdrive's starred folder...
4)go to starred folders in ur gdrive account. right click on the files u starred from MG's link and click on "copy to my drive" on popped up menu
5) go to ur drive and download "copied folder".
6) after u r done remove the files to ur trash and empty the trash...

hope this contribution helps u guys out.

**Comment by MachineGunnur** [comment]
fyi i didn't write the guide on google, GOD team had this there already. credits go all to them!

**Comment by MachineGunnur** [comment]
hellwalker31 - think this is asame result as make a copy, don't matter if star or not for file ;-)
