### ISSUE TITLE
Inability to request re-upload of: Slay the spire

### ISSUE THREAD

**Issue by Galaxyrapier** [MachineGunnur/GOG-Games#50]
I'm aware the game was updated 15 days ago however 5/6 of its links are broken, only one shows up and it leads to a non-existent google drive. Should I just wait 2 weeks for the re-upload option to appear, hope the issue resolves the next time it's updated(whenever that is) or is it possible for someone in charge to issue a re-upload?

**Comment by sezglt** [comment]
Slay the Spire is 1 URL: Works! Quota is not "non-existent," Google is not Zippyshare (1 URL is OK)

**Comment by sezglt** [comment]
So, wanna re-upload? Done! This link below contains 4 alt URLs. But it'll delete itself after a day
https://bin.privacytools.io/?56141155d62b9e17#mbt8RL2x4i7fv5DvwmwBDLBOSGmF6rxartqdcIk0czA=

**Comment by MachineGunnur** [comment]
what sezglt said.
