### ISSUE TITLE
Revamp donate

### ISSUE THREAD

**Issue by MachineGunnur** [MachineGunnur/GOG-Games#51]
I have a few ideas:

- Bring back the bar - but make yearly, not monthly. Think long term.
- New ways to donate - mining or missing GOG games, maybe?

**Comment by MachineGunnur** [comment]
what should use for mining, what coin, cpu, gpu, program? etc ? any help on this would be welcome

**Comment by sezglt** [comment]
Do not forget to add an option of donating premium hosting accounts, GOD [did have](https://web.archive.org/web/20181115123551/https:/goggames.goodolddownloads.com/donate) this back in time

**Comment by MachineGunnur** [comment]
i add some more donate info. will look for more ways going forward (such as mining). so leave open for now.

**Comment by galneon** [comment]
People aren't going to respond well to the new header message. I suggest removing it before too many people read it, then switching the donation bar to monthly so when people do donate they feel like they're accomplishing more.

You cannot threaten users for donations by giving a doomsday date. No one wants to be the person who donated 2% only to find that by the cutoff date you're at 76% and the site is finished.

It doesn't sound like you penned that message, MG. Whoever did lacks the tact and empathy to write anything for public consumption. You're not an enormous for-profit tracker, and you can't treat your relatively detached user base the same way.

Like I suggested before, if there was any community aspect at all, like there was with GOD, you'd have MUCH better luck eliciting donations, and without threats. GOG-Games is currently radiating negative vibes, and users aren't going to be able to relate to you and your site in the same way they did GOD and their crew.

Honest advice from someone who writes for a living and understands the effects of language.

**Comment by MachineGunnur** [comment]
>  GOG-Games is currently radiating negative vibes

So, all the updates and games we provided exclusively, doesn't matter? We have given to the community since April. 

We needs funds to continue past April 2020. It's a warning. If people can't help US, we can't help THEM.

**Comment by MachineGunnur** [comment]
I corrected my message. I think it explains the situation "better" and hope you believe so too.

We will look into optional mining, at some point. Closing.
