### ISSUE TITLE
about terminator? anyone knows?

### ISSUE THREAD

**Issue by hellwalker31** [MachineGunnur/GOG-Games#54]
Sorry for asking this here but what happened to "terminator"... when u go to terminator, it says "Account Suspended/Deletion Pending " 
any knowledge...

**Comment by MachineGunnur** [comment]
you mean torrminatorr* forum? to me, looks like didn't pay bills.very very, sad to see. all speculation at this point in time though, until more is made known

**Comment by hellwalker31** [comment]
hmm... and admin was on vacation... hope he handles that soon... or...

**Comment by MachineGunnur** [comment]
its returned.
