### ISSUE TITLE
Google Goodies

### ISSUE THREAD

**Issue by MachineJunkie** [MachineGunnur/GOG-Games#57]
Hello! Any way both Zippyshare & Google? Zip only, not for installers. Saves traffic: Goodies are rarely downloaded but Google will help when needed. Or at least can you don't remove working links of already downloaded Goodies when updating? Thanks.

**Comment by MachineGunnur** [comment]
hello MachineJunkie - 

only can use one host as the server all these games are kept on has a monthly allotted upload bandwidth. needs donations to get more. already i personally pay enough.

the GOD/API/Database was designed when a game gets upload all previous links are auto cleared. i think they do this just do be safe from dead, not working, old game files. less work.

at this time, just keep the way it was originally designed. you can get all the stuff, though, so i dont see a problem

**Comment by MachineJunkie** [comment]
Fine, remove but don't deactivate, OK? GG: 2,425 Games; 3,054 installers (4,316 GB); 6,343 Goodies of whom only 86 are +1 GB (244 GB). 3 game installers (like Kingdom Come Deliverance) will take 258 GB. If 3 Games is a problem, I have no words then.

**Comment by MachineJunkie** [comment]
Fine, remove but don't deactivate, OK? GG: 2,425 Games; 3,054 installers (4,316 GB); 6,343 Goodies (244 GB) of whom only 86 are +1 GB. 3 game installers (like Kingdom Come Deliverance) will take 258 GB. If 3 Games is a problem, I have no words then.
