### ISSUE TITLE
Re: GoogleDrive - better file hoster

### ISSUE THREAD

**Issue by shakeyourbunny** [MachineGunnur/GOG-Games#58]
Sorry for creating a new issue, I was going to reply directly, but you locked the topic, sadly, so you do not wish a discussion?

Anyway, currently my purchased game library on GOG consists of about 1700 games, so please.. but I'd like to evaluate the games before obtaining it on GOG and dealing it with Google Drive is REALLY a pain in the bottom, script or not.

You want alternatives? The first one comes in mind is multiup.org which distributes the uploads between a wide array of hoster, so the users can pick and choose to their liking. 

There is also an API available: https://multiup.org/en/upload/from-api
No, I'm not affiliated with this hoster in any way.

Other possibilities:
- https://mirrorace.com/ (has also API), but imho its a bit obnoxious on the user side, but one can live with hit.
- https://multifilemirror.com/ (has API) -- no personal experience
- https://www.mirrored.to/ (has API) -- no personal experience

So there a plenty opportunities to do some down prevention, most of these are limited to 500MB pieces though.

What do you think?

_Originally posted by @MachineGunnur in https://github.com/MachineGunnur/GOG-Games/issues/38#issuecomment-514464600_

**Comment by MachineJunkie** [comment]
@MachineGunnur [said](https://github.com/MachineGunnur/GOG-Games/issues/47#issuecomment-515544939) "I am just revert back to zippy. new uploads will use zippy."

**Comment by MachineJunkie** [comment]
1,741 GOG Games on July 12 by Zippyshare are below, can be used to switch some stuff out of Google:

https://bin.privacytools.io/?284055a3ae2473f8#LzFUkoUeF4Pz4YHIUxtHM1ZUt/B9agaSvqkLtMVzCxA=

**Comment by MachineJunkie** [comment]
Sorry @shakeyourbunny! I don't want to public my scrapped links and have deleted them for my own reasons. If you're receiving notifications, well, honestly you could just use a GNU/Linux distro with curl. @MachineGunnur, if you're receiving notifications, you should ask me for this yourself if haven't backed up own staff before commit changes but if you have a backup, you can roll back 1,741 games with no issue and not a single bit used. You can't imagine my surprise to hear you need to upload already uploaded stuff. Why? That is "Incredible."

**Comment by MachineJunkie** [comment]
P.S. Please do not write anything to me. Thank you!

**Comment by MachineJunkie** [comment]
P.P.S. I mean on #58, this issue only for Google's hoster.

**Comment by shakeyourbunny** [comment]
Hi,

I did get the notifications but be assured that I did not get it, it was already deleted (you know what I mean). It's alright.

**Comment by MachineGunnur** [comment]
shakeyourbunny - 

i did some more testing with **multiup**, seems fine but need to test more. i.e. megaup doesn't work AT ALL, openload wasn't working when i tested last few days ago, now is... O_O T_T. i don't want to upload thousands of files and only gets borked in end - waste of monthly bandwith

**mirrorace** has captcha if you use jdownload.

i actually may  found way to reduce the **crappy "google quota"**. i spend hours yesterday writing and testing code.

also, if you are mass downloading - yes a very big pain to do bypass so, so many times. but i don't see problem if only doing a few times to try a game or two!

to remove the "copy of" requires very simple google skill to learn how to write simple batch or shell script and will auto remove for you to all files with one CLICK! ... :D

i am going to test the google quota reduction workround this week. if not greatly reduces, will use zippy and do some hard testing on mulitup over a next day.

i hope this helps you!

**Comment by shakeyourbunny** [comment]
Really thank you for your effort working on it.

Well  .. mass downloading ... I maintain my private archive on an usb drive where I use lgogdownloader for my purchased games. Alongside that I'm doing some updates unregularily, by going through the other games, copy 'n pasting links and using something like freerapid, then sorting them manually into the folders.

If my money permits and the game is not garbage, I'll buy it at GOG.

Nevertheless I am really grateful that something like this exists and I know the effort of doing such things.

**Comment by MachineGunnur** [comment]
thank you for feedback! also, if google don't work out and if multiup is good - will do a poll so input on which hosters to use is from the users!

**Comment by MiiKe999** [comment]
@MachineGunnur I really thank you for bringing google drive back, which is very handy, I have been bypassing that google drive quota for years by "Make a copy", strictly speaking, the time spent in making a copy, renaming and downloading is still way less of a hassle when it's compared to zippy,openload etc. because their reliability is simply wobbly. Also, not everyone uses 1Gbit/s connection, in that case everything is google drive. I hope you keep google drive.
Thanks for reading and consideration in this regard.

**Comment by MachineJunkie** [comment]
@MachineGunnur, why did not backup own Zippyshare links to reverse for no money? 1,741 of GOG Games are working great! @shakeyourbunny, use Bash, automate yourself. @MiiKe999, Google Drive won't be kept, only hope at least URLs won't be deactivated.

**Comment by 07416** [comment]
Thank you a lot of bringing the other filehosts back.

Sorry if I've been rude in the past.
