### ISSUE TITLE
Missing update - Frostpunk 1.3.3

### ISSUE THREAD

**Issue by galneon** [MachineGunnur/GOG-Games#59]
Frostpunk seems not to have a base installer for 1.3.3, but according to GOGDB a patch from 1.3.2 to 1.3.3 exists. Currently, GOG-Games only has 1.3.2 base.

(Steam has 1.4.0, but those features are either Steam-only, or the developer is screwing over its GOG customers as so many do.)

**Comment by MachineGunnur** [comment]
the file from GOG is named incorrectly, i believe. 

from changelog:
**Patch 1.3.3 (6 February 2019)**

from file: setup_frostpunk_1.3.2.42665.45362_**(2019-02-08_1516)**_(27230)

**Comment by MachineGunnur** [comment]
time stamp of digital signature also, the 8 of February.

**Comment by MachineGunnur** [comment]
1.3.3. bring photo mode. install and confirm, please? if there, GOG just mess up on naming.

**Comment by galneon** [comment]
Confirmed it's just mislabeled. I should've checked the date. Thank you!
