### ISSUE TITLE
Reverting back to zippyshare/using other free filehosts

### ISSUE THREAD

**Issue by kevinj93** [MachineGunnur/GOG-Games#63]
[NOT COMPLAINING/ NOT A BUG] Having everything uploaded to google drive is very risky in case google decides to remove/shut down the account, in case that happens, everything will be gone. While uploading files to filehosts without account requirement (such as zippyshare) is safer and can be re-uploaded easily in case the files expired due to inactivity.

**Comment by MachineGunnur** [comment]
yes, i know. already planned. we have connections for more accounts from google. ;-)

all it takes to reupload everything if that happens is a click of a few buttons and wait a 7-9 days.

reason why there is a storage server power this project.
