### ISSUE TITLE
Missing Data on Google Drive

### ISSUE THREAD

**Issue by totemor** [MachineGunnur/GOG-Games#64]
1. Red Faction Guerrilla Re-Mars-tered
*setup_red_faction_guerrilla_re-mars-tered_cs4931_(23846)-8.bin*
2. Descent
*descent_1_reference_card.zip*
3. Sacred 2 Gold
*sacred_2_gold_ost_flac.zip*

**Comment by MachineGunnur** [comment]
queue for reuploading. be all fixed in ~15 minutes
