### ISSUE TITLE
Add Discord

### ISSUE THREAD

**Issue by Jumbar** [MachineGunnur/GOG-Games#66]
Have made Discord GOG Games Channel. Can add to the Site as a Button? Tnx!

**Comment by MachineGunnur** [comment]
bad idea. discord hates pirates.

**Comment by Jumbar** [comment]
:(

**Comment by MachineGunnur** [comment]
if you had my concern for privacy (and others) you would understand. do as you wish. i am not advertise your discord server on the site.
