### ISSUE TITLE
MultiUp Poll Results

### ISSUE THREAD

**Issue by MachineGunnur** [MachineGunnur/GOG-Games#67]
Results, so far. Top 10, i mean 11! since 1fichier is dead, not working until fixed by MU team.

1. zippyshare.com 
2. drive.google.com
3. openload.co 
4. 1fichier.com (broken atm on MU)
5. uptobox.com 
6. uploaded.net
7. dl.free.fr 
8. megafile.io (limited space, can't do)
9. clicknupload.org
10. 4shared.com (limited space, can't do)
11. letsupload.co 
12. sendspace.com (very unreliable)

**Comment by Jumbar** [comment]
Why no poll about do people need Multiup in the first place?
