### ISSUE TITLE
add New to Batch Tag game area in admin 

### ISSUE THREAD

**Issue by MachineGunnur** [MachineGunnur/GOG-Games#7]

**Comment by HSingus** [comment]
Hi, thanks a lot for the great work, I’m just reporting a small error I noticed.
Don’t know if this happens on other games, on Shogo Mobile Armor Division it shows 
“Last Update: 49 years ago”

**Comment by MachineGunnur** [comment]
done. https://github.com/MachineGunnur/GOG-Games/commit/1e44a5202308bcbe8080cf6e37e03ec010d31803
