### ISSUE TITLE
Add ElasticSearch Instructions to INSTALL.md

### ISSUE THREAD

**Issue by gameisfree** [MachineGunnur/GOG-Games#70]
I have a debian machine running and have followed the tutorial, but I have no idea how to setup ElasticSearch. pls help

**Comment by MachineGunnur** [comment]
the site infrastructure doesn't use original gog install instructions. we use custom docker-compose file (since 2~ months ago?)

it's almost done for public use. so i'll release that repo soon.

**Comment by MachineGunnur** [comment]
If I can get the database template sorted out, I will release this in the next few days.

**Comment by MachineGunnur** [comment]
@gameisfree Here: https://github.com/MachineGunnur/GOG-Games-Docker-Edition
