### ISSUE TITLE
Missing Updates

### ISSUE THREAD

**Issue by ajhix36** [MachineGunnur/GOG-Games#71]
Hi, it's been a while these games have had an update, but the newest version missing from the site, would really appreciate it if you could update em :)

Katana Zero 	1.0.5
Heaven's Vault 1.11

Thank you!

**Comment by MachineGunnur** [comment]
katana zero - YES, can do
heavens vault - NO, none shared. also update not that important :-)

> Update 1.11 (26 July 2019)

    Achievement support added
