### ISSUE TITLE
Timestamps on downloaded files

### ISSUE THREAD

**Issue by shakeyourbunny** [MachineGunnur/GOG-Games#72]
Hi,

can you stop putting the timestamp 01.01.1999 19:00:00 on every file available and let the original ones on them?

This is VERY annoying if you have an archive with files and then you cannot sort by timestamp to catch the recent ones to sort out the old versions....

I do know the reason why (torrenting checksums etc), but this really makes the archive more or less worthless for me. At least please provide a text file with the original timestamps in the archive that the timestamps can be corrected after decompressing.  This could be done before manipulating the timestamps to this arbitrary non-sensical value.

Thank you.

**Comment by shakeyourbunny** [comment]
I fixed it for myself with running a cron job which sifts through the archive hourly, but this is not really a solution, but a bandaid...

**Comment by MachineGunnur** [comment]
no, it's staying that way. we have a good reason as to why its like that. use touch if you want a current date...

**Comment by MachineGunnur** [comment]
I can change it  though to a date in the future. :-)

**Comment by shakeyourbunny** [comment]
The whole point is that the date should not be messed with; but just please leave now the timestamp as is. There is a certain timestamp  I get really mad when I see it, but this isn't this date. 

I only want to say that some real idiots from the console sphere have infected the internet like cancer with their file "distribution" alongside their fixed timestamp. Luckily for me, I could rebuild most of their files in the original form, with proper file names and time stamps.

As already said, I know the reason why this has been done so on your side.

My script is running now once a hour stamping the current time on it, at least there is some "normal" date then on the files. Regarding GOG, the "real" timestamp is imho unknown, so a current one has to suffice.

**Comment by shakeyourbunny** [comment]
Anyway thanks for your efforts, I appreciate your work.

**Comment by MachineGunnur** [comment]
You can touch all your files and directories and get a current timestamp with **touch** in about 30 seconds. They date modified time is made when you download the file from GOG...

Big issue over nothing, touch doesn't change anything in the file. Compare md5, sha256 etc..

**Comment by MachineGunnur** [comment]
Also you can derive the location of someone/server from a timestamp easily. That is why we modify it. This is more important than your "sorting" reasons!

**Comment by MachineGunnur** [comment]
The timestamp is going to be modified still. but it won't be the fixed date in the past anymore.

**Comment by shakeyourbunny** [comment]
Really... I do not want to be impolite, but ...
- I think I mentioned TWICE that I already wrote a script which touches all the 1.1.1999 files. 
- For archiving, metadata is IMPORTANT. You just nuked this for evasion purposes and will make it worse to catch this properly with scripting, really thank you.

You are wrong if you wanna change timestamps for "evasion" purposes. If I would want to locate someone, a timestamp would be one of the LAST things I'd consider for hunting someone down.

Please don't do any such silly games, this is bonkers really.

**Comment by mjr-awesome** [comment]
Take a look at [GOG Times](https://github.com/mjr-awesome/gog-times) (Linux) to set the Time from GOG itself

**Comment by MachineGunnur** [comment]
> Take a look at [GOG Times](https://github.com/mjr-awesome/gog-times) (Linux) to set the Time from GOG itself

@Guessol can do all file types? i see and .exe  and .sh only (may zip too)? need .bin to i think. unless i miss, just quickly looked at - thanks.

**Comment by guedela** [comment]
Sorry if late. GOG Times [is on Gitlab now](https://gitlab.com/mjr-awesome/gog-times). Cannot dmg, tgz, jpg, pdf, pkg, rar but supports 99.70%: Signed exe (includes bin); sh; zip.

**Comment by shakeyourbunny** [comment]
Its a really fascinating piece of hacked code :)

**Comment by shakeyourbunny** [comment]
For best results, try do it the proper way by parsing the Microsoft Authenticode Signature, you will get really frustrated fast :-)

**Comment by shakeyourbunny** [comment]
btw why now on gitlab? it's not really ideologically better than here :)

**Comment by MachineGunnur** [comment]
@guedela  Thanks, i will look into it now and use soon when I get around with the time too! :+1:

**Comment by guedela** [comment]
@shakeyourbunny Github's flagging.

**Comment by guedela** [comment]
My apologies. I can't recognize WTF Github doesn't like. It even nuked an acc who has had a repo only or an acc who had 2  posts without repos and they were okay. I don't see any logic behind its actions. I have no choice but to ghost myself...

**Comment by MachineGunnur** [comment]
OK, implement using GOG Times script for times now!!! thanks again.

**Comment by Vihakijo** [comment]
You're Welcome!

**Comment by mjr-ghosty** [comment]
Should be nothiced: GOG Times vefore 13.0.0 is incapable of timestamping correctly on a non-GMT+0 system timezone. Today GOG Times can time stamp almost all GOG filetypes and a little bit more than that: exe, bin, msi, pdf, sh, torrent, 7z, deb, dmg, iso, pkg, rpm, rar, zip, jpg, png, tar, tar.bz2, tar.gz, tar.xz and mp4. Keep in mind though, no one can magically take EXIF timestamp from a JPG who has none or get date from an unsigned unknown executable.

The original GGT version is, 2019-10-20:
- 45 Lines of Code, 1 Function
- Process 1 File per run, no folders
- Correctly stamps only on a GMT+0 OS
- Supports EXE, BIN, SH and ZIP Filetypes
- Has no Graphical Interface whatsoever
- Painfully slow for a big game installer
- Uses unzip to time stamp ZIP archives
- Has absolutely no exceptions for no Cert

The new GGT version 1.3.4.4, 2019-11-24:
- 861 Lines of Code, 36 Functions
- Can processes any amount of dirs/files
- Does convert GOG GMT to your timezone
- Supports Timestamping of 20+ Filetypes
- Shows Zenity GUI when no options given
- Very fast on installers of any size\*
- Uses 7z for most availible filetypes
- Handles a few files who have no Cert
- Control Folder Applying File Depth (-r)
- Has filter options like "dir/file only"
- Able to output a game installer Title
- Can set your own Manual Date for Data
- Allows to use Quiet Mode (no Messages)
- Makes Extended Attributes (-x Switch)
- Downgrades if don't have some packages

\* To work fast, needs "tac" to be installed

**Comment by mjr-ghosty** [comment]
Excuse me, not "Can processes" but "Can process."
