### ISSUE TITLE
Game changelogs

### ISSUE THREAD

**Issue by 07416** [MachineGunnur/GOG-Games#73]
Have the changelogs been removed from the site? At least in the past full changelogs were provided by the GOG's API and always displayed on the .onion site, when available.

**Comment by MachineGunnur** [comment]
![Screenshot from 2019-08-27 07-22-27](https://user-images.githubusercontent.com/45913297/63779513-2f156a80-c8d6-11e9-8bf0-a50cfbc36f70.png)

**Comment by MachineGunnur** [comment]
need more info if want more help. javascript enabled? using tor browser? version? what game you trying to see if has Changelog etc.

works here in deafult setting in TOR browser. FYI not all games have a CL.

**Comment by 07416** [comment]
This was a NoScript issue. I've configured to allow JavaScript, but my setup was still blocking the element:

![2019-08-28 12_58_16-NoScript Settings - Tor Browser](https://user-images.githubusercontent.com/14923168/63846058-af4dd580-c993-11e9-9638-65632bc25647.png)

Sorry.
