### ISSUE TITLE
Pixeldrain instead of Zippyshare

### ISSUE THREAD

**Issue by Anyfurry** [MachineGunnur/GOG-Games#80]
- Anonymous. [The Site](https://pixeldrain.com) doesn't force to register to download data.
- No blocks. The Site is not Zippyshare, it does not block users.
- [It is free](https://medium.com/pixeldrain/advertising-on-pixeldrain-a-more-honest-approach-d5e00e3f0c29?source=collection_home---6------0-----------------------). Good speeds, no quotas or limits by Download Number.
- Holds files longer. Instead of 30 days with others, there's 60.
- Working [API](https://pixeldrain.com/api). Allows to send or receive files via Curl requests.
- No need for RAR. The Filesize Limit is 10 GB, it is enough for.
- Can give a file [directly](https://pixeldrain.com/api/file/Ba6IvHSJ?download), no annoying pages whatsoever or Java.
- Since the above, should work with JDownloader without an issue.
- Tested by Time. Pixeldrain is more than [4 years](https://www.reddit.com/r/PixelDrain/comments/3gu0wu/what_is_pixeldrain/) old, that's OK.

**Comment by MachineGunnur** [comment]
no, last time removed zippy people got mad.

we have enough hosters now with multiup!
