### ISSUE TITLE
Pixeldrain instead of Multiup

### ISSUE THREAD

**Issue by Anyfurry** [MachineGunnur/GOG-Games#81]
- Anonymous. [Pixeldrain](https://pixeldrain.com) doesn't force to register to upload data.
- No blocks. The Site is not Zippyshare, it does not block users.
- The only reason of Multiup was "Zippyshare blocks." Isn't true?
- [It is free](https://medium.com/pixeldrain/advertising-on-pixeldrain-a-more-honest-approach-d5e00e3f0c29?source=collection_home---6------0-----------------------). Good speeds, no quotas or limits by Download Number.
- No one'll "got mad." Multiup isn't Zippyshare, thus zero risks.
- Holds files longer. Instead of 30 days with others, there's 60.
- Working [API](https://pixeldrain.com/api). Allows to send or receive files via Curl requests.
- No need for RAR. The Filesize Limit is 10 GB, it is enough for.
- Will save you Traffic; more reliable, more friendlier to users.
- Can give a file [directly](https://pixeldrain.com/api/file/Ba6IvHSJ?download), no annoying pages whatsoever or Java.
- The only Sharing who gives links with no ads, redirects or etc.
- Since the above, should work with JDownloader without an issue.
- Tested by Time. Pixeldrain is more than [4 years](https://www.reddit.com/r/PixelDrain/comments/3gu0wu/what_is_pixeldrain/) old, that's OK.
- If to deny a Good Suggestion, people will think twice, I guess.

**Comment by MachineGunnur** [comment]
Stop the fucking spam.
