### ISSUE TITLE
House Flipper Lost URL

### ISSUE THREAD

**Issue by Gontrip** [MachineGunnur/GOG-Games#89]
The 3rd RAR on Zippyshare is not Present

**Comment by MachineGunnur** [comment]
MultiUp part 3 is present. Download it. Closing

**Comment by Gontrip** [comment]
Should I updating 2,537 by Hand, not Bash then?

**Comment by MachineGunnur** [comment]
didnt know house flipper was 2537 games?? WOW!! its one game and there a way to get the last part you need. deal with it. 

know who you are G.
