### ISSUE TITLE
The Uploading Script Requires Improvements

### ISSUE THREAD

**Issue by mjr-awesome** [MachineGunnur/GOG-Games#90]
**Describe the bug**
GG Uploader misses RAR URL for both Multiup or Zippyshare unpredictably

**Expected behavior**
If Uploader fails, shall retry to re-upload a missing part instead of skipping it

**Additional information**
Few Examples: [batman_a_telltale_game_series](https://goggamespc7v6z5e.onion.ws/game/batman_a_telltale_game_series), [house_flipper](https://goggamespc7v6z5e.onion.ws/game/house_flipper), [pathologic_2](https://goggamespc7v6z5e.onion.ws/game/pathologic_2)

**Comment by MachineGunnur** [comment]
There are already check built in the scripts. Something is happening on MU/ZS end. Site unstable, etc. We can't control and it is rare so hard to debug. Closing.

**Comment by MachineGunnur** [comment]
Logging turned on. Open another issue if find a missing part on upload after this date  so I can check logs. Thanks.

**Comment by guedela** [comment]
Please use [GOG Tests](https://gitlab.com/mjr-awesome/gog-tests) to catch the bug yourself, without "-t" it'll use RSS slugs. Isn't perfect but does the task.
