### ISSUE TITLE
Could I Sync my own copy DocKer Version of GoG Database  with  goggamespc7v6z5e.onion Database ??

### ISSUE THREAD

**Issue by tomgates** [MachineGunnur/GOG-Games#94]
I was successful to run a Docker version of GOG.
But How could I sync with your database in http://goggamespc7v6z5e.onion/ ??

**Comment by MachineGunnur** [comment]
what do you mean? i provide a blank database template only. it's if someone wanted to make their own copy, etc. 

if you want our exact 1:1 copy with download links, etc. not happening. ^^

**Comment by iFreester** [comment]
https://github.com/iFreester/GOG-Games-Full-Docker-Edition/raw/master/database.sql

**Comment by tomgates** [comment]
thanks a lot.

iFreester <notifications@github.com> 於 2019年12月4日 週三 下午5:47寫道：
