### ISSUE TITLE
Parchive Backup Enhancement

### ISSUE THREAD

**Issue by AinzuUruGoun** [MachineGunnur/GOG-Games#97]
PAR 2.0 ([Linux](https://packages.ubuntu.com/bionic/par2)/[Multi](https://en.wikipedia.org/wiki/Parchive#Software)). Verification & Repair. Creates PAR files to regenerate original data from a bad disk or transmission. You would be interested in making 1% each as means of protection. 82 GB for 8 TB. Wise to share, quicker to download instead of 100%.

**Comment by MachineGunnur** [comment]
doesnt rar have this? https://www.winrar-france.fr/winrar_instructions_for_use/source/html/HELPCmdRR.htm

https://ss64.com/bash/rar.html

> rr[N]  Add data  recovery  record.  Optionally, redundant information
>           (recovery record) can be added to an archive.

**Comment by MachineGunnur** [comment]
it would be much easier to use RAR would take 5seconds and 3 keystrokes in current scripts! ^^

**Comment by AinzuUruGoun** [comment]
Do you keep' 'em in RAR yourself, honestly? There's many people who don't. If broke, need redownload everything again.

Speaking of RAR, why not use BLAKE2 instead of CRC?

**Comment by MachineGunnur** [comment]
was pain to make rar work in first place. don't feel like requirement and testing for hours... works, stable, why fix not broke IMO 

server has ECC ram, of course. not worried about bitrot as the installers have their own integrity check. too much extra ram for ZFS, not that paranoid, either!

im confused though, wont the RR in rar be enough? https://superuser.com/questions/1362786/how-does-winrar-recovery-record-work

**Comment by AinzuUruGoun** [comment]
What? Just "par2 create -r1 *," that's it, a single command for. Par2 can be trated the same as a game file. Zero worries. Put them into Others/Patches, no rewrite.

Do you test installers? ZFS can use less with the right settings, otherwise go BTRFS, it is less hungry by default. "Paranoid???" Tech does break down, any, sooner or later, unfortunately.

Same, Reed-Soloman Code. But PAR 2.0 avoids the unnecessary overhead of compression,splitting, etc, installers don't compress well by the way.
