### ISSUE TITLE
“MarZ: Tactical Base Defence” Incorrect BIN

### ISSUE THREAD

**Issue by AinzuUruGoun** [MachineGunnur/GOG-Games#98]
The Great Tomb of Nazarick  has independent hashes for 87%, 1.5% were incorrect, 16 games mismatch. This one is the most odd from all of 27 files found.

Able to only guess how much is, truely: Have 45% of GOG Games of which 38.47% is alright, 6.53% needs to be dealt later, haven't 55%. Innoextact can [verify](https://manpages.ubuntu.com/manpages/bionic/man1/innoextract.1.html) on Linux but [1.8](https://constexpr.org/innoextract/changelog).

The hash of EXE is correct, BIN isn't. Torrminatorr has the right one. Nobody warned you for 44 days. Are there other files who aren't OK?

**Comment by MachineGunnur** [comment]
the most likely cause for that is the bin wasn't fully there/downloaded. i am not worried about "bitrot" as  have people who also collect and have copies on hand - backups are better. i checked and the backup is corrupt to for the BIN. most likely, didn't download all the game for the BIN file

**Comment by MachineGunnur** [comment]
game was updated last month - sept 12. bin in the archive just downloaded are corrupt to, so as assumed, the initial download of BIN was incorrect, sadly no one noticed earlier.

**Comment by AinzuUruGoun** [comment]
Yes.Sounds familiar, happend a few times with Drive myself. Sometimes no matter how good your system is, unexpected happens.The independent checksums and test by the app can help.

My abilies in that world are limited. However, to avoid not fully downloaded, I'm always downloading twice from two different devices if a checksum is not availible in advance, then Nazarick hashes plus testing by the app and creating PAR 2.0, don't have time on installing 'em.

**Comment by MachineGunnur** [comment]
Thanks for notification too of corruption download ^^

**Comment by MachineGunnur** [comment]
@AinzuUruGoun funny happen again today. supplier on tracker upload new game in torrent - Crossroads Inn and it was corrupt. hehahaha... now wait for for him to fix.

**Comment by MachineGunnur** [comment]
also can be borked gog package. either way waiting for fix

**Comment by AinzuUruGoun** [comment]
"GOG had put currupt data into own Server as of 26-10-2019. Waiting for updates. Suspended seeding for a while." Now see why BIN occured. Oh P2P.

> Таки GOG тик так в такт. Даже на оправдание ни похоже... Йа криветко Странноветко, мочу метко: «Гогчу за причину, не чудовщину».
