### ISSUE TITLE
Some rar files have CRC check errors. 

### ISSUE THREAD

**Issue by BluePT** [MachineGunnur/GOG-Games#99]
Hi, MachineGunner!

Some files have CRC check errors. Tryed download from several hosts and have the problem in sames files (exemple: Trine 4 - *.r09 and *.r17 gives checksum error - file corrupt all the time. Using JDownloader. I find the same problem in other games.
![Snap1](https://user-images.githubusercontent.com/26176496/68400773-7e96d300-0170-11ea-9b79-6be196552f90.jpg)

**Comment by MachineGunnur** [comment]
hell, 

 just downloaded trine 4 via jdownloader 2 and tested the archives and extracted also fine.

**Comment by MachineGunnur** [comment]
@BluePT also you have older version downloaded. i downloaded 1.0.0.8109_(64bit)_(33560)

lastest from the site - perfect

**Comment by frontideau** [comment]
Others? Run SMART Extended Self-Test.

**Comment by BluePT** [comment]
It seems I have a mix of old files and new ones... don't understand why. Re-download today all zippyshare links and I have the same problem... that's odd...

**Comment by BluePT** [comment]
I found the problem: "the copy links to clipboard" button is pasting some old links to clipboard. I have to past the links one by one... Now all files are ok! Give a look on that MachineGunner... maybe a sync problem... Thanks for your good work!
